### ISSUE TITLE
OS X version loads diags.img instead of boot2.img when new flash is created.

### ISSUE THREAD

**Issue by p0wer0n** [nspire-emus/firebird#10]
This seems to happen even when I don't add diags.img to the flash file. Instead, the diags image is loaded instead of booting to the os.

**Comment by adriweb** [comment]
Was able to reproduce with the latest version.
Vogtinator hinted that it could be related to https://github.com/nspire-emus/firebird/blob/master/core/flash.c#L749
For now, in order not to go to the diags, you can re-create a flash without it, only boot2 and OS (and manuf, but even that is optional).

**Comment by Vogtinator** [comment]
Should be fixed now. If it's not, please reopen!

**Comment by adriweb** [comment]
This specific issue is indeed fixed, however I have noticed some weird behaviour now, that happens with boot2 3.9+, during boot:
```
VSys is below 3.4V!  VSys:-2147480648 VSled:-2147480648 KEY:-2147480648(36000)!
Going Off.
```
which prevents loading the OS.
For now, until we figure it out, boot2 3.2.4 will have to be used instead.

**Comment by Vogtinator** [comment]
Everything should be fine now.
