### ISSUE TITLE
Where are the Boot1 and Flash files at?

### ISSUE THREAD

**Issue by sgrigsby** [nspire-emus/firebird#100]
Configuration asks for a Boot 1 and Flash file for the emulation to work.  Where are these files located?  Searching within the directory shows no such files exist in the zip download.

**Comment by Vogtinator** [comment]
You need to extract boot1 from a calculator.

Please read https://github.com/nspire-emus/firebird/wiki/First-Time-Setup on a guide how to do that.

**Comment by MovGP0** [comment]
unfortunately, the setup process is quite complicated and the documentation is not very clear on that. read the documentation. here are some additional pointers: 

**get the images from the calculator**
- Download the current version of the operating system for your calculator. 
- use the TI-Nspire Computer Link Software (CLS) to install the new OS on your calculator
- download Ndless and polydumper 
- use the CLS to copy Ndless and polydumper on your calculator
![ndless](https://user-images.githubusercontent.com/83339/32255423-1e0f7e18-bea8-11e7-9054-2c98f235dcd4.PNG)

- open the file proper version of the Ndless installer (`ndless_installer_XXXX.tns`) from your calculator like you open a document
- I kinda forgot the next steps, but essentially you should get the boot files this way
![boot](https://user-images.githubusercontent.com/83339/32255452-5d395410-bea8-11e7-81c4-b6ecc74028ca.PNG)

**create the flash file**
- You then need to download and start the desktop version of firebird emu and go to Emulation/Configuration
- select the Boot1 file 
- create a new Flash configuration and select the proper files. it should now look something like this: 
![config](https://user-images.githubusercontent.com/83339/32255523-d3cdaca2-bea8-11e7-8bc1-b40d0b363f1f.PNG)
- save the newly created flash image 
You now should be able to use the emulator on your desktop computer. 

**smartphone setup**
If you want to use firebird on the Smartphone, you need to 
- install the app (requires sideloading)
- copy the flash (created on the desktop), boot2 and .tcc files to the phone

**Comment by adriweb** [comment]
Thanks - feel free to copy that into the wiki somewhere :)

**Comment by EpicBigPPgamer69** [comment]
bruh i have the wrong calculator

**Comment by MovGP0** [comment]
> bruh i have the wrong calculator

I recommend getting the HP Prime 😂

**Comment by Speederchamp** [comment]
Brooo who cares about the law
