### ISSUE TITLE
Software Update doesn't reboot handheld - Android

### ISSUE THREAD

**Issue by Keltorx** [nspire-emus/firebird#103]
I tried to update the OS with a .tcc file downloaded from TI which I transferred via the Send a File option. The install apparently gets completed which requires a reboot. The reboot doesn't occur and the emulator ends in a black screen saying "LCD turned off". It doesn't turn back on even after waiting a while.

**Comment by Vogtinator** [comment]
Likely same as #86 - test bulid is available on https://github.com/nspire-emus/firebird/issues/92#issuecomment-308525700

Can you give that a try and report back?

**Comment by Keltorx** [comment]
The test build provided in the comment allows the emulation to properly reboot. Snapshots of process in imgur album --> http://imgur.com/a/tEZRE
