### ISSUE TITLE
Couldn't start emulation on Samsung Galaxy S8

### ISSUE THREAD

**Issue by Phoenix200571** [nspire-emus/firebird#105]
Hello,

First of all, I just would like to say thank you for your free development, and also to be available to solve the issues... :-)

So I installed your software Firebird_android, but the first time I started the program I had a problem with the permission of the files which the program wants to write on my phone...
By reading the issues topics, I found a software version of firebird called only firebird (The file downloaded, which you uploaded for another user).
Now I have no more this problem, but using the files of ROM you uploaded for Nspire CX CAS with this program, Firebird software says that it is not able to start emulation.
I put also the developpers rights to my phone, but nothing changed.
FYI, ROM and software are installed from my SD card, in a folder I created for that.

I have no more idea to be able to use NSPIRE CS CAS on my phone to follow my idea to be able to help my 2 sons which have also the real calculator TI Nspire (I bought 2 machines for them).

I'm engineer and also to be honest, if I could use this calculator for my work it could be helpful by making programs inside which I will use every days :-)

So that for all these reasons that I ask you to help me.

In advance thank you.

BR
Phoenix

**Comment by Vogtinator** [comment]
I'm not sure how the android permissions system works - I've got Android 6.0 here and it works fine.
Maybe it works properly if you move the file to a different location on the internal storage?

**Comment by Phoenix200571** [comment]
Hello Fabian,

I will try like that.

I will let you know

Best regards.
Frank

De : Fabian Vogt
Envoyé le :mercredi 25 octobre 2017 21:22
À : nspire-emus/firebird
Cc : Phoenix200571; Author
Objet :Re: [nspire-emus/firebird] Couldn't start emulation on Samsung GalaxyS8 (#105)

I'm not sure how the android permissions system works - I've got Android 6.0 here and it works fine.
Maybe it works properly if you move the file to a different location on the internal storage?

**Comment by Phoenix200571** [comment]
Hi Fabian,

I did what you propose and it  works fine.

The only little point I could tell, is that button are not aligned on the screen, if you have some answer to provide, I will appreciate.

In advance thank you.

Best regards

De : Fabian Vogt
Envoyé le :mercredi 25 octobre 2017 21:22
À : nspire-emus/firebird
Cc : Phoenix200571; Author
Objet :Re: [nspire-emus/firebird] Couldn't start emulation on Samsung GalaxyS8 (#105)

I'm not sure how the android permissions system works - I've got Android 6.0 here and it works fine.
Maybe it works properly if you move the file to a different location on the internal storage?

**Comment by Vogtinator** [comment]
> I did what you propose and it  works fine.

Yay!

> The only little point I could tell, is that button are not aligned on the screen, if you have some answer to provide, I will appreciate.

That's a known issue which I sadly do not know how to fix. It somehow only affects samsung devices...

**Comment by Phoenix200571** [comment]
Bad new for Samsung, but I’m happy nevertheless.

BR

Frank

Provenance : Courrier pour Windows 10

De : Fabian Vogt
Envoyé le :vendredi 27 octobre 2017 20:31
À : nspire-emus/firebird
Cc : Phoenix200571; Author
Objet :Re: [nspire-emus/firebird] Couldn't start emulation on Samsung GalaxyS8 (#105)

I did what you propose and it works fine.
Yay!
The only little point I could tell, is that button are not aligned on the screen, if you have some answer to provide, I will appreciate.
That's a known issue which I sadly do not know how to fix. It somehow only affects samsung devices...

**Comment by adriweb** [comment]
Please try the [latest release](https://github.com/nspire-emus/firebird/releases/latest) and reopen the issue if needed (generic comment, might not be 100% related).
