### ISSUE TITLE
[Android O | Firebird 1.3] keyboard not working

### ISSUE THREAD

**Issue by MovGP0** [nspire-emus/firebird#106]
I've using a TI NSpire CX CAS and managed to create the following files: 

used factory images: 
```
TI-NspireCXCAS-4.5.0.1180.tcc
tinspirecx_boot2_3.1.0.16.img
```
extracted with Ndless: 
```
boot2.img.tns
diags.img.tns
boot1.img.tns
manuf.img.tns
```
created using firebird for Windows: 
```
flash
snapshot
```

So I've put everything on my Pixel Phone and started Firebird. However, I get the error message 
```
Detected problems with app native
libraries
(please consult log for detail):
libfirebird.so: text relocations
```
After that the emulation starts up fine, but the keyboard input is not working.

**Comment by Vogtinator** [comment]
> After that the emulation starts up fine, but the keyboard input is not working.

Ok, that is weird. Maybe it just works with the latest build? 
[firebird.zip](https://github.com/nspire-emus/firebird/files/1433661/firebird.zip)

Sometimes keys can get stuck in the pressed position, which makes the OS ignore all other events.

**Comment by MovGP0** [comment]
that one works. thx :-)
