### ISSUE TITLE
firebird 1.4 windows

### ISSUE THREAD

**Issue by Jo900** [nspire-emus/firebird#109]
I'm trying the new version, just few questions:
- why the .zip package have only the .exe ?
- menu configuration "flash & boot1" and "file transfer" are empty.
thanks

**Comment by Vogtinator** [comment]
1. It's statically linked now. Nothing else is necessary anymore.
2. I assume you dropped the 1.4 exe into the 1.3 directory. That won't work.

**Comment by Jo900** [comment]
so is standalone .exe now ? good
