### ISSUE TITLE
ndroid 7.0 and Windows 10 vs Firibird 1.4

### ISSUE THREAD

**Issue by Carloshvb** [nspire-emus/firebird#111]
Hi,

I'm having some problems with this new version (1.4)

**- Windows 10 (have not tested in old versions)**

Even running as Administrator, I'm getting error messages when i try to create a image. I select the files and when I ask to save I get a error message and the image was not created.

But, with the same files, I created the image in a old version (1.1.1) and imported to the new one and now it's running well.

PS: I put it version in a different folder.

**- Android 7.0 (Galaxy S8+)**

I'm getting error saying the that "The image can't be loaded" on my mobile. 

PS1: I'm trying the image I've created into Windows
PS2: I don't have on the mobile version (1.4) a option to create a image directly on my mobile.

Hope this could help the development.

**Comment by Vogtinator** [comment]
> when I ask to save I get a error message

What's the message?

> I'm getting error saying the that "The image can't be loaded" on my mobile.

There's no such message in firebird, what's the exact error?

**Comment by Carloshvb** [comment]
**Windows:**
![image](https://user-images.githubusercontent.com/34339577/33714223-5493490c-db35-11e7-8010-04dd477aab0a.png)

Translation: 
"firebird-emu-windows.exe has stoped working"
"A problem caused the program to stop working properly. Close the program."


**Android**
The message is "Couldn't start emulation"

**Comment by Vogtinator** [comment]
> The message is "Couldn't start emulation"

Try it again with the flash and boot1 files moved to external storage (sd card?).

**Comment by Carloshvb** [comment]
The files are already  in the SD-Card!

**Comment by Vogtinator** [comment]
I'll need the adb log in that case. It's probably permission issues with the RW_ flash mapping.

**Comment by Carloshvb** [comment]
How can I get the adb log?

**Comment by Vogtinator** [comment]
https://support.symantec.com/en_US/article.HOWTO81826.html

**Comment by Carloshvb** [comment]
I delayed, but I did. Hope this is what you need!

[android-debug.zip](https://github.com/nspire-emus/firebird/files/1539923/android-debug.zip)

**Comment by Vogtinator** [comment]
Sadly no usable information in there (at least I couldn't find any), can you try this apk:

[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/1540116/QtApp-debug.zip)

It contains pr #94 rebased on top of current master.

**Comment by Carloshvb** [comment]
Ok, 

Step by Step.

1) I've installed the QtApp...apk withoud any previous action and opened it. Get the same error.
2) I've uninstalled the app and installed it again.
    Then I've selected the files Boot1 and Flash again and it has worked. The first time I couldn't choose the language, but I close the app and in the second flash intall it worked well.

    I noticed that it has a new way to select files, much more easier, and that all the file path was saved in the selection menu.

![screenshot_20171207-172214](https://user-images.githubusercontent.com/34339577/33734436-733c6314-db73-11e7-86bf-a6cb6a458e2f.png)

PS: 1CE0-3CA8 was how my mobile named the SD-Card.

**Comment by Vogtinator** [comment]
Fixed in 1.5.
