### ISSUE TITLE
Nothing happens when clicking the icons on the linux-repo-website

### ISSUE THREAD

**Issue by KronP** [nspire-emus/firebird#112]
Nothing happens when I click on any of the links on the linux-repo-website https://software.opensuse.org/download.html?project=home%3AVogtinator%3Afirebird-emu&package=firebird-emu . Is there any other way to get to the repo?

**Comment by adriweb** [comment]
It works fine here, showing repo URLs etc., as well as a direct link to the binary.
What's your distro ?

**Comment by KronP** [comment]
I am running Ubuntu 16.04 LTS. I tried the link in both Chrome and Firefox.

**Comment by Vogtinator** [comment]
The page works for me as well.

However, Ubuntu 16.04 is too old for Firebird. At least Qt 5.6 is required, which means you'll have to add a PPA with Qt 5.6 and build it yourself.

**Comment by KronP** [comment]
Okey, thank you. Odd that the link does not work for me though (I tried Safari on iPhone too)

**Comment by Vogtinator** [comment]
I just hit the issue for a different package and I found and applied a workaround to the URL now.
