### ISSUE TITLE
Firebird emulator 1.4 for ubuntu x64 (Configuration button not working)

### ISSUE THREAD

**Issue by lexterror** [nspire-emus/firebird#113]
When I click on the "configuration" button nothing happens. So I can't select the boot and flash files.

**Comment by Vogtinator** [comment]
You need to install the Qt Quick Controls 1 module.

**Comment by ijustwantcoverartbrowser** [comment]
Not working for me either on Debian Stretch, and Qt Quick Controls is installed.

**Comment by Vogtinator** [comment]
Only `qml-module-qtquick-controls qml-module-qtquick-dialogs` should be necessary.

The debian packaging of Qt is weird.

**Comment by ortizjeison** [comment]
Thank you so much! It worked perfectly.

**Comment by coolreader18** [comment]
@Vogtinator this worked for me on Linux Mint 19, in addition to installing `qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel`. Is there somewhere that the dependencies for the openSUSE build services are configured? The .deb from there is for Ubuntu 17.10, and it evidently failed to install all the correct dependencies.

**Comment by Vogtinator** [comment]
@coolreader18 None of those modules are used by firebird. If you need to install them, your distro has broken deps.

**Comment by adriweb** [comment]
Was dealt with here, it's the same indeed: https://github.com/nspire-emus/firebird/issues/161#issuecomment-486640563
