### ISSUE TITLE
Snapshot File

### ISSUE THREAD

**Issue by Ouikujie** [nspire-emus/firebird#116]
What is the snapshot file for this emulator?
And how could I create one from my device, otherwise I have to load for one minute on my phone before I can do any calculation.
:persevere:

**Comment by Flnch** [comment]
After you once booted the operating system in the app (which can take fairly long) you can swipe the sidebar from the left and press "save". [https://i.imgur.com/cLphTgn.png](url) This should take a snapshot of the actual system status. I do not actually know if this is the default setting but either the app then automatically starts using this snapshot or you have to go into the app's settings (again via the sidebar) and there in the flash tab choose the file "myFlash.bin" for "Flash".

**Comment by Vogtinator** [comment]
Note that you need to configure a location where to save the snapshot to.
The mobile UI is unfortunately hard to use as Qt Android's file dialog is the worst I've ever seen.
You'll have to navigate to the destination folder and then enter the filename in the input field at the top and tap "Save".
