### ISSUE TITLE
Issues on Android 7.0. 

### ISSUE THREAD

**Issue by JuanDGFlorez** [nspire-emus/firebird#120]
Hi everyone, i've installed it on my Huawei Y7 with Android 7.0. It opens, but when im looking for the Boot, Snapshot and the other one. It doesnt find the files or it doesnt show them i granted all the permissions to the app but it doesnt work. 
Does anybody knows how to fix it? 
Thank you all

**Comment by Vogtinator** [comment]
Did you navigate to the right folder? Where/how did you transfer the files?

**Comment by JuanDGFlorez** [comment]
Hi, problem solved, i dont know what caused it but today i tried again and it was showing them. 
Thanks

**Comment by Vogtinator** [comment]
Ok. This means it was either a OSI layer 8 issue or a bug in the file selection dialog, both of which can't be fixed in firebird.
