### ISSUE TITLE
Window not visable, program does not terminate.

### ISSUE THREAD

**Issue by GiovanH** [nspire-emus/firebird#121]
System: Windows 10 x64
Problem: When I launch the program, a white window flashes for a split second, and then vanishes. The process does not crash or stop. Hovering over the icon in the taskbar shows a blank white rectangle, but clicking it does not show the window. 

The program worked perfectly fine last week, and no major system changes were made in the spanning time. 

The program does not seem to generate relevant logs, or if it does, I'm not sure where to find them.

**Comment by Vogtinator** [comment]
My guess is that you received a broken graphics driver update which broke OpenGL. Please try to run firebird in a terminal and provide the output.

**Comment by GiovanH** [comment]
Wait, I think I know that the issue is, and boy was I stupid. This was literally a windowing issue: the program was trying to render on monitor 2, even though only one was connected. I'm sure that's an operating system glitch and not one with the program.

Close this issue, I guess.
