### ISSUE TITLE
Desktop file fails desktop-file-validate due to "DesktopUtility" category.

### ISSUE THREAD

**Issue by TC01** [nspire-emus/firebird#122]
I finally got around to updating my Fedora package of firebird-emu. Our policy requires running ```desktop-file-validate``` over all installed desktop files. When I did so, I discovered the following error:

"value "Qt;DesktopUtility;System;Emulator;Education;Math" for key "Categories" in group "Desktop Entry" contains an unregistered value "DesktopUtility"; values extending the format should start with "X-""

Poking around [this freedesktop page](https://standards.freedesktop.org/menu-spec/latest/apa.html) I don't see a "DesktopUtility" category listed. I think therefore this should be changed to X-DesktopUtility, although I am not sure.

**Comment by Vogtinator** [comment]
Apparently I made a bad choice when searching for an example - the desktop categories aren't that easy to pick.

Should be fixed now, thanks for the report!
