### ISSUE TITLE
NAND ECC not being calculated when writing manuf

### ISSUE THREAD

**Issue by parrotgeek1** [nspire-emus/firebird#123]
There seems to be an issue with how NAND ECC is handled, at least on non-CX.
For example, the program hwMod (https://tiplanet.org/modules/archives/download.php?id=6733 / source code in zip), which has been verified by me personally to work in real hardware on OS 3.1, results in an ECC error on reboot, on firebird and nspire_emu. It seems like the new ECC isn't even being calculated; it's just all 0xFF. On real hardware, the NAND controller automatically calculates the right ECC.

(You can modify the code to not check the ASIC flags to make it easier to test, or just use "ncas2cas" in the same zip)

**Comment by Vogtinator** [comment]
Is the ECC written?

The hardware only provides on-the-fly calculated ECC, which the OS then has to read from special registers and write into the OOB area.

The code implies that there's never been proper understanding of when and how to calculate ECC, so it's not unlikely that something might be wrong there.

The code also contains
```
                    // Set ECC register
                    if (!memcmp(&nand_data[0x206], "\xFF\xFF\xFF", 3))
                        nand.phx.ecc = 0xFFFFFF; // flash image created by old version of nspire_emu
                    else
                        nand.phx.ecc = ecc_calculate(ptr);
```

is that the case for your flash image?

**Comment by parrotgeek1** [comment]
No, that is not the case. I already checked it and tried to create a brand new flash image with firebird master code I compiled myself today.

**Comment by parrotgeek1** [comment]
Also the ECC is written, yes, the old ECC is replaced by alll FF

**Comment by Vogtinator** [comment]
Ok, that's good to know. As you compiled firebird yourself - can you set breakpoints on reading the `nand.phx.ecc` register and the `ecc_calculate` function?

If `ecc` is read but `ecc_calculate` is never called, it's confirmed that the OS expects a calculated ECC while firebird doesn't provide that.

**Comment by parrotgeek1** [comment]
I'm going to do that. I just noticed that only the LAST block written has blank ECC. the others are all correct

**Comment by Vogtinator** [comment]
I suspect that the last write access doesn't write a whole page - if you pad the contents with the old data at that place, does it work?

firebird only calculates ECC If a write request writes a whole page:

```
                if (nand.phx.op_size >= 0x200) { // XXX: what really triggers ECC?
                    // Set ECC register
                    if (!memcmp(&nand_data[0x206], "\xFF\xFF\xFF", 3))
                        nand.phx.ecc = 0xFFFFFF; // flash image created by old version of nspire_emu
                    else
                        nand.phx.ecc = ecc_calculate(ptr);
                
```

**Comment by parrotgeek1** [comment]
I don't see why not. I am reading and writing exactly 0x20 pages at once.

**Comment by Vogtinator** [comment]
Then please turn on debugging in firebird and look at the write operation block sizes.

**Comment by parrotgeek1** [comment]
I'll do that tomorrow; it's 1 am

**Comment by Vogtinator** [comment]
Any news?

**Comment by parrotgeek1** [comment]
Sorry, I've been really busy and I'm traveling this weekend, then
university classes start again on Monday. I'll try to look at it more soon.

**Comment by parrotgeek1** [comment]
I am no longer developing anything that would use this functionality and thus I am unable to test it.
