### ISSUE TITLE
Does firebird support boot1>4.0

### ISSUE THREAD

**Issue by A-Shahbazi** [nspire-emus/firebird#128]
I encountered boot1.5>4.0 backups and I was wondering if firebird supports booting TI-Nspire CX with that(Instead of boot1 3.0.0.99)

**Comment by adriweb** [comment]
Boot1.5 is not the same as boot1, and cannot he uses as a replacement of boot1.

**Comment by Vogtinator** [comment]
As @adriweb said, Boot1 != Boot1.5.

You need to use boot1 3.0 or boot1 4.0 as boot1, the flash image from any known calc version is supported.
