### ISSUE TITLE
Can't load flash

### ISSUE THREAD

**Issue by kenzierocks** [nspire-emus/firebird#13]
I've used `Create flash` 3 times now, but it doesn't seem to do anything. I can't see a `Load flash` option, and all `Create flash` has done is make files. Is there something I'm missing?

**Comment by Candunc** [comment]
First of all, launch firebird. Click settings, then click Nspire. Choose your boot1.img file by clicking select file underneath the text, and do the same with the Flash on the right hand side. Then go to emulation in the top left menu, and click restart. 

It's not a terribly intuitive program at the moment, however the emulation does work well.

**Comment by kenzierocks** [comment]
Awesome, thanks. Works well, and wiki pages will be useful.

**Comment by Vogtinator** [comment]
> It's not a terribly intuitive program at the moment

Any suggestions?

**Comment by adriweb** [comment]
When the flash creation is finished, what about a dialog that asks the user if he wants to [re]boot the emu using the newly created flash?
