### ISSUE TITLE
How to use the app (Android 7.1)

### ISSUE THREAD

**Issue by Ti64CLi** [nspire-emus/firebird#133]
Firebird don't want to start, after choosing a boot1. It says I gotta choose a Boot1 or a Flash image

**Comment by Vogtinator** [comment]
Well yes, you need to select a boot1 and a flash image.

**Comment by Ti64CLi** [comment]
What is a flash image?

**Comment by adriweb** [comment]
The iOS and Android versions require you to provide a ready-to-use (already made) "flash image" which is like a dump of the calc, in this case a binary file generated by the desktop version of Firebird. So basically use that first ([see here](https://github.com/nspire-emus/firebird/wiki/First-Time-Setup)), transfer boot1 and flash to your mobile app, then in the settings (swipe left in the app), select it and restart emulation.

**Comment by Ti64CLi** [comment]
Yes, but the desktop version of firebird doesn't work on my laptop :(

**Comment by Ti64CLi** [comment]
And can't we make a flash image directly on the android version?

**Comment by adriweb** [comment]
> Yes, but the desktop version of firebird doesn't work on my laptop :(

You should be making an issue about that, then.

> And can't we make a flash image directly on the android version?

We cannot indeed.

**Comment by Ti64CLi** [comment]
I'm sorry but I only have one last question:

> And can't we make a flash image directly on the android version?

> We cannot indeed.
Why?

**Comment by adriweb** [comment]
Ask @Vogtinator about it ¯\_(ツ)_/¯

**Comment by Ti64CLi** [comment]
Ok, thanks a lot
