### ISSUE TITLE
Firebird doesn't work on my laptop

### ISSUE THREAD

**Issue by Ti64CLi** [nspire-emus/firebird#134]
The desktop version of firebird doesn't work on my computer, under Windows 7.
I can run it, but he freezes then :(

**Comment by Vogtinator** [comment]
Which version did you try? When does it freeze?

**Comment by Ti64CLi** [comment]
Version 1.4. It freezes just after launched it

**Comment by ammonteir** [comment]
Firebird 1.4 doesn't work properly on my computer either (Windows 8.1). I can start and run the emulator but can't create (save) or load a Snapshot .img file. When trying to save a Snapshot, program returns an error ("Could Not Suspend") When trying to load, program returns "Could Not Resume". I've tried on other computer running Windows 7 and it worked well with the same files. On Android also worked with the same files (note: when exiting, Android says "Firebird has stopped"). I've tried to change .exe to run in compatibility mode and/or run as administrator but get the same errors.

**Comment by ammonteir** [comment]
Firebird 1.4 started to work well on my computer running Windows 8.1 now. I just moved the Firebird folder that I've created from the desktop to C:\Program Files (x86) and re-created Flash and Snapshot files from there. Somehow it worked on that folder, I can't say why. It was not necessary to do that on the other computer running Windows 7, it worked well on a desktop folder.
