### ISSUE TITLE
Add flash image creator to mobile versions

### ISSUE THREAD

**Issue by Ti64CLi** [nspire-emus/firebird#135]
It's not an issue, more a request.
Can you add a flash image creator to the Android version of firebird?

**Comment by Vogtinator** [comment]
I re-enabled the QWidget-based flash dialog and it seems like it technically works - but it doesn't look or behave right. You can give it a try:

[firebird.zip](https://github.com/nspire-emus/firebird/files/2246560/firebird.zip)

Something like a first time setup wizard is probably the best option here.

**Comment by Ti64CLi** [comment]
I'll try it.
Thanks a lot
