### ISSUE TITLE
"Touch Screen" Selection

### ISSUE THREAD

**Issue by ammonteir** [nspire-emus/firebird#139]
Is it possible to implement a "Touch Screen" feature to select previous answers directly instead of using the "Touchpad"? That would work the same as HP Prime emulator (on Android you can touch any answer on stack to use it for other operation and on Windows you can use the mouse pointer directly to any answer as well). That would be a great feature specially on Android version.

**Comment by Vogtinator** [comment]
That can't be done by firebird itself, it would need integration into the Nspire OS (probably using Ndless) as there is no absolute pointing device.

The HP Prime software is not an emulator, so doesn't have any of those restrictions.
