### ISSUE TITLE
Support for Shift+[Key] to generate symbols

### ISSUE THREAD

**Issue by kenzierocks** [nspire-emus/firebird#14]
Currently it seems that using `Shift` to generate symbols doesn't work properly. Some examples are `Shift`+`9`=`(` and `Shift`+`.`=`>`. Generating capital letters and the like is ok. I assume this is because the TI doesn't map symbols for `Shift`.

**Comment by Vogtinator** [comment]
The Shift button on the keyboard is directly mapped to the Nspire's shift button,
so even if ) would press the calc's ( key, it would do so with shift pressed, resulting in [].
It could be implemented in theory, but that would be pretty complex and cause various other issues.

**Comment by mstallone** [comment]
From my experience using the emulator and my handheld, I feel the shift key is not that useful. The functions on the calculator are case-insensitive ("solve" is the same as "sOLVe"); the only reason one would need a capital letter is if they are taking notes. However, parentheses are far more useful; they are necessary for math and functions. Would it be possible to toggle between mapping the shift key to calculator's shift key and mapping the keyboard shift+key to the calculator's said key ('shift'+'9'='(')? What I find interesting is the way the TI-Nspire CX CAS Student Software implements the shift key: if shift is pressed with letter, the calculator receives shift+letter; however, if the shift is not with a letter (i.e. 'shift+'9'), the calculator receive the generated symbol (for '9,' it would be '(').

**Comment by Vogtinator** [comment]
That's definitely possible to implement, it's a bit of work, however, as there would be a need for one big keymap, mapping each host key (or ascii char?) to a nspire key combination.
TINCS is not an emulator, it is simply the software that is running on the calculator recompiled as DLL for use with Java, so no need for keymapping.

**Comment by Vogtinator** [comment]
This is basically implemented now.

**Comment by truthadjustr** [comment]
I can't find where is the single quote  ' ?
