### ISSUE TITLE
Couldn't start emulation on Android 7.1.2

### ISSUE THREAD

**Issue by puretrance** [nspire-emus/firebird#146]
"Couldn't start emulation" on Android 7.1.2
APK from https://github.com/nspire-emus/firebird/issues/111#issuecomment-350049067 does not work too.
All paths are on internal storage : /storage/emulated/0/ ..., there's no external sd card.
I don't know what else to say.

**Comment by puretrance** [comment]
Files are located on internal storage. They are displayed as
primary%3Atinspire%2FBoot1cx.img
Also, fonts are too big, and some elements in settings don't fit the screen (1280x720, xiaomi redmi 4).
In portrait orientation, you can't "Select" files, also, on other tabs, some text doesn't fit.

**Comment by Vogtinator** [comment]
> Files are located on internal storage. They are displayed as
primary%3Atinspire%2FBoot1cx.img

Ok, that should work. I'll try something different based on other suggestions and create an APK based on Qt 5.12 and git master.

> Also, fonts are too big, and some elements in settings don't fit the screen (1280x720, xiaomi redmi 4).
In portrait orientation, you can't "Select" files, also, on other tabs, some text doesn't fit.

Screenshot please. I've got 1280x720 resolution here as well and it looks fine.

**Comment by Vogtinator** [comment]
Here is a build of git master with Qt 5.12.0 and clang with explicit requesting of storage permissions on startup (fully untested, so might crash):

[firebird.zip](https://github.com/nspire-emus/firebird/files/2753097/firebird.zip)

**Comment by puretrance** [comment]
Hi, this doesn't work either.

> Screenshot please. I've got 1280x720 resolution here as well and it looks fine.

On the first start, buttons does not fit, https://i.imgur.com/WOQqYE9.png
but when files are selected, buttons are displayed in-place: https://i.imgur.com/Q6ckUqC.png
Also, the text did not fit on other tabs too, but this time it was normal.
Also, when changing orientation to horizontal, and then back to vertical, calculator buttons disappears (only on this version): https://i.imgur.com/hAfXIBJ.png

**Comment by adriweb** [comment]
Looks like a DPI-related issue. We haven't had that in a while have we?

**Comment by Vogtinator** [comment]
Yup, looks like it has both doubled the font size and the display scale... Not sure what to do there, especially not without an effected device.

**Comment by puretrance** [comment]
> Did you get a prompt on first start?

Yes, there was a prompt to read/write permissions.

Have recreated flash on PC, and it started to work (on all three versions).
However, the image is a bit blurry: https://i.imgur.com/JOmst9V.png

And some other bugs:
Not all keys fit in the screen, and when you scroll it, some keys occasionally pressed.

When changing screen orientation, Configuration is automatically opens.

Keyboard disappears only on one (latest) version.

**Comment by Vogtinator** [comment]
> Have recreated flash on PC, and it started to work (on all three versions).

How did you create the flash before?

**Comment by puretrance** [comment]
Downloaded sample files from here: https://www.intereseducation.com/resources/how-to-emulate-ti-nspire-cx-cas-touchpad-on-android-ios-with-firebird/
I believed it should work.

**Comment by Vogtinator** [comment]
Snapshots are not guaranteed to work across version changes and platforms (64bit/32bit Android/iOS), but the flash should theoretically work fine.

Note that that webpage is illegal though.

**Comment by Vogtinator** [comment]
Fixed in 1.5.
