### ISSUE TITLE
Configuration and gui issues.

### ISSUE THREAD

**Issue by NicholasCousar** [nspire-emus/firebird#148]
Trying to set up the emulator in Ubuntu 18.04 lts. When I launch firebird-emu I am not able to select/change anything in the configuration dialog box; here's what it looks like https://imgur.com/a/2mN57r5. I'm also not seeing anything resembling a "kit management page" or "boot1 row". Does anything from the terminal message explain this? 
```
nicholas@klaus:~/Apps/firebird/build$ ./firebird-emu
QObject::connect: signal not found in QLineEdit
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QApplication
qrc:/qml/qml/ConfigPageKits.qml:68:13: Type FileSelect unavailable
qrc:///qml/qml/Firebird/UIComponents/FileSelect.qml:15:26: Type FileDialog unavailable
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed
qrc:/qml/qml/ConfigPageFileTransfer.qml:36:26: Type FileDialog unavailable
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed
```

**Comment by NicholasCousar** [comment]
I was able to sort it out somewhat from this previous [thread](https://github.com/nspire-emus/firebird/issues/113), but I'm still having a few issues with the interface. [This](https://imgur.com/a/GUOIoci) is what it looks like now. 
And here is the terminal output when I launch ./firebird-emu
```
nicholas@klaus:~/Apps/firebird/build$ ./firebird-emu
QObject::connect: signal not found in QLineEdit
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QAction
QObject::connect: signal not found in QApplication
qrc:/qml/qml/ConfigPageKits.qml:34:9: QML GridLayout: Binding loop detected for property "columns"
qrc:/qml/qml/ConfigPageKits.qml:34:9: QML GridLayout: Binding loop detected for property "columns"
qrc:/qml/qml/ConfigPageKits.qml:117: TypeError: Cannot read property 'snapshot' of null
qrc:/qml/qml/ConfigPageKits.qml:90: TypeError: Cannot read property 'flash' of null
qrc:/qml/qml/ConfigPageKits.qml:71: TypeError: Cannot read property 'boot1' of null
qrc:/qml/qml/ConfigPageKits.qml:59: TypeError: Cannot read property 'name' of null
qrc:/qml/qml/ConfigPageKits.qml:117: TypeError: Cannot read property 'myData' of null
qrc:/qml/qml/ConfigPageKits.qml:90: TypeError: Cannot read property 'myData' of null
qrc:/qml/qml/ConfigPageKits.qml:71: TypeError: Cannot read property 'myData' of null
qrc:/qml/qml/ConfigPageKits.qml:59: TypeError: Cannot read property 'myData' of null
```

**Comment by NicholasCousar** [comment]
Update 3: I was able to create a flash, but now It freezes on the [splashscreen](https://imgur.com/a/Kx3frgb) every time I restart with kit. 
```

Boot Loader Stage 2 (4.4.0.8)
Build: 2016/8/10, 16:32:3
Copyright (c) 2006-2016 Texas Instruments Incorporated
Using production keys

Clocks:  CPU = 156MHz   AHB = 78MHz   APB = 39MHz
Checking for NAND: NAND Flash ID: Generic 1 GBit (0xA1)
This device is a CXCR.
TI_PM_SetShipMode:  FALSE
Unknown LCD(0x00 0x00 0x00).


Initializing graphics subsystem.
Unknown LCD(0x00 0x00 0x00).
Boot option: Normal
Found a pre-installed Phoenix image.
Waiting for load instructions.
```

**Comment by Vogtinator** [comment]
>  module "Qt.labs.folderlistmodel" is not installed

Your distro has a broken Qt packaging, please report it.

> Update 3: I was able to create a flash, but now It freezes on the splashscreen every time I restart with kit.

It's not frozen, it's waiting for you to follow the instructions on the screen.

**Comment by NicholasCousar** [comment]
> It's not frozen, it's waiting for you to follow the instructions on the screen.

My bad, for some reason the keypad only works with the right-mouse click button. It will occasionally power off and say "LCD screen turned off" when it it's under a heavy load, but other than that it works! Thank you.

**Comment by Vogtinator** [comment]
> It will occasionally power off and say "LCD screen turned off" when it it's under a heavy load

That sounds weird - did you enable the turbo mode by any chance? That means that it goes into power saving mode more quickly when it's idle.

The GUI scaling issue should be fixed with #150.

**Comment by NicholasCousar** [comment]
I don't how to enable turbo mode. Could It be from the [Power Standby](https://imgur.com/a/LjW1bL6) settings?

**Comment by NicholasCousar** [comment]
Also, how do I enter a plus symbol with the keyboard. Normally it's "shift+=" but that brings up the [Integral Template](https://imgur.com/a/rL468XS) on the calculator.

**Comment by Vogtinator** [comment]
> I don't how to enable turbo mode. Could It be from the Power Standby settings?

Nope - by pressing either F11 or on the speed button.

> Also, how do I enter a plus symbol with the keyboard. Normally it's "shift+=" but that brings up the Integral Template on the calculator.

That seems to be a conflict with the us/uk keyboard layout - does the numpad + work?

**Comment by NicholasCousar** [comment]
> That seems to be a conflict with the us/uk keyboard layout - does the numpad + work?
I should have clarified that I am using this on a dell laptop, so I don't have a numpad or a numlock key. Is there a way to edit the keybindings so I don't have to click the ` + ` on the gui keypad every time I want to add?

**Comment by NicholasCousar** [comment]
Not entirely sure how to implement your gui changes/updates to the cloned Repo on my local machine (I'm very inexperienced with git). But, I sorted out the keypad shortcuts. Addition symbol is "ctrl+shift++".

**Comment by adriweb** [comment]
> file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
> file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed
> file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
> file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed

Was dealt with here: https://github.com/nspire-emus/firebird/issues/161#issuecomment-486640563
