### ISSUE TITLE
Keypad does not appear on Windows

### ISSUE THREAD

**Issue by Candunc** [nspire-emus/firebird#15]
Try to ignore the lack of the tabs, I clicked x on them all and they vanished. They can be restored.
However, keypad is just a white box. Clicking doesn't seem like it causes any response.

![capture](https://cloud.githubusercontent.com/assets/549161/9983363/5372321a-5fb6-11e5-8035-35cf58f469a5.PNG)

**Comment by adriweb** [comment]
Looks like the QML things (which is what's powering the Keypad front-end side) doesn't load properly.
I believe we have seen this specific issue in the past, I'm not sure what we then did... @Vogtinator may remember.

**Comment by Vogtinator** [comment]
Might also be a OpenGL issue, Qt requires OpenGL >= 2.1 to be supported.
I'll have a look at this one today!

**Comment by Vogtinator** [comment]
Fixed, some files were missing from the zip. If there's still a problem, please reopen!
