### ISSUE TITLE
firebird screen resolution on tablet

### ISSUE THREAD

**Issue by Charios01** [nspire-emus/firebird#151]
Hi,
am surprised about firebird and it's good working. By using on a Nexus 10 tablet (screen resolution 2560x1600) I get in vertical position the complete Display of the nspire but the lower part is zoomed in, so I must move it often. Is there a way to set firebird to a lower resoution to see the whole nspire on screen?
greetings
karl

**Comment by Vogtinator** [comment]
The horizontal/landscape mode was made for that - does that not work for you?

**Comment by Vogtinator** [comment]
Closing, no response.
