### ISSUE TITLE
Can't save snapshots with some characters 

### ISSUE THREAD

**Issue by vb-03** [nspire-emus/firebird#153]
If the app is running inside a folder with º (that's the one i noticed, maybe there are others characters), gives an error when saving snapshot, screenshots in the link 
[Windows 10, 1809]
![368](https://user-images.githubusercontent.com/47537857/52598046-9e50d300-2e4c-11e9-999c-3104fb09e92b.png)
![369](https://user-images.githubusercontent.com/47537857/52598047-9e50d300-2e4c-11e9-8193-74fbd74cb056.png)

**Comment by vb-03** [comment]
#134 Looks similar to this

**Comment by Vogtinator** [comment]
Should be fixed with http://jacobly.com/firebird/utf8snapshot/c857c8898625458dffbe6c06cabd1ed8eb69a4f0/firebird-emu.exe.gz - please try.

**Comment by vb-03** [comment]
Yes, everything working now. #134 could be closed too, it seems to be the same issue.

**Comment by vb-03** [comment]
Update: bugging again, this time i don't understand the reason why, will test further.

**Comment by vb-03** [comment]
Yup still not working, probably I was using wrong folder.

**Comment by Vogtinator** [comment]
I just tried it in a windows 10 VM and it works fine.

**Comment by vb-03** [comment]
Ok this version for me just doesn't save snapshots anywhere. Where does it store the temp files? (so I can delete them and try to fix this)

**Comment by Vogtinator** [comment]
There are no temp files. If it saved a snapshot, it did so in the location you specified directly.

**Comment by vb-03** [comment]
So the app is reallly messed up in my pc, it just doesn't save anywhere the snapshots now. I've moved it in different folders, only missing trying it in another disk.

**Comment by Vogtinator** [comment]
Ok, so let's ask for an independent test - @adriweb?

**Comment by vb-03** [comment]
Couldyou try to re-upload it to check if the issue persists?

**Comment by Vogtinator** [comment]
Re-upload what?

**Comment by vb-03** [comment]
The .exe, is it possible that the file could be corrupted in someway?

**Comment by Vogtinator** [comment]
Very unlikely.

**Comment by vb-03** [comment]
Ok so I ran the 1.4 release, used it for a bit, then opened the new .exe and magically started working....
Even the icon in the taskbar that was broken reappeared again!

**Comment by vb-03** [comment]
Also the calculator screen is bigger in this version - nice touch!
