### ISSUE TITLE
Not using full screen on android

### ISSUE THREAD

**Issue by John-Ingram** [nspire-emus/firebird#155]
The Application seems locked to 16:9. Is there a technical reason not to support other aspect ratios? it seems like it would be fairly straightforward to [add support](https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html) for this, and it would be very useful now that we have super wide/long-screen phones.

**Comment by Vogtinator** [comment]
I did the change but can't test it myself, here's an APK:

[firebird.zip](https://github.com/nspire-emus/firebird/files/2914987/firebird.zip)

**Comment by John-Ingram** [comment]
Works Perfectly. Even resumes the emulation where I left off.
