### ISSUE TITLE
Software Crashes every time I open

### ISSUE THREAD

**Issue by StickyChannel92** [nspire-emus/firebird#157]
I'm using a Windows 7 laptop, so when I extract the folder, the instant I open up Firebird it becomes unresponsive and crashes. It keeps doing this every time I try to open up Firebird. I'm trying other versions for Firebird, but the same issue happens on other versions.

How do I open Firebird without making it crash the instant I open it?

**Comment by StickyChannel92** [comment]
OK, thanks. But I tried looking in _Device Manager_, and the laptop I'm using has an _Intel Graphics Media Accelerator_, opened up the properties, and here is what it said:

> This device is working properly.

Is that a graphics driver, or am I talking about something else?

![junk](https://user-images.githubusercontent.com/48563620/54435381-5a2c4900-46fe-11e9-8cc6-c6ed40825040.PNG)

**Comment by lights0123** [comment]
@StickyChannel92 Windows pretty much always says that the device is working properly, even if everything is completely broken.

**Comment by StickyChannel92** [comment]
**@lights0123 who wrote:**
> @StickyChannel92 Windows pretty much always says that the device is working properly, even if everything is completely broken.

OK, Thanks for letting me know.

**Comment by Vogtinator** [comment]
The windows build for v1.5 includes software OpenGL now, so should work fine.
