### ISSUE TITLE
Unwanted debug popup

### ISSUE THREAD

**Issue by nbenm** [nspire-emus/firebird#160]
When I use GDB, every time a breakpoint is reached, the firebird debug internal window is open and has focus. This is really annoying.
I have unchecked all boxes in debugger preferences, but it’s still the same.
What can I do?

**Comment by Vogtinator** [comment]
That's hardcoded, it's meant to focus the internal debugger input when a breakpoint is reached.

I agree that it doesn't make much sense for breakpoints sent to GDB though.

**Comment by nbenm** [comment]
I have tried firebird on Linux today.
It's not the same behaviour.
As debug, console, file transfer and keyboard are in the same window, but in different tabs, it's not annoying.
Furthermore, focus remains on the xterm widow. Even if not perfect, it's much better than on Mac.

**Comment by adriweb** [comment]
The UI, which tabs are shown and where, is customizable. Look in the menus to enable UI edit, then make the changes you want, and disable it. All platforms should have the same GUI features (and almost the same look)

**Comment by nbenm** [comment]
@adriweb I have finally succeeded in putting windows as tabs.
I'm not familiar with using a mouse, a trackpad, and gui.
I feel more comfortable with command line. I'm an old school boy!
Indeed, I now have something similar to what I have with Linux. The debugger tab opens but focus remains on xterm window. For me it's enough. There's no need to change anything.

It's a real pleasure to use the emulator. Having the console output is also a plus.
It's like a real calculator. Even the official simulator doesn't permit using ndless.
Very good job!
