### ISSUE TITLE
Something strange in com.org-firebird.firebird-emu.plist file on Mac

### ISSUE THREAD

**Issue by nbenm** [nspire-emus/firebird#162]
I have taken a look at com.org-firebird.firebird-emu.plist file on my Mac.
The goal was to check if I could save it before changing UI in case this one was broken.
I have found some sensitive data into it. Such as GPS coordinate of my home, list of all usb devices I have connected one day or another. Some directories I have used which are not related to firebird. This seems strange, isn't it?

**Comment by adriweb** [comment]
What's the path of that file for you?
Which firebird version? Which OS version? etc. etc.

I'd need to check if such things are in mine as well, but for now I don't know where they could be from. Not Firebird itself, anyway. Could be Qt (weirdly?), macOS (unlikely?)...

**Comment by nbenm** [comment]
firebird version: 1.4
OS version: Mojave MacOs 10.14.4
qt5 version: 5.12.2 (from homebrew)
Full path: $HOME/Library/Preferences/com.org-firebird.firebird-emu.plist
This file is in binary. You must first convert it to text using:
plutil -convert xml1 $HOME/Library/Preferences/com.org-firebird.firebird-emu.plist
to go back to binary format:
plutil -convert binary1 $HOME/Library/Preferences/com.org-firebird.firebird-emu.plist

**Comment by adriweb** [comment]
Yeah those are all the things the system (and possibly any other 3rd party app you have ?!) manages and sets, nothing we can do about it here ourselves.
I don't know why they end up here, though.

Interestingly, there aren't as many things for CEmu, barely nothing, relatively....
That said it's not managed exactly the same way, we do keep some .ini file with the settings we want.

**Comment by adriweb** [comment]
Closing as we can't really do anything about it apparently and it's not coming from us (plus, we don't share/export/upload your files anyway :P)
Reopen if needed for some reason.
