### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [nspire-emus/firebird#163]
i've downloaded Version '1.4' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all - it just shows "Created by Qt/QMake". 

i guess the *CFBundleVersion* and *CFBundleShortVersionString* entries in your *Info.plist* file are missing.

all apps on macOS are supposed to contain valid version information.

**Comment by adriweb** [comment]
Yeah, I'll fix that for the next release.

**Comment by adriweb** [comment]
Looks like I got trolled by the build again even though I had fixed it locally beforehand.
I'll try to update the release binary soon.

**Comment by core-code** [comment]
awesome!

**Comment by adriweb** [comment]
Version + codesigning issues fixed in the latest release :)

**Comment by core-code** [comment]
i can confirm all is fine now. thanks!

**Comment by core-code** [comment]
while this was fixed in 1.5, it is broken again in 1.6

**Comment by adriweb** [comment]
Maybe something is overriding it then because the .plist file has 1.6 as expected : https://github.com/nspire-emus/firebird/blob/master/Info.plist

**Comment by core-code** [comment]
weird, this is not the Info.plist that ended up in 1.6, it was a barebones thing even with broken bundle-identifier:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>firebird-emu</string>
	<key>CFBundleIconFile</key>
	<string>logo.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.yourcompany.firebird-emu</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.13</string>
	<key>NOTE</key>
	<string>This file was generated by Qt/QMake.</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
</dict>
</plist>
```

**Comment by adriweb** [comment]
Alright, guess we'll have to see why it got completely replaced by a generic one.
