### ISSUE TITLE
upload files in CLI

### ISSUE THREAD

**Issue by nbenm** [nspire-emus/firebird#164]
Hi

Is there a way to upload files in command line?
I'd like to avoid using file explorer (Mac and Linux).
I have tried with gdb:
```
load helloworld.tns
"helloworld.tns" is not an object file: Format de fichier non reconnu
```
I have then tried:
```
gef> load helloworld.elf
Loading section .text, size 0x52f0 lma 0x0
Loading section .got, size 0x40 lma 0x52f0
Loading section .data, size 0x474 lma 0x5330
Start address 0x0, load size 22436
Transfer rate: 104 KB/sec, 158 bytes/write.
gef> compare-sections
Section .text, range 0x0 -- 0x52f0: matched.
Section .got, range 0x52f0 -- 0x5330: matched.
Section .data, range 0x5330 -- 0x57a4: matched.
gef> 
```
Hum, sounds well!
But when I continue, a reboot occurs.

Is there a way to upload a tns file, in or out of gdb in command line?
It takes too long with mouse or trackpad, and needs many clicks.

**Comment by Vogtinator** [comment]
`firebird-send` is meant for that, it requires remote access to the internal debugger.

**Comment by nbenm** [comment]
@Vogtinator these are good news.
Do you have examples?
I have tried locally (not remotely) "ln st /documents/ndless" and "ln s path_to/helloworld.tns"
But nothing happens. When you say firebird-send are talking about "ln s"?

**Comment by Vogtinator** [comment]
I'm talking about `https://github.com/nspire-emus/firebird/blob/master/core/firebird-send`, which does that for you.

**Comment by nbenm** [comment]
Thanks a lot.

It was that: a "ln file" followed by a "ln st dir"
For me it worked only once. But I'm pretty sure it is related to my conf.
I have tried different netcat versions, and frequently it hangs.
I have also tried with telnet, and it's the same.
It connects to port 3334, and then freezes.
But I'm closing the "issue". you answered my question perfectly.

**Comment by Vogtinator** [comment]
`ln c` connects (happens automatically though), `ln st <dir>` sets the target directory and `ln s <file>` sends a file, so `ln file` can't have worked, especially not in that order.

Neither telnet nor netcat freeze, they just wait for input or disconnection.

**Comment by nbenm** [comment]
You are right!
I was wrong when writing here.
Here's my script:
```
nc localhost 3334 << EOT
ln st /documents/ndless
ln s /Users/nb/Dropbox/dev/asm/nspire/S/helloworld/helloworld.tns
EOT
```
With Mac native nc, It returns without doing anything. In the console I see 
```
Remote debug: connected.
Remote debug: connection closed.
```
But the file isn't sent.

With homebrew netcat it hangs and in the console I see only:
`Remote debug: connected.
`
but once, I saw the file transferred. Only once.
I'm going to try on Linux.

**Comment by Vogtinator** [comment]
That's because `/documents/ndless` is not a valid folder - try `ln st /ndless` instead.

**Comment by nbenm** [comment]
I have tried on Debian sid: it also connects and then hangs.
I have tried on Mac with `ln st /ndless` and it hangs also.
What I can't understand is why it worked once. I remember that perfectly. The file was present in the calc file browser and not in the transfert file one.

**Comment by nbenm** [comment]
In fact when I say it hangs, it hangs on output only!
It does the job but nothing is transferred.
I say that because I have adde a "h" at the end, and I see the result of help command in the console.
This is exactly the same when I type the commands locally in the debugger.
So, the debugger receives the commands but does nothing.

**Comment by Vogtinator** [comment]
Doing drag and drop file transfers works fine though?
If so, this needs a bit more debugging.

**Comment by nbenm** [comment]
Yes drag and drop works fine.
That's what I wanted to avoid...
I understand it needs more debugging.
If there are some tests I can do, please let me know.
Thanks again

**Comment by Vogtinator** [comment]
If you start firebird, get into the OS, enter the internal debugger and then run `ln c`, `c`, does it connect successfully? It should say so in the status bar and the USB connection button.

**Comment by nbenm** [comment]
When I type `ln c` I have the message **usblink connected** and the green tick appears, then it exits the debugger.
If I type only `c`, nothing happens.

**Comment by Vogtinator** [comment]
Ok, that's fine. If you then do `ln st ndless`, `ln s file`, what happens?

**Comment by nbenm** [comment]
Bingo! It works fine this way.
The only remaining problem is why nc doesn't exit. But this is not important. A ctrl-C and it's ok.
Thanks for all

**Comment by Vogtinator** [comment]
That's because you need to add either `-q0` or `-N`. Does firebird-send not work?

**Comment by nbenm** [comment]
It works fine now on Linux, Mac with original netcat, and Mac with Homebrew netcat.
I was trying to create a new branch and pull request changes.
But it may be simpler to tell these changes here:

Changing
`nc -N 2>&1 | grep -q "invalid option" || NC_ARGS=-N
`
to
```
nc -N 2>&1 | grep -q "invalid option" || NC_ARGS=-N
nc -q 0 2>&1 | grep -q "option" || NC_ARGS="-q 0"
```
solves the netcat issue. Second line added.

netcat options are completely different depending on version. I have tried three of them. Not the one that uses **-N**

**Comment by nbenm** [comment]
In fact it's `-N`, `-q 0` or **nothing**

**Comment by Vogtinator** [comment]
According to the `nc` man page, `-q 0` implies `-N`, so I'll just change it.

**Comment by nbenm** [comment]
Ok. But I just found a version which uses `-c`
```
nc -h
GNU netcat 0.7.1, a rewrite of the famous networking tool.
Basic usages:
connect to somewhere:  nc [options] hostname port [port] ...
listen for inbound:    nc -l -p port [options] [hostname] [port] ...
tunnel to somewhere:   nc -L hostname:port -p port [options]

Mandatory arguments to long options are mandatory for short options too.
Options:
  -c, --close                close connection on EOF from stdin
  -e, --exec=PROGRAM         program to exec after connect
  -g, --gateway=LIST         source-routing hop point[s], up to 8
  -G, --pointer=NUM          source-routing pointer: 4, 8, 12, ...
  -h, --help                 display this help and exit
  -i, --interval=SECS        delay interval for lines sent, ports scanned
  -l, --listen               listen mode, for inbound connects
  -L, --tunnel=ADDRESS:PORT  forward local port to remote address
  -n, --dont-resolve         numeric-only IP addresses, no DNS
  -o, --output=FILE          output hexdump traffic to FILE (implies -x)
  -p, --local-port=NUM       local port number
  -r, --randomize            randomize local and remote ports
  -s, --source=ADDRESS       local source address (ip or hostname)
  -t, --tcp                  TCP mode (default)
  -T, --telnet               answer using TELNET negotiation
  -u, --udp                  UDP mode
  -v, --verbose              verbose (use twice to be more verbose)
  -V, --version              output version information and exit
  -x, --hexdump              hexdump incoming and outgoing traffic
  -w, --wait=SECS            timeout for connects and final net reads
  -z, --zero                 zero-I/O mode (used for scanning)

Remote port number can also be specified as range.  Example: '1-1024'
```
I hope that's the last one.

**Comment by Vogtinator** [comment]
I pushed a commit which works both with OpenBSD and GNU netcat.
