### ISSUE TITLE
Add autosave feature 

### ISSUE THREAD

**Issue by Candunc** [nspire-emus/firebird#17]
The NAND for the calculator seems to only be loaded in RAM, and the actual data never gets written unless you explicitly save the file. Perhaps in the settings there should be a option for saving the NAND the moment it is modified, for example when saving a document.

**Comment by Vogtinator** [comment]
Hm, what about a timed autosave, like most office programs do?
The interval can be configured and completely disabled, of course.
It would also be much easier to implement in this way.

**Comment by adriweb** [comment]
Timed autosave looks good to me, but not enabled by default. When I try stuff, it's mostly temporarily and I'd hate to see, the next time I run the emu, that my clean/ready flash image isn't clean anymore because I forgot to disable the autosave



Thanks,
Adrien Bertrand

**Comment by Vogtinator** [comment]
I guess the recently added autosuspend/autoresume are even better than autosave.
