### ISSUE TITLE
exec from debugger causes a data abort

### ISSUE THREAD

**Issue by lights0123** [nspire-emus/firebird#170]
Using CX CAS 4.5.0, using exec to execute a file within the debugger by typing `exec /ndless/executable.tns` gives the following error: `Warning (10433890): Data abort: address=fffffffc status=05 instruction at 10433890`. Then, after typing `c` to resume, the calculator resets, and `Warning (100e4e44): Undefined instruction at 100e4e44` appears during boot, and the OS displays "System Error". Resetting then allows it to reboot correctly.

**Comment by Vogtinator** [comment]
Yes, that's unfortunately a known issue. The program can only be executed while the file browser thread is active in the OS, but currently it just executes directly. What would need to be done is dispatching the execution to a hook inside the right thread.

Closing here as it's a bug in Ndless.
