### ISSUE TITLE
is the thumb instruction set supported?

### ISSUE THREAD

**Issue by grubsteak** [nspire-emus/firebird#175]
Every time I try to call a function with `__attribute__ ((target ("thumb")))` applied (it's not `main()` fyi), the emulator breaks into a debugger.
```
Warning (12164b88): Data abort: address=fffff2fb status=05 instruction at 12164b88
Warning (12218bb4): Undefined instruction at 12218bb4
Warning (0000029a): Data abort: address=60035140 status=05 instruction at 0000029a
```
I am running Ndless 4.5 on OS 4.5.0
Is thumb not supported or does the problem sit between the driver's seat and the steering wheel? :grin:

**Comment by Vogtinator** [comment]
Yes, thumb is supported. In fact, the OS itself has some thumb code in some places (for whatever reason...). You can use the `ut` command in the debugger to force thumb disassembly.

**Comment by grubsteak** [comment]
Sorry for the late reply, but I still cannot get this to work. I have searched and I cannot find any examples that use thumb. I've made sure to use ` -mthumb-interwork` and `-mthumb` and also told the compiler to generate my `main()` method as non-thumb.

Here is my configuration: [(thumb-test.zip)](https://github.com/nspire-emus/firebird/files/3721902/thumb-test). To run it, open `firebird-emu`, install Ndless 4.5, and do `make clean send`. Whenever I execute it, the emulator just hangs. Can you explain what I am doing wrong? 

---
Here is the stack trace and register dump  when I manually enter the debugger after it hangs.
```ocaml
Frame     PrvFrame Self     Return   Start
00000000: invalid address
```
```j
 r0=13fda7fa  r1=00000084  r2=13fda800  r3=12967a5c  r4=8a8a6b40  r5=12967b08
 r6=11514d68  r7=11514d70  r8=00000001  r9=00000000 r10=00000000 r11=00000000
r12=00000ba5  sp=1800d488  lr=12960a2c  pc=00000bca
cpsr=200000b3 (N=0 Z=0 C=1 V=0 Q=0 IRQ=off FIQ=on  T=1 Mode=svc) spsr=40000093
```

Ndless Version: 4.5
OS Version: 4.5.0
Hardware: CX (HW A)

---

# File listing for thumb-test.zip

test.c
---
```c
#include <libndls.h>
#include <stdio.h>

__attribute__((target("thumb")))
void hello_from_thumb() {
	printf("Hello from thumb!\n");
}

__attribute__((target("arm")))
int main(int argc, char* argv[]) {
	hello_from_thumb();
	return 0;
}
```
Makefile
---
```makefile
GCC = nspire-gcc
CFLAGS = -mthumb-interwork -mthumb
#-fpic
#-mcallee-super-interworking

default: test.tns
.PHONY: default clean

test.elf: test.c
	$(GCC) $(CFLAGS) $< -o $@

test.tns: test.elf
	genzehn --input $< --output $@ --include-bss

send: test.tns
	firebird-send -p 3334 test.tns

clean:
	rm -f test.elf test.tns
```

**Comment by Vogtinator** [comment]
It's actually a bug in binutils: It turns out that even with the `--emit-relocs` parameter passed to `arm-none-eabi-ld`, it does not emit relocations for the arm2thumb stubs, so it just jumped to nowhere in thumb mode.

Workaround is to pass the `--pic-veneer` option as well.

Can you confirm that it works if you add `--pic-veneer` to the arguments to ld in `ndless-sdk/bin/arm-none-eabi-ld.gold`?

**Comment by grubsteak** [comment]
Both adding `-Xlinker --pic-veneer` to the compiler options or adding `--pic-veener` to `ndless-sdk/bin/arm-none-eabi-ld.gold` seems to do the trick. Thanks!
