### ISSUE TITLE
MacOS emulation fails to start after changing name of flash image

### ISSUE THREAD

**Issue by dpleshkov** [nspire-emus/firebird#176]
I've installed firebird and have gotten it to create and boot a flash image. I closed the app, changed the name of the flash image it created, launched it again. I get the "failed to start emulation" message, and no menu dialogs show up in the app to somehow change configuration.

Re-installing app does nothing, deleting `~/Library/Caches/org.firebird` also does nothing. Couldn't find anything in `~/Library/Application\ Support` related to firebird.

Is there a way I can reset all previous settings to default so I get to re-initialize firebird again?

**Comment by dpleshkov** [comment]
Fixed by deleting `~/Library/Preferences/com.org-firebird.firebird-emu.plist`

**Comment by Vogtinator** [comment]
> no menu dialogs show up in the app to somehow change configuration.

Have you tried opening the configuration dialog manually?
