### ISSUE TITLE
Can’t get started on iOS

### ISSUE THREAD

**Issue by Tarang74** [nspire-emus/firebird#179]
So I just got it on iOS, can someone please explain what I should do next?

Is the boot file the file from the tnspire website? Or is this the flash file? Then what is the other file?

**Comment by Vogtinator** [comment]
You need to create the flash image yourself on a PC, that's not possible on iOS (yet).

See https://github.com/nspire-emus/firebird/wiki/Installing-firebird#ios

**Comment by fakefakeman** [comment]
I also can't start simulation .
hardware:
PC: win10
Ipad: ios 10.2 jailbreaked
The flash created on PC worked.
but after load boot1 & flash on ipad and press the bomb icon，
just shows couldn't start the simulation, and I can't find any clue.
