### ISSUE TITLE
Files automatically get put in ndless folder

### ISSUE THREAD

**Issue by Candunc** [nspire-emus/firebird#18]
When I first attempted to transfer files, they would be sent however I never saw the notifications. I looked in the serial monitor tab, where it reveals that it couldn't move a file from /tmp/ to /documents/ndless/

Creating the folder ndless solved that issue, and files appeared on my calculator. However, it appears whenever you drag files into the File Transfer tab, they all go into the ndless folder, no matter what folder is selected in the tab. 

![folder](https://cloud.githubusercontent.com/assets/549161/9997349/f64aea58-6048-11e5-86fc-e28976e78227.png)

**Comment by Vogtinator** [comment]
Drag and Drop from/to the file explorer is not implemented yet, only file listing is.
I'm currently working on that. The folder you send dropped files to can be changed under Settings->File transfer.

**Comment by Vogtinator** [comment]
Dropping files into explorer is now implemented.
