### ISSUE TITLE
""Firebird Emu" Needs to Be Updated" pop-up when starting the app. 

### ISSUE THREAD

**Issue by papshed** [nspire-emus/firebird#181]
I installed the 64 bit version of the latest release on my iPhone X running the checkra1n jailbreak on iOS 13.2.2.

I am unable to start the app, triggers "The developper of this app needs to update it to work with iOS 13.2.2."

Did I do something wrong?

![IMG_59AD3EAE9B5F-1](https://user-images.githubusercontent.com/28029858/70555623-6dfdc200-1b4d-11ea-98d4-88e9ee81a293.jpeg)

**Comment by adriweb** [comment]
Alright, I actually hadn't tried it in a while. And considering iOS 13.3 is soon going to be released...

**Comment by papshed** [comment]
Oh really? ^^ That's amazing! I love the fact that I don't have to have my TI calculator with me all the time, this app is a delight. 

Do you happen to know how soon? I haven't managed to find info about an iOS 13 release!

**Comment by papshed** [comment]
Alright, marking closed. Hand't realized that AppSync Unified was not running and that the app could therefore not properly install. Just realized you're one of the legends that developed this marvel. Thank you so much for this!

**Comment by papshed** [comment]
For anyone experiencing this issue:

1. Install AppSync Unified
2. Install the 64 bit .IPA file through Filza by pressing the install button.

That's it really.
