### ISSUE TITLE
Is it possible to compile this to run natively on a chip?

### ISSUE THREAD

**Issue by CiriousJoker** [nspire-emus/firebird#182]
Say, I have the Esp32 board with a 240mhz processor on it. Can I run the nspire os "natively" somehow?

**Comment by CiriousJoker** [comment]
The chip is Arduino compatible, which means I can compile c++ to run on it, but I also have only 500kib of ram. Does this emulator make use of any complex OS libraries or is it fairly low level to the point where I can port it by adding proxies for the necessary display/io functions?

**Comment by CiriousJoker** [comment]
Nevermind, I guess there's no way unless I pretty much rewrite the whole thing for the new architecture :(

**Comment by Vogtinator** [comment]
> The chip is Arduino compatible, which means I can compile c++ to run on it, but I also have only 500kib of ram.

The emulated hardware has 64MiB RAM, so Firebird needs at the very least ~70MiB of RAM for the bare interpreter and ~256MiB for JIT.

> Does this emulator make use of any complex OS libraries or is it fairly low level to the point where I can port it by adding proxies for the necessary display/io functions?

The headless version is plain C++ with some use of OS specific functions.
