### ISSUE TITLE
Can't start simulation on ios 10.2

### ISSUE THREAD

**Issue by fakefakeman** [nspire-emus/firebird#187]
hardware:
PC: win10
Ipad pro A1673 : ios 10.2 jailbreaked 
Following steps:  
1. Create a flash by setting boot1 ,boot 2 and os.
 The flash created on PC worked. (but can't save the snapshot )

2. Install  newest ipa for 64 bit  on ipad.
Load boot1 & flash (created on PC )  and press the bomb icon.
Just shows "couldn't start the simulation", and there's no clue why it failed.

**Comment by fakefakeman** [comment]
I installed apk version and load the same boot1 & flash on an andriod simulator, 
and it worked.
So my conclusion is:  
There's no problem with the boot and flash. 
The problem is ios version itself .

**Comment by adriweb** [comment]
I would suggest trying the latest master, and on a more recent iOS. In fact, the next release probably won't even be able to support anything lower than iOS 12 (because we're using Qt 5.14 - so if you build it yourself, make sure to get an older Qt)

Thank you,
Adrien Bertrand

**Comment by fakefakeman** [comment]
Thanks for the advice.
I also tried using the windows ver1.1 to produce the flash and loaded with ios ver 1.1 (released on Nov 2016) ⇒But also didn't work.
 Maybe I'll try it on other device instead.

**Comment by adriweb** [comment]
Could you try with the latest release?

**Comment by adriweb** [comment]
Try the latest release ; reopen if needed.
