### ISSUE TITLE
More suitable license?

### ISSUE THREAD

**Issue by Vogtinator** [nspire-emus/firebird#19]
I received some comments about the license, but such a switch would need acknowledgement from all contributors... Any suggestion for a new license?

**Comment by adriweb** [comment]
MIT or LGPL would be fine for me, I guess, if it's any better.

**Comment by Vogtinator** [comment]
Not for me, that way firebird could be converted into a shard library and used in commercial and closed source apps.

**Comment by adriweb** [comment]
Then whoever doesn't like the current license should also propose another that's compatible with this idea (which I agree to)

**Comment by Vogtinator** [comment]
Legimet proposed the GPLv3 some time ago and it might be the best choice

**Comment by adriweb** [comment]
I'm OK with GPLv3.

**Comment by Legimet** [comment]
I would also suggest getting permission from Goplat and any other previous 
contributors to nspire_emu.

**Comment by debrouxl** [comment]
Not that I contributed much brand-new code, but GPLv3, I suppose.
