### ISSUE TITLE
XModem Hangs On File Sending

### ISSUE THREAD

**Issue by StevenC21** [nspire-emus/firebird#192]
I am running Windows 10 with a dumped CX CAS CR4 v4.4 OS. Firebird happily loads up the operating system and it appears to work normally. However, when I attempt to send a file over XModem, it never actually sends. The bottom left of the Firebird UI gives the right filepath, filename, etc. So it clearly thinks it is sending the file...

Furthermore, the Debugger has no output whatsoever during this time. The "usblink" *_is_ connected, and there doesn't appear to be an error there. It has the green checkmark which I would think signifies success. 

To be clear, from the time I initialize the Firebird program, to the time I close it, the debugger has exactly nothing in its log. XModem just never sends the file over. I'm just trying to send over the ndless 4.4 installer tns file (and yes, it does have the .tns extension). The file transfer bar also never moves from 0%.

Strangely, the menu in the configuration folder will allow me to transfer the files. So I have a workaround, but this behavior is still strange to me.

I don't know if it helps, but here is a full copy-paste from the Serial Monitor:

```
File system ready.





rebootGenerateFilename(): /logs/1A2B_reboot_1.txt file does not exist
autodim_power_callback: Stop dim Timer. flags(0x4)
------------------ Module is Gone!! 
TouchPad Firmware Revision : 01060000

Created Execution Context
<TI_PCL_Init2> SetSystem Settings   -->
<TI_PCL_Init2> TI_RM_LoadAllStrings -->
<TI_PCL_Init2> TI_UI_IME_Init -->
<TI_PCL_Init2> RegisterC1Widgets -->
<TI_PCL_Init2> TI_GOIO_InitializeGoIO -->
<TI_PCL_Init2> TI_AM_Initialize -->
Product   : 16 (defined in os/inc/deviceinfo.h)
Platform  : 2 (defined in documentmanager/inc/hal.h)
Version   : 3.6.0.337 CE 
Build Date: 2013-5-10
TI_PM_DIM_settime: Dim set to 90.
Unknown LCD(0x00 0x00 0x00).
RET - Echo UDP: TI_Echo_UDP_Init called +++
RET - ECHO UDP: EchoUDPListenerThread. Inside Thread +++

START TI_LOCALE_initializeDefaultLocale.....
DEFAULT LOCALE is en.....
Found a Match: en(MD) and en
END TI_LOCALE_initializeDefaultLocale.....
autodim_power_callback: Stop dim Timer. flags(0x4)
autodim_power_callback: Stop dim Timer. flags(0x1)
I_PM_DIM_disable: Stop dim Timer. 
TI_PM_DIM_disable: Stop dim Timer. 

```

Hope I gave useful information :P

**Comment by Vogtinator** [comment]
That sounds like you're trying to send a `.tns` or OS file over XModem - that won't work. XModem is only used for transferring the bootloader during the initial installation, the OS doesn't support that otherwise.
