### ISSUE TITLE
Connection refused on port 3333 or 3334

### ISSUE THREAD

**Issue by AdelCraftZ** [nspire-emus/firebird#193]
When I try to use `GDB` on port `3333` or `firebird-send` on port `3334`, the connection is refused. I am on Arch Linux. I first thought that my `loopback (lo)` interface was down or badly configured, so I tried listening on the port `3333` and `3334` with netcat while `firebird-emu` was running, and it worked. That means that `firebird-emu` is NOT listening on port `3333` or `3334`, otherwise it wouldn't have been able to listen on these ports.

Any ideas? Thanks.

**Comment by CodeWriterPro** [comment]
Nevermind, Now it works.

**Comment by Vogtinator** [comment]
Firebird binds to 127.0.0.1 by default, while netcat uses 0.0.0.0, so all interfaces and addresses.
If binding fails, there is an error message in the "Debuger" panel. If you can reproduce the issue, does such a message appear?

**Comment by CodeWriterPro** [comment]
Again, it don't works. I just rebooted my computer since last time it worked and there's no message in the debugger. I'm sorry that i cant provide you more info.

**Comment by CodeWriterPro** [comment]
It seems to be a problem with my computer. I've just turned the `loopback (lo)` interface down and up again, an now it works.

**Comment by CodeWriterPro** [comment]
I've been able to reproduce the issue.:

1. I have to start the emulator. At this point, the connection is still refused.
2. When the emulator is still running, I have to bring down and up again my `loopback lo` interface (I use `ifconfig` for that).
3. I have to restart the emulator by clicking `Emulation > Restart` and NOT by closing it's process and opening it again.
4. Now, I can connect with `GDB`, `firebird-send `or `netcat`.

**Comment by AdelCraftZ** [comment]
Bug seems to be fixed in version the new version (1.5). I'm closing this issue.
