### ISSUE TITLE
CXII branch binaries

### ISSUE THREAD

**Issue by tvlad1234** [nspire-emus/firebird#194]
I see that there is initial support for CXII emulation. Is it possible for me to download some precompiled binaries? I don't have the knowledge to install the whole development framework and tools.

**Comment by adriweb** [comment]
Technically there can be binaries but it's not like it would be useful now, since the way to dump a CX II isn't public yet.

**Comment by Vogtinator** [comment]
There are binaries actually: http://jacobly.com/firebird/cxII-clean/latest/

As @adriweb wrote though, probably not of much use yet.

**Comment by Atrate** [comment]
Is Firebird 1.5 supposed to be able to emulate CXII now that it's possible to dump it?
