### ISSUE TITLE
File Transfer On Android

### ISSUE THREAD

**Issue by penzovakid** [nspire-emus/firebird#195]
How To Transfer .tns file on FireBird Emu 
~ Android ~ 
Help

**Comment by Vogtinator** [comment]
In the configuration pane, select the "File transfer" tab.

**Comment by penzovakid** [comment]
Please Send Vidio Tutorial

**Comment by adriweb** [comment]
No need for a video...
On the emu: swipe left, tap on "Configuration", at the top tap on "File Transfer", then tap on the "Send a file" button.
