### ISSUE TITLE
Build fails on little endian ppc64le, Fedora Rawhide

### ISSUE THREAD

**Issue by TC01** [nspire-emus/firebird#196]
Hi,

I tried to build firebird-emu on Fedora Rawhide (Fedora 33), to update the package in RPM Fusion. The build on ppc64le [seems to have failed](http://koji.rpmfusion.org/kojifiles/work/tasks/3349/403349/build.log) for somewhat mysterious reasons:

```
BUILDSTDERR: Project ERROR: No JIT found for arch power64
```

It works just fine on other little-endian architectures (most notably, x86_64). I checked the [OBS](https://software.opensuse.org/download.html?project=home%3AVogtinator%3Afirebird-emu&package=firebird-emu&locale=en) repo to see if this was a known issue and I noticed that there's no 1.5 build in ppc64le there either. In any case, I thought I'd file a bug (and switch off ppc64le, at least for now).

**Comment by adriweb** [comment]
Well that's correct. The target archs for JIT are only x86, x86_64, arm, and arm64. If you want to build for another arch, disable JIT in the build options (edit TRANSLATION_ENABLED). Or implement hitting for said arch haha

**Comment by Vogtinator** [comment]
With https://github.com/nspire-emus/firebird/pull/197 you can pass `TRANSLATION_ENABLED=false` to qmake. Better option is probably to have the default depend on the architecture though.

**Comment by Vogtinator** [comment]
> Better option is probably to have the default depend on the architecture though.

I updated #197 to use an `auto` value for that by default.

**Comment by Vogtinator** [comment]
#197 got merged, so this is fixed in master.
