### ISSUE TITLE
Where can I download these rom files

### ISSUE THREAD

**Issue by potatomatos** [nspire-emus/firebird#198]
Where can I download these files:
palmos40-en-m500.rom: f50e4d5e4d98dc831f2c34a9107651eb (MD5)
palmos41-en-m515.rom: 83cb1d1c76e568b916dc2e7c0bf669f6 (MD5)
palmos52-en-t3.rom: de46ec84d9aabf655eabdf9b00a3845d (MD5)
bootloader-dbvz.rom: 9da101cd2317830649a31f8fa46debec (MD5)

Don't know GitHub very well

**Comment by Vogtinator** [comment]
That does not seem to be related to Firebird.
