### ISSUE TITLE
Keypad not visible in portrait after rotating phone

### ISSUE THREAD

**Issue by CodingKoopa** [nspire-emus/firebird#199]
When I rotate my phone (sometimes by accident) to where it switches from portrait to landscape, Firebird changes the screen layout to accommodate this, but when I change it back to portrait, the keypad is no longer visible. The full size screenshots stretched out this post pretty badly, so I've put them in [this](https://imgur.com/a/D5N6gHz) Imgur album. I'm able to reproduce this issue on Firebird 1.5, but not 1.4. I'm using a Samsung Galaxy S10e. Thanks :)

**Comment by Vogtinator** [comment]
I see this issue as well, but also on 1.4 for some reason. I don't know why exactly, but the application of the `tabletMode` state followed by resetting to the default portrait state in `MobileUIFront.qml` confuses the layout.

**Comment by Jo900** [comment]
> 
> 
> I see this issue as well, but also on 1.4 for some reason. I don't know why exactly, but the application of the `tabletMode` state followed by resetting to the default portrait state in `MobileUIFront.qml` confuses the layout.

can you build the updated 1.5 apk without this bug ? thanks

**Comment by Vogtinator** [comment]
Sure: https://owncloud.ritter-vogt.de/index.php/s/xsixrmumNxKXWSK
The file is too big for github...

**Comment by Jo900** [comment]
thanks :)

**Comment by CodingKoopa** [comment]
Thanks :)
