### ISSUE TITLE
Impossible to return windows after closing all of them

### ISSUE THREAD

**Issue by kenzierocks** [nspire-emus/firebird#20]
I closed 1 window, and discovered that I could right-click to retrieve. Being the curious person I am, I closed the rest. Now I can't get them back! Even the prefs I discovered had no effect. How do I get some of these windows back?

**Comment by Vogtinator** [comment]
Right click on the menu bar.

**Comment by kenzierocks** [comment]
Which menu bar, none of them seem to have anything:
![img](https://i.imgur.com/T1PzQDn.png)

**Comment by Vogtinator** [comment]
Oh, you're on mac. I guess you're using an older version where the fix wasn't implemented, so closing the last dock was possible. You have to delete your settings (I don't know where they are stored on mac) and update firebird.

**Comment by adriweb** [comment]
Somewhere in `~/Library/Application Support/` and/or
`~/Library/Preferences/` IIRC.

Thank you,
Adrien Bertrand

2015-10-02 2:47 GMT-04:00 Fabian Vogt <notifications@github.com>:

**Comment by kenzierocks** [comment]
Okay, I seem to have them back in tabs mode now. I would like to suggest the addition of a menu for this anyways.

**Comment by adriweb** [comment]
A menu item would probably be useful, but on the latest versions you cannot delete all the tabs anymore, so that's "fixed" anyway.
