### ISSUE TITLE
Is there a tutorial how to setup ti inspire on android? 

### ISSUE THREAD

**Issue by karasjoh000** [nspire-emus/firebird#200]
I get an error of no flash/boot when trying to start on android. Are there any tutorials for this?

**Comment by Vogtinator** [comment]
Yes: https://github.com/nspire-emus/firebird/wiki/Installing-firebird

**Comment by karasjoh000** [comment]
where can the flash be found?

**Comment by Vogtinator** [comment]
https://github.com/nspire-emus/firebird/wiki/First-Time-Setup
