### ISSUE TITLE
Where are the files boot, flash and snapshot??

### ISSUE THREAD

**Issue by tikalow2305** [nspire-emus/firebird#205]
I had the previous version but I updated to android 10 and now it doesn't start me. I downloaded the latest version and in the boot, flash and snapshoot files I put those of the previous version and it does not load, where do I find the latest files? Thx

**Comment by Vogtinator** [comment]
Which version did you have previously? Do you still have the files mentioned in the configuration or is everything empty?

**Comment by tikalow2305** [comment]
> ¿Qué versión tenías anteriormente? ¿Todavía tiene los archivos mencionados en la configuración o está todo vacío?



> Which version did you have previously? Do you still have the files mentioned in the configuration or is everything empty?

it had version 1.3. I try to use the boot, flash and snapshot files of 1.3 in version 1.5 but it doesn't open. Are there files for this latest version?

**Comment by Vogtinator** [comment]
Version 1.5 can't read snapshot files created by 1.3 and vice versa, so resuming won't work.
You can simply do a full "Restart" though and create a new snapshot.

Boot1 and Flash files are still compatible, so just choose the ones you used with 1.3 again.

**Comment by tikalow2305** [comment]
> Version 1.5 can't read snapshot files created by 1.3 and vice versa, so resuming won't work.
> You can simply do a full "Restart" though and create a new snapshot.
> 
> Boot1 and Flash files are still compatible, so just choose the ones you used with 1.3 again.

it closes me at startup. Where can I download the flash, boot1 and snapshot files again? i have android 10

**Comment by adriweb** [comment]
You don't "download" them, you create them from the PC version: https://github.com/nspire-emus/firebird/wiki/First-Time-Setup

**Comment by tikalow2305** [comment]
> You don't "download" them, you create them from the PC version: https://github.com/nspire-emus/firebird/wiki/First-Time-Setu

> You don't "download" them, you create them from the PC version: https://github.com/nspire-emus/firebird/wiki/First-Time-Setup

So how would I go about running it? I need for my classes at the university

**Comment by adriweb** [comment]
Well you follow the instructions :)
Someone wrote a tutorial here for Android: https://www.intereseducation.com/resources/how-to-emulate-ti-nspire-cx-cas-touchpad-on-android-ios-with-firebird/

**Comment by Tsun-hung** [comment]
> Well you follow the instructions :)
> Someone wrote a tutorial here for Android: https://www.intereseducation.com/resources/how-to-emulate-ti-nspire-cx-cas-touchpad-on-android-ios-with-firebird/

@adriweb  Hi，are there any  available files for TI-nspire CX II CAS?

**Comment by debrouxl** [comment]
Nope.

**Comment by JoshuaB-L** [comment]
@tikalow2305 You can download them here at the bottom of the page: https://tinspiredownald.wordpress.com/2018/02/04/the-journey-begins/

**Comment by Vogtinator** [comment]
Sorry, even linking to pages which host that kind of content might cause issues. I removed the link.
