### ISSUE TITLE
Is there a key mapping for desktop's key-board?

### ISSUE THREAD

**Issue by JeffLeeBYD** [nspire-emus/firebird#208]
I wander if there's a instruction on how to use computer key-board to control the calculator. I have explored some key mapping, but I still don't konw how to type "+" with only my key-board, but not the virtual touchpad.

**Comment by Vogtinator** [comment]
For plus, there are three options: https://github.com/nspire-emus/firebird/blob/57dfbbec502378a76b66100f546a5809d614cc0b/qtkeypadbridge.cpp#L146-L148

So you can either use the numpad plus, Alt+Equal or Alt+Plus. I tested that with the `us` layout here and AltGr+Shift+Plus works.

**Comment by Vogtinator** [comment]
Actually, there's an even simpler method: Shift, then Shift+Plus. The first shift makes the OS ignore the second one, which is needed to turn the `=` into a `+`.

**Comment by JeffLeeBYD** [comment]
Thanks!
