### ISSUE TITLE
file transfer on android with different UI

### ISSUE THREAD

**Issue by JeffLeeBYD** [nspire-emus/firebird#209]
When I tap on the file teansfer on phone (16:9 screen), the botton of "send a file" is right there. However, when I try on my tablet (16:10 screen) there's no botton.

**Comment by Vogtinator** [comment]
Can you share a screenshot?

**Comment by JeffLeeBYD** [comment]
![Screenshot_20200815-231506 1](https://user-images.githubusercontent.com/68489908/90408743-d76da180-e0da-11ea-99a2-18e5aff87fde.png)

![12](https://user-images.githubusercontent.com/68489908/90409306-945ffe00-e0db-11ea-8110-cfdb7ba1c5c0.jpg)

**Comment by JeffLeeBYD** [comment]
When I tap the word "file", it works. Thankyou.
