### ISSUE TITLE
Minimal Calculator View

### ISSUE THREAD

**Issue by Candunc** [nspire-emus/firebird#21]
I am a fan of all the tabs that are provided, as they are pretty useful. However, would it be possible to make an interface similar to the "Wabbitemu" emulator for the TI-84? I'm asking simply as it would be a better interface for making tutorial videos, or for example, teaching in a classroom with the calculator projected onto a touchscreen.

For example, this is what Wabbitemu's window can look like:

![](https://lh3.ggpht.com/KDgWiGq53cN__38aq61OPFif5RLsnLESCqBL-8gVYFuqJeD4720IoxUQqf28C_WNfw=h900)

**Comment by Vogtinator** [comment]
The mobile UI comes very close to that, but a recompile is needed for that.
I'll see whether it makes sense to have builds with MOBILE_UI enabled on desktop as well.
