### ISSUE TITLE
Suggestion: Upload this to the play store to allow Chrome OS users to use it

### ISSUE THREAD

**Issue by lmore377** [nspire-emus/firebird#210]
Uploading the app to the play store would make it easy to push out updates and would it make it available to almost all of the Chrome OS devices out there for people who can't/don't want to fumble with Linux or enable developer mode to install it. I tested it on my Chromebook and it runs good enough, but because of the arm to x86 translation that the Chromebook has to do it can get a bit slow at times (building for x86 should fix that and you can test it without a Chromebook by installing [Android x86](https://www.android-x86.org/) on another PC or in a virtual machine) and not having the ability to resize the window makes it a bit cumbersome to use sometimes. I think if it was added to the play store, it would need a notice at launch saying that the user needs to provide the required files, maybe offer a tutorial, and a way to create the flash file without a PC or Mac.

**Comment by Vogtinator** [comment]
> Uploading the app to the play store would make it easy to push out updates and would it make it available to almost all of the Chrome OS devices out there for people who can't/don't want to fumble with Linux or enable developer mode to install it.

I don't really want to deal with the mess which is the Play Store. It'll probably end up getting removed for some reason anyway.
This is GPLv3 software, so you could build and publish it yourself if you want to. You'd just have to write "Firebird Emu (Community build)" or something like that.

> I tested it on my Chromebook and it runs good enough, but because of the arm to x86 translation that the Chromebook has to do it can get a bit slow at times (building for x86 should fix that and you can test it without a Chromebook by installing Android x86 on another PC or in a virtual machine) and not having the ability to resize the window makes it a bit cumbersome to use sometimes.

Firebird can be built for x86 Android, but only without JIT currently, which is why it's not part of the released apk.
AFAIK Chrome OS can also run Linux applications, so you could also do it that way?

> I think if it was added to the play store, it would need a notice at launch saying that the user needs to provide the required files, maybe offer a tutorial,

There is a message, but it might not be visible enough and it also doesn't have a link to a tutorial.

> and a way to create the flash file without a PC or Mac.

Yeah, that's definitely planned.

**Comment by Vogtinator** [comment]
#211 implements proper x86_64 support for Android, please try: https://github.com/nspire-emus/firebird/pull/211#issuecomment-683409967

**Comment by DremOSDeveloperTeam** [comment]
Do note that you can always install APKs on Chromebooks by using Android's file browser or downloading a package installer from the Play Store. I forget if it's possible to sideload APKs from the Chrome OS file browser, though.

**Comment by PicoPlanetDev** [comment]
Sorry to dig up this old thread but I have a bit of new information on this. Google took away support for installing APKs on ARC++ Android containers, so if you have an older Chromebook, sideloading may no longer work. If you have a newer Chromebook with Android 11 and ARCVM it is still an available option by installing from the Chrome OS Files app.

I already have a Google Play developer account if anyone still wants it uploaded to the Play Store to use more easily on a Chromebook. However, I have found that the Linux version is not terribly difficult to use on Chrome OS.
