### ISSUE TITLE
v1.4 Configures with CX on Android Oreo, CX-CAS doesn't load

### ISSUE THREAD

**Issue by Madeirio** [nspire-emus/firebird#216]
Have several issues, but first:

CX (CX-4.3.0.702) will load and run, but requires a full boot cycle upon reopening or after initiating a 'Resume'. (Have opened and closed app several times while composing this post and app appears to RESUME where it left off. Just performed a hard power cycle on my phone and app picked right up without a complete reboot. Consider this a non-issue.)

Second, is there a prescribed sequence for shutting down the Nspire emulator prior to closing out of the app?

Next, upon reopening (re-initiating) Firebird, I encounter the following error message, 'Detected problems with app native libraries (please consult log for detail); libfirebird.so text relocations'. How best to resolve this nuisance?

Last, have attempted and failed (emulator won't start) to configure Firebird for the same firmware release of CX-CAS. Any recommendations?

Device is an LG Rebel 4 running under Android 8.1 (Oreo), Kernel v3.18.71 and SW v-L212VL15a, 16GB-ROM (2GB free) and 2GB-RAM, and 1.4GHz-Quad Core Snapdragon CPU.

Thanks in advance and awaiting your response(s).

**Comment by Vogtinator** [comment]
> Second, is there a prescribed sequence for shutting down the Nspire emulator prior to closing out of the app?

To make use of the "Suspend on exit" feature, you need to use the back button. The flash has to be saved manually anyway, so you can quit the app any way you like.

> Next, upon reopening (re-initiating) Firebird, I encounter the following error message, 'Detected problems with app native libraries (please consult log for detail); libfirebird.so text relocations'. How best to resolve this nuisance?

Please try v1.5 first, it shouldn't have any text relocations anymore.

> Last, have attempted and failed (emulator won't start) to configure Firebird for the same firmware release of CX-CAS. Any recommendations?

How did you create the flash image and how does it fail?

**Comment by Madeirio** [comment]
Vogtinator, 

Thanks for the swift response. CX appears to be functional as I am able to navigate through various menus. As a noob to the Ti-Nspire, I've yet to indulge in it's mathematical machinations.

Currently unable to save the CX (CX-4.3.0.702) version as a unique configuration. Despite attempts to load a second image: Flash-CXCAS-4.3.0.702.tcc (with boot2cx.img and Snapshot-CXCAS-4.3.0.702.img), Firebird defaults to CX. I've tried iterative steps at loading CX-CAS firmware; cleared the app's cache, then cleared its memory and cache, and finally scrubbed Firebird and reinstalled it, each time it fell back to CX.

Somehow between re-installations of Firebird, initially v1.4, I finally got a release to work thinking it was the same v1.4 but now under App's Info it indicates 0.3-beta. Will scrub it it from the phone and install FB v1.5 and try to load CX-CAS first.

The full complement of firmware files were obtained online at a presumed legitimate website.

**Comment by Madeirio** [comment]
Vog,

Have downloaded v1.5, anew, and installed under Android.  While swiping to access the configuration setup, at the very bottom reveals v1.4-dev. The result is the same as before: CX configures properly and CX-CAS does not.

**Comment by Vogtinator** [comment]
> Currently unable to save the CX (CX-4.3.0.702) version as a unique configuration. Despite attempts to load a second image: Flash-CXCAS-4.3.0.702.tcc (with boot2cx.img and Snapshot-CXCAS-4.3.0.702.img), Firebird defaults to CX. I've tried iterative steps at loading CX-CAS firmware; cleared the app's cache, then cleared its memory and cache, and finally scrubbed Firebird and reinstalled it, each time it fell back to CX.

Do you mean the hardware type shown in the kit management dialog? If so, that's entirely controlled by what is selected during flash creation.

> The full complement of firmware files were obtained online at a presumed legitimate website.

If you mean boot1, any website providing a download for that can't be legitimate as sharing it is not allowed.
