### ISSUE TITLE
eFuse ID in Aladdin PMU for CX II

### ISSUE THREAD

**Issue by zephray** [nspire-emus/firebird#219]
Hi, when I was reading the code for the initial CX II support by @Vogtinator , I noticed that there is a TODO item for the eFuse value (0x90140808). So I went ahead and read the value on my own TI nspire CX II-T CAS rev AE, and I got 0x004566A4, this is certainly very different from the one currently used in the emulator. I guess we need to gather more information to better understand the nature of this value.

**Comment by Vogtinator** [comment]
Thanks for the info! I just had a look at what that value might do and it seems like it's copied verbatim into the device id. I couldn't find any other use of that value.

The lower bits of `0x9014080C` are in the device ID as well, apparently.

**Comment by zephray** [comment]
Cool, so I guess we can document that now.
