### ISSUE TITLE
Cannot move application docks while minimized

### ISSUE THREAD

**Issue by Circvmingo** [nspire-emus/firebird#222]
When moving keyboard dock below emulator window, firebird emu 1.5 crashes then quits. Tried it several times and the issue appears to be consistent, but only when no snapshot is saved? It's definitely a strange and rather minor issue, but still an interesting one that may be linked to something larger. Or it could be that I don't know what I'm talking about. Either way, I thought someone might want to know

Cheers!
-Circ

**Comment by Vogtinator** [comment]
I can't reproduce this issue here. Is this on macOS, Linux or Windows? Can you get a backtrace of the crash?

**Comment by Circvmingo** [comment]
It was on Windows 10. I tried several times to reproduce the conditions and result , but I couldn't get it to happen again either. Also, I looked for a while for any logs of the crash but I couldn't find them. I'm really sorry, I know I'm not exactly being the most helpful but I'm trying to do what I can.
