### ISSUE TITLE
iPad - When in Portrait, Keypad does not show up

### ISSUE THREAD

**Issue by vb-03** [nspire-emus/firebird#230]
- Model: iPad (7th Gen)
- iOS: 14.4.1
- Version: 1.5

When using iPad, in Portrait, or when dragging the app from the dock to overlap to another app, the keypad doesn't show up and the screen is way lower then it should be.

- Screenshots: https://imgur.com/a/ARywLxr

**Comment by Vogtinator** [comment]
Dup of https://github.com/nspire-emus/firebird/issues/199, fortunately already fixed

**Comment by tigeryu8900** [comment]
@Vogtinator Can you build the iOS version without this bug? Thanks.

**Comment by adriweb** [comment]
I would be the one to provide iOS builds (although I don't even know how they're supposed to be installable anyway if you're not jailbroken or not the author or the build ; would be easier to build it yourself if you have a mac)... I'm very busy these days but I'll try to provide an IPA at some point. For the latest master branch state.

**Comment by vb-03** [comment]
I believe it is possible to install with AltStore.
________________________________

**Comment by adriweb** [comment]
Yes possibly, or similar tools.

**Comment by tigeryu8900** [comment]
I use AppSync Unified and Filza.

**Comment by tigeryu8900** [comment]
> I would be the one to provide iOS builds (although I don't even know how they're supposed to be installable anyway if you're not jailbroken or not the author or the build ; would be easier to build it yourself if you have a mac)... I'm very busy these days but I'll try to provide an IPA at some point. For the latest master branch state.

Thanks. I don't have a mac next to me so I can't build them.
