### ISSUE TITLE
This emulator, does it work also with Ti Nspire CX II CAS?

### ISSUE THREAD

**Issue by CodeGenStudio** [nspire-emus/firebird#233]
So while following the wiki and stuff, I figured that this emulator is only designed for the Ti-Nspire CX/CX CAS right? Not Ti-Nspire CX II/CX II CAS.

**Comment by adriweb** [comment]
﻿No, it is also working for the CX II , however there is no public software to fully dump the CX II that would make it boot in Firebird.

**Comment by CodeGenStudio** [comment]
@adriweb Ahh ok thats why. I'm able to dump some files from my CX II-T but problem is i'm not sure which one is boot1 rom and boot2 rom, and there is another file called osldr.img . Also, the emulator wants a .tcc file for the OS, whereas the CX II series uses a .tcc2 file for the OS.
