### ISSUE TITLE
Using Polydumper.

### ISSUE THREAD

**Issue by itsJavaCoder** [nspire-emus/firebird#238]
Im currently in the process of setting up Firebird and according to the wiki I must download 'Polydumper'. I've downloaded it and extracted it but from here I am confused.
![image](https://user-images.githubusercontent.com/67208310/122278685-cb926d80-ceac-11eb-8fc9-773b62fec147.png)
Should I just transfer the tns file to my CX CAS, or are the 'source' and 'old_binaries' folders used in any way?

**Comment by Vogtinator** [comment]
Yep, you only need the `.tns`.

**Comment by itsJavaCoder** [comment]
> Yep, you only need the `.tns`.

ok thanks!
