### ISSUE TITLE
Touchpad not working

### ISSUE THREAD

**Issue by NobiDevs** [nspire-emus/firebird#241]
My touchpad isn't working. I don't know if this is supposed to happen or not but all I know is that it isn't working.

**Comment by Vogtinator** [comment]
Do the arrow keys work?

If you go into graph mode and plot a function, the cursor is forced to appear. Does it move then?

**Comment by itsJavaCoder** [comment]
> Do the arrow keys work?
> 
> 
> 
> If you go into graph mode and plot a function, the cursor is forced to appear. Does it move then?
Yes the arrow keys work. I'm going to try to force the cursor to appear.

**Comment by itsJavaCoder** [comment]
> Do the arrow keys work?
> 
> 
> 
> If you go into graph mode and plot a function, the cursor is forced to appear. Does it move then?

The cursor disappears after I leave the graph. And when I was still in the graph the calculator cursor was higher than my cursor and I don't know why.

**Comment by Vogtinator** [comment]
That's expected. Cursor movement is relative, so you have to use the touchpad like you would on a real calculator.

**Comment by itsJavaCoder** [comment]
> That's expected. Cursor movement is relative, so you have to use the touchpad like you would on a real calculator.

Ah I see.
