### ISSUE TITLE
Next public beta?

### ISSUE THREAD

**Issue by dexman545** [nspire-emus/firebird#25]
Just curious about if there are any plans currently to publish another pre-built release of firebird.

**Comment by adriweb** [comment]
Most definitely, however we have no ETA :P
I think the Windows version needs to be fixed regarding some recent changes, otherwise the current code is a nice step forward compared to the latest release/build.

**Comment by adriweb** [comment]
The Windows version should now be on-par with the other platforms, feature-wise.
After some more testing of the recent improvements, we'll probably make a new release.

**Comment by Vogtinator** [comment]
Done!
