### ISSUE TITLE
System Error halfway through load

### ISSUE THREAD

**Issue by terrafrost** [nspire-emus/firebird#250]
I'm using the same ROM image for two different Galaxy S21 Ultra's but on one of them I'm getting a "System Error" error halfway through the loading process as https://i.stack.imgur.com/7A73b.jpg demonstrates.

Any ideas?

**Comment by Vogtinator** [comment]
By ROM, do you mean Boot1 or Flash or both?

If both files are identical, then that's really strange.

**Comment by terrafrost** [comment]
Yah - that's what I mean. Both Boot1 and Flash are the same.

The Android versions are probably different. I can get that information in a few days but don't have that information readily available to me right now

**Comment by Vogtinator** [comment]
Does the behaviour change if you reset a few times on both devices?

If you make a snapshot with the working device, does it work in the non-working one? Hm, snapshot saving/loading might not work with recent android versions...

**Comment by duckduckgo2022** [comment]
I did not get any error in Android 11 (Motorola Edge plus with longer height, similar to Samsung S21) but the Nspire doesn't stay on screen. When I look at its hidden screen, bringing it to front then it disappears again.

**Comment by Vogtinator** [comment]
What do you mean by "hidden screen"? Background apps maybe?

**Comment by duckduckgo2022** [comment]
On Android phone, hidden screen in background until you flush it so after I configured Nspire, the main Nspire calculator disappears into background. Please see screen shot showing it in background
![Screenshot_20211223-195400](https://user-images.githubusercontent.com/95590893/147303192-6fa54578-0a4a-45b3-bcdd-ec95b4238d83.png)
.

**Comment by Vogtinator** [comment]
> On Android phone, hidden screen in background until you flush it so after I configured Nspire, the main Nspire calculator disappears into background. Please see screen shot showing it in background. Can't keep it in front. Anytime, pull it out then it disappears again.

That sounds like it crashes when it tries to resume the activity. Can you get the adb log? Do you have automatic snapshots enabled?

**Comment by Vogtinator** [comment]
No response, closing.
