### ISSUE TITLE
Suggestion| Support for non-jailbroken iOS Devices

### ISSUE THREAD

**Issue by BootLoaderANK** [nspire-emus/firebird#251]
### What Happened
Previously I was using an old iPad and that is jailbroken, which ran Firebird Emu perfectly. I can manage the boot1cx and flash via iFile. But that device runs slow so I decided to purchase a new one. After I got the new iPad (`A2377`), I install the application with `AltStore`, but I found that I could not import the boot1cx or the flash file anyway. The version of system is not supported to jailbreak, but I need to run it. I take note using the iPad and wish to copy the screenshot of the emulated calculator to the notes in order to display functions or plots. So could you please to support the original Apple File app in order to support the non-jailbroken devices? It was great of you to do so— it will save my day!

### My iPad Model and OS Version
> Model: MHQU3CH/A | A2377        (M1)
> System Version: iOS 15.1

### My suggestion
Beside the built-in explorer, could you enable the Apple File browser so that non-jailbroken users can import the files to set up the emulator without jailbreaking it?

**Comment by adriweb** [comment]
It works for me if I save the boot and flash somewhere accessible by the files app, so I'm not sure to see what the problem is?

**Comment by BootLoaderANK** [comment]
> It works for me if I save the boot and flash somewhere accessible by the Files app (/ open file dialog), so I'm not sure to see what the problem is? Could be the on-phone Documents or Downloads folder, or the iCloud one. I tried both IIRC.
> 
> Regardless, this part is handled by Qt, IIRC... And now I'm wondering what happens with old (well, the latest release?) builds of Firebird on new iOS. What I tested was with Qt 5.15 and/or 6.x)

Hi, I am still learning to express in English, so if I express something wrong, please forgive me.

I tried to save the files in the File app, b it I cannot access them.

Here is the screen shot.
![IMG_0726](https://user-images.githubusercontent.com/65069930/144414154-1b62d133-17f3-4bab-9269-c59c3ac1483c.jpeg)

I save the file in the “Download” section and try to visit it in the browser of the application, but it cannot be read.

**Comment by adriweb** [comment]
Right, so this is the "old" (corresponding to the release) look of the file chooser, and this is actually managed by Qt, not us. If you re-build the app with a recent Qt, the file chooser will use the native Files app chooser.

Anyway, for your situation, you _should_ (haven't checked, since I myself use a build with a recent Qt...) be able to use the "File sharing" in iTunes/Finder where you can drag'n'drop files in the Firebird app part. Then on the app, tap one of the shortcuts in the sidebar that we can see in your screenshots, I don't remember which one it is... Maybe documents? or Home ? Or the app folder?
Anyway, let me know.

**Comment by BootLoaderANK** [comment]
> Right, so this is the "old" (corresponding to the release) look of the file chooser, and this is actually managed by Qt, not us. If you re-build the app with a recent Qt, the file chooser will use the native Files app chooser.
> 
> Anyway, for your situation, you _should_ (haven't checked, since I myself use a build with a recent Qt...) be able to use the "File sharing" in iTunes/Finder where you can drag'n'drop files in the Firebird app part. Then on the app, tap one of the shortcuts in the sidebar that we can see in your screenshots, I don't remember which one it is... Maybe documents? or Home ? Or the app folder? Anyway, let me know.

Oh I haven’t try these yet for my laptop’s broken. Thank you so much for your patience. If I have problem again, I will create a new issue, anyway, wish you a good day!
