### ISSUE TITLE
A way to reset UI?

### ISSUE THREAD

**Issue by mstallone** [nspire-emus/firebird#26]
Hello, when I first downloaded firebird I accidentally removed all of the sections on the main window. Is there a way to restore it back to normal? 

<img width="941" alt="screen shot 2015-12-02 at 9 47 56 pm" src="https://cloud.githubusercontent.com/assets/4524270/11552900/899173f8-993e-11e5-83c8-8b7877937e2d.png">

Cheers

**Comment by Vogtinator** [comment]
That should not be possible, after only one dock is remaining, that one does not have close buttons.
To reset the UI, you have to delete the settings for now, @adriweb knows how to do that.

**Comment by Vogtinator** [comment]
I'll add a new menu "Docks" on all platforms, it's probably the most intuitive option anyway.

**Comment by adriweb** [comment]
Hmm yes, good idea about the menu somewhere, and a quick way to reset the UI to the default would be useful anyway.

In the meantime, @mstallone, you can indeed try to delete the config file(s) in the `~/Library/Preferences/` folder (do a Cmd-Shift-G in Finder to get there quickly). It's a file like com.ndless.firebird.plist or maybe com.adriweb.firebird.plist, depending on the version.

**Comment by mstallone** [comment]
Thanks @adriweb, everything is working perfectly now.

**Comment by Vogtinator** [comment]
The menu is implemented and should work on all platforms now.
