### ISSUE TITLE
What Parameters/Versions are used for compiling an Android APK

### ISSUE THREAD

**Issue by CKraft11** [nspire-emus/firebird#263]
Wanting to test out a few changes and am having trouble making an apk so I was wondering if you had any ideas.

**Comment by Vogtinator** [comment]
Basically any recent (5.14 or 5.15) Qt for Android build setup should work OOTB.

What did you stumble over?

**Comment by CKraft11** [comment]
> Basically any recent (5.14 or 5.15) Qt for Android build setup should work OOTB.
> 
> What did you stumble over?

I had some issues with them removing the androidextras package in newer versions of qtcreator, I'll have to look back and see if it is supported in those you listed above. I was also having a hard time manually getting it to compile to anything that wasn't x86_64. I'm assuming it's because I'm not putting flags in the qmake or make commands to tell it the architecture but I don't know that those would be.

**Comment by Vogtinator** [comment]
As long as you have the full NDK and Qt installation, it should automatically build an APK for `x86`, `x86_64`, `armeabi-v7a` as well as `arm64-v8a`. Just use `qmake` from the Qt for Android install directory without additional parameters or the usual build configuration in Qt Creator.

With the qt6 branch it's also possible to build FB for Android with Qt 6, without any changes to the code using androidextras.

**Comment by Vogtinator** [comment]
No response, closing.
