### ISSUE TITLE
Firebird crashes shortly after startup on Fedora rawhide w/ GNOME

### ISSUE THREAD

**Issue by kelvinnkat** [nspire-emus/firebird#269]
Whenever I try to start up the emulator it crashes within a few seconds. According to ABRT, this is what the user logs say: 
User Logs:
```
Sep 01 00:20:49 kk firebird-emu[502019]: QSocketNotifier: Can only be used with threads started with QThread
Sep 01 00:21:02 kk firebird-emu[502365]: QSocketNotifier: Can only be used with threads started with QThread
```

The more complete trace is linked below.
[firebird crash logs.txt](https://github.com/nspire-emus/firebird/files/9467230/firebird.crash.logs.txt)

I haven't really gotten fully used to the process of sending logs for fixing, so if there's something else I can do, let me know!

**Comment by Vogtinator** [comment]
I guess some changes in Fedora made it so that `-no-pie` is no longer enough to avoid ending up with a PIE binary.

It should work with the builds from git, can you try https://software.opensuse.org/download.html?project=home%3AVogtinator%3Afirebird-emu%3Aunstable&package=firebird-emu&locale=en?

**Comment by Vogtinator** [comment]
No response, closing.
