### ISSUE TITLE
the numbers in shadow is invisible

### ISSUE THREAD

**Issue by rxdntsx123** [nspire-emus/firebird#270]
I used the rom dumped from nspire cas with Touchpad to start up.
Letters and numbers in shadow is invisible.
The screen is unclear ,is not Point-to-Point Display.
Can you help me?
![Screenshot_2022-09-24-11-06-07-35_e62297963dcd82a5d43736e9745000df](https://user-images.githubusercontent.com/114271625/192077711-2d27fbde-bbb9-4449-81dd-17c4e85d16bd.jpg)
![IMG_20220924_111344](https://user-images.githubusercontent.com/114271625/192077723-1a477fa0-33b6-40c5-9bb8-c079b4910462.jpg)
![IMG_20220924_111422](https://user-images.githubusercontent.com/114271625/192077730-1c1138e3-abe6-4707-9d8f-f6c7240e0c21.jpg)
![IMG_20220924_111451](https://user-images.githubusercontent.com/114271625/192077737-a282e862-dcaa-4d5e-b380-ba4996128702.jpg)

**Comment by adriweb** [comment]
Could you take a picture of what it looks like on your calculator?

**Comment by rxdntsx123** [comment]
![IMG_20220924_151437](https://user-images.githubusercontent.com/114271625/192085451-2ad0288c-d8e2-4667-a110-ef8fdcd4827b.jpg)

**Comment by adriweb** [comment]
I'll let @Vogtinator weigh in :p

**Comment by Vogtinator** [comment]
Looks like `lcd_cx_draw_frame` is missing the palette shift code. I'm not entirely sure why that is only needed there and not for the CX, but I suppose just copying that over with a `if(!emulate_cx)` is good enough.
