### ISSUE TITLE
How do I write a plus sign with a keyboard?

### ISSUE THREAD

**Issue by wyattjohnsonbro** [nspire-emus/firebird#272]
The title pretty much sums it up. How would I write a plus sign with the keyboard?

**Comment by Vogtinator** [comment]
If your keyboard does not have a plus key, you can use alt + equals.

**Comment by wyattjohnsonbro** [comment]
ah, okay!

**Comment by wyattjohnsonbro** [comment]
it worked once when I just kind of spammed shift so... if there a way to just use shift?

**Comment by wyattjohnsonbro** [comment]
also, if there a list of like inputs I can do to get each character?

**Comment by Vogtinator** [comment]
Only the code itself: https://github.com/nspire-emus/firebird/blob/18daacaf37754c1b8bd11201b21d0f537ac5ca3f/qtkeypadbridge.cpp#L25
