### ISSUE TITLE
CX II + Boot files

### ISSUE THREAD

**Issue by rayzerbrain** [nspire-emus/firebird#277]
Apologies in advance, I'm new here. If I understand correctly, all I need for emulation is a copy of the operating system I want and the two boot files

Is CX II support with the latest build only possible with illegal/impossible to obtain boot files?

Additionally, is ndless the only legal way to obtain such files, CX II or no? (I currently have a CX II incapable of running ndless due to the OS version)

**Comment by Vogtinator** [comment]
> Apologies in advance, I'm new here. If I understand correctly, all I need for emulation is a copy of the operating system I want and the two boot files

It's actually just the boot rom. bootloader and installer can be extracted from the OS archives.

> Is CX II support with the latest build only possible with illegal/impossible to obtain boot files?

Correct. You can dump the boot rom using ndless, but the section containing the decryption keys will be empty.

> Additionally, is ndless the only legal way to obtain such files, CX II or no? (I currently have a CX II incapable of running ndless due to the OS version)

Correct.

**Comment by rayzerbrain** [comment]
Thanks, that's all I needed

**Comment by TKperson** [comment]
Can you explain a little more? I'm currently having similar issue. I'm also new to this, so excuse me if I said anything wrong.

My emulator debugger outputted:
```
Incomplete bootrom dump detected: Booting will fail.
There is currently no public way to perform a complete readout.
```

Does this mean that polydumper cannot dump a complete boot ROM for legal reasons? Or is it because polydumper cannot find a way to decrypt the "encrypted" ROM data?

If this issue is not fixable currently, is there any other ways that I can try to emulate my CX II calculator?

**Comment by Vogtinator** [comment]
> Does this mean that polydumper cannot dump a complete boot ROM for legal reasons?

For technical reasons.

> Or is it because polydumper cannot find a way to decrypt the "encrypted" ROM data?

The ROM is not encrypted, but the encryption keys in ROM are "hidden" to prevent extraction.

> If this issue is not fixable currently, is there any other ways that I can try to emulate my CX II calculator?

In theory, with some work, yes. You could run the OS decryption routine on the calculator itself and inject the raw OS into firebird. There's no code for that available though so you'd have to get the IV and other info yourself first...

**Comment by TKperson** [comment]
Thanks for answering my questions. It's sad to see that they are limiting their users from having full access over their devices after we paid them ~100 USD per calculator 

I don't think I'll spend that much effort to get the extraction working. I'll just wait for someone to make a script for this
