### ISSUE TITLE
Improper boot1 and flash image for iOS

### ISSUE THREAD

**Issue by mstallone** [nspire-emus/firebird#28]
Hi, I just downloaded the firebird.ipa to use on my iPhone. I transferred the the boot1 and flash I use for firebird on my Mac (they work) through iTunes. I selected the the two files in the mobile app and when I press "start," I get "You need to select a proper boot1 and flash image before. Swipe the keyboard to the left to show the settings menu." I did select the proper files. I cannot get the simulator to work on my phone? 

Cheers

**Comment by Vogtinator** [comment]
The files for iOS have to be at a specific location for some reasons:
"<APPROOT>/Documents/boot1.img" and "<APPROOT>/Documents/flash.img".

**Comment by mstallone** [comment]
Okay, that fixed that, but now I get the toast notification of "Emulation started," then the app crashes right after?

**Comment by Vogtinator** [comment]
@adriweb can probably help here better than I can.
Can you provide a backtrace and other logs?

**Comment by adriweb** [comment]
Hmm, probably not much to work with on a release build...
Is your iPhone jailbroken ? Mine (iPhone 5) is and I have no crashes so far. There have been changes recently on how the JIT (what the jailbreak is used for here) is used, so maybe that's a bit broken on iOS.

I'll also try Firebird on an non-jailbroken iPad very soon, so maybe I'll be able to help more directly

**Comment by adriweb** [comment]
I was able to reproduce on a non-jailbroken iPad, and have a code that fixes it (correctly detects the fact that JIT can't be used).
An updated iOS build should be available soon.

**Comment by adriweb** [comment]
I quickly updated the .ipa on the release page: https://github.com/nspire-emus/firebird/releases/download/v0.30/firebird-iOS.ipa 
Please re-open the ticket if this still doesn't work (worked for me on two devices though !)

**Comment by PaulBGD** [comment]
Just installed on my jailbroken iPhone 5s, after naming the files correctly and trying to start I get the single message "Couldn't start emulation". Is there a log file somewhere I could check?

**Comment by adriweb** [comment]
Hmm, I don't think there is a log to look at. But at least it didn't crash.
So, if I understood correctly, you created a flash image from Desktop firebird, transferred it via iTunes as `flash.img` as well as a `boot1.img` (dumped from your CX) ?
This is what's supposed to be done, and so far has worked for me on two devices.

While it shouldn't matter, try putting just "state" as the snapshot file (so, for instance, select the flash.img file and delete the last few letters from the path to put "state", no extension needed) and see if that works...

Any more ideas, @Vogtinator ?

**Comment by PaulBGD** [comment]
Tried the state, no such luck. Both files are named correctly (to the extensions) and in the Documents folder. I didn't actually use iTunes, I assumed SSH would work the same. However I can go ahead and try iTunes.

**Comment by adriweb** [comment]
By "Documents" folder, we mean the app's Documents folder (which is the one that iTunes sees in the file sharing pane in the app sync view, when you scroll down).
Maybe it was a permission issue if it was another Documents folder, which would explain the emulation fail.

**Comment by PaulBGD** [comment]
Could've been a permission issue. It was definitely the correct folder, after deleting them in iTunes then uploading them through iTunes the emulator starts.. then the app crashes.

**Comment by PaulBGD** [comment]
Here's a pastebin of the crash error: http://pastebin.com/jT078p77

**Comment by adriweb** [comment]
Ah, thanks. I'll try to get you a debug build so the crash logs will tell us exactly where the crash happened :)
I'm starting to wonder if all jailbreaks make dynamic code execution (seeing `KERN_PROTECTION_FAILURE` makes me think about that), or if I have just been lucky with my tests...

**Comment by PaulBGD** [comment]
I can compile it, any specific flags?

**Comment by adriweb** [comment]
All right, this binary shouldn't be optimized nor symbol-stripped, so it should be more helpful...
[firebird-ios_debug.zip](https://github.com/nspire-emus/firebird/files/66058/firebird-ios_debug.zip)

**Comment by PaulBGD** [comment]
Thanks, trying it now.

**Comment by mstallone** [comment]
Okay, just finished finals. I am running a jailbroken iPhone 5s (9.0.2). I just tried the debug ipa @adriweb posted. I still crashed on the start emulation (I also had the ".../Document/state" set for the state option). 

I managed to scrape the crashlog through xcode: http://pastebin.com/pPNrhU0L

Hope that will help

**Comment by Vogtinator** [comment]
No symbols.
I have no idea what the issue is, there are almost no differences in that code area since the last release.

```
Thread 12 name:  EmuThread
Thread 12 Crashed:
0   ???                             0x1cdd8000 0 + 484278272
1   firebird                        0x0005e4d4 0x4000 + 369876
2   firebird                        0x0001d884 0x4000 + 104580
3   firebird                        0x008f60d9 0x4000 + 9380057
4   libsystem_pthread.dylib         0x35ed7c93 _pthread_body + 139
5   libsystem_pthread.dylib         0x35ed7c07 _pthread_start + 111
6   libsystem_pthread.dylib         0x35ed5a24 thread_start + 8
```

**Comment by Vogtinator** [comment]
The ??? seem to be the translated code, though, so could you test the older release of firebird?

**Comment by mstallone** [comment]
I just booted up my old iPhone 5, which is also jailbroken and running 9.0.2. The emulation started! The only difference between the iPhone 5 and 5s that would affect the code is the architecture. The iPhone 5 is armv7, while the iPhone 5s is arm64. What is interesting is that on both cases the app launches; however, the when starting the emulation it crashes. I haven't really looked over the code (so I may be completely wrong), but I would assume that the iOS app is a wrapper for the emulator and that the wrapper was compiled for arm64 while the emulator itself was compile for armv6/7?

**Comment by adriweb** [comment]
Well, that's interesting...
I can

**Comment by Vogtinator** [comment]
Is it possible that the current build has some ARMv8-A code in it?
That would explain the issue.

**Comment by adriweb** [comment]
AFAIK, I only made it produce armv7 code.

**Comment by Vogtinator** [comment]
I had a second look at this:
```KERN_PROTECTION_FAILURE at 0x000000001cdd8000```
together with the information that PC is currently ```0x1cdd8000``` tells me that marking the code as executable failed somehow.
@adriweb: Any idea why only on 64bit?

**Comment by adriweb** [comment]
We probably would have to ask some jailbreak-knowledgeable people, I guess

**Comment by pangeacake** [comment]
I now have this exact behavior, crashing when starting as well.

**Comment by XDSS2002** [comment]
How do I get to the Documents Folder on iOS?

**Comment by adriweb** [comment]
On iTunes, you just have to drag'n'drop the boot1 and flash in the Firebird area of the app sharing pane. It will then appear automatically in the app's Documents folder within the app when your browse for them in Firebird.

**Comment by XDSS2002** [comment]
I placed the Flash Image and the Boot1 in the Documents folder using iTunes file sharing. When I go to select the boot1 and flash image, I press Documents and select them both. It still doesn't work. Do I have to choose anything for the snapshot location?

**Comment by adriweb** [comment]
No, snapshot location can stay empty.
Choosing a the boot1 file and flash file in the respective button/settings should work well, at least it does for many/all of us here.
How did you generate those .img files ?

**Comment by XDSS2002** [comment]
I used polydumper 4.2 and got the files boot1, boot2, manuf, and diags. Then, i used Firebird on Mac to create the Flash.img. It works fine on my mac, but it won't work on iOS. Also, should the boot1 be boot1.img or boot1.img.tns?

**Comment by adriweb** [comment]
Sounds good to me... especially if it works on the desktop app.
I don't think it matters (?) but the files I use are just .img.

**Comment by XDSS2002** [comment]
For the snapshot location, I accidentally pressed on boot1.img.tns. How do I set that back to "none"?

**Comment by adriweb** [comment]
Hmm, I don't know, but you can probably just choose a dummy file in the same location if the explorer can create or (else, transfer one from your computer)

**Comment by XDSS2002** [comment]
Should the flash be named something specific? (Mine is names nspire.img)

**Comment by adriweb** [comment]
Nope, though flash.img kind of works everywhere.
Which version do you have, btw? (of OS, boot1, Firebird desktop, Firebird iOS)

**Comment by XDSS2002** [comment]
I have Firebird 0.30 on Mac, but I don't know what version I have on iOS.
Also, I downloaded the .ipa from a website on my mac and put it on my phone via Cydia Impactor. Since my phone is jailbroken, is there another place where I could get it on my phone?

**Comment by adriweb** [comment]
A better way would be to download the files from the releases here: https://github.com/nspire-emus/firebird/releases/latest
Then again, the best way would be to build the apps yourself so that you have the latest version :P

I'll try to find more time soon anyway because I have to make new builds for iOS as several people have been expecting them.

**Comment by XDSS2002** [comment]
What is your preferred way to put the .ipa on my phone?

**Comment by adriweb** [comment]
I don't do that, I just launch the built app through dev tools (Qt Creator or more recently Xcode directly because it's gotten weird in Qt Creator).
If jailbreak, any .ipa installer should work.
But then again, it's free to test dev. things on device now, through Xcode.

**Comment by XDSS2002** [comment]
I'll try different things and i'll let you know if something works.

**Comment by pangeacake** [comment]
@adriweb sorry for the late reply, but in my last message I meant that firebird also crashes for me when I attempt to start emulation. (again, iPhone 6, 9.3.3 jailbroken)

**Comment by XDSS2002** [comment]
I downloaded Firebird on Windows, but when i try to run it, it says that MSCVO120.dll is missing.

**Comment by Vogtinator** [comment]
@XDSS2002 You need to install the Visual C++ Redistributable Packages for Visual Studio 2013
 (https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe)

**Comment by XDSS2002** [comment]
Hi, I was reading all the comments on this page and saw that adriweb suggested to someone to put the snapshot location as "state". Can someone explain to me how to do this?

**Comment by adriweb** [comment]
A new version has been released: https://github.com/nspire-emus/firebird/releases/latest
Please try it and see if that fixes the problem(s).

Closing the issue. Re-open if needed.
