### ISSUE TITLE
Windows touch screen support

### ISSUE THREAD

**Issue by PixelcrafterEXE** [nspire-emus/firebird#292]
I have a windows tablet running firebird but the keypad dock doesn't work porperly. By using a external trackpad or mouse everything works fine but if it try to tap with touchscreen or active pen the keys don't change collor (as they do when pressed with mouse) and the CAS doesn't get a input. Mobile view on Windows works.

**Comment by Vogtinator** [comment]
Looks like `QQuickWidget` does not accept touch events by default. We could either switch to `QQuickView` (have to do that for Qt6 anyway) or do `ui->keypadWidget->setAttribute(Qt::WA_AcceptTouchEvents);`.

**Comment by Vogtinator** [comment]
You can try one of the builds in https://github.com/nspire-emus/firebird/pull/293 once they're done.

**Comment by Vogtinator** [comment]
> You can try one of the builds in #293 once they're done.

FTR, they're done: https://github.com/nspire-emus/firebird/actions/runs/3795934362 for both 32bit and 64bit Windows.

**Comment by PixelcrafterEXE** [comment]
Works. Thanks!
