### ISSUE TITLE
I need help! I fork the project and make a pretty keypad, but the android Action build failed, do you know how to fixed it?

### ISSUE THREAD

**Issue by qingwa2009** [nspire-emus/firebird#303]
![Snipaste_2023-01-15_22-51-46](https://user-images.githubusercontent.com/9941628/212548314-2e09ffcb-c6dd-4783-a0c4-0e0aa21bb4b1.png)

This is the exception on Pack APK

1: Task failed with an exception.
-----------
* Where:
Build file '/home/runner/work/firebird/firebird/build/android-build/build.gradle' line: 37

* What went wrong:
A problem occurred evaluating root project 'android-build'.
> For input string: "ext4"

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'android-build'.
> compileSdkVersion is not specified.

**Comment by Vogtinator** [comment]
Those error messages look strange. Does it also fail if you try to build an unmodified branch?

**Comment by qingwa2009** [comment]
i dont know how to do!😔
should i make a new fork . and try to build it?

**Comment by Vogtinator** [comment]
I reran the CI for one of my PRs and it also fails. So something regressed.

**Comment by qingwa2009** [comment]
I bump to version 1.6(i fork from this project and dont change) and the actions android build is also failed！😭

**Comment by Vogtinator** [comment]
Fixed with #304.
