### ISSUE TITLE
Emulator crashed while attempted to add firmware files

### ISSUE THREAD

**Issue by DennyLiao607** [nspire-emus/firebird#307]
https://user-images.githubusercontent.com/99601414/219937839-a44bb0f8-345e-4099-a291-3b0b9d570975.mp4

**Comment by Vogtinator** [comment]
That is very strange and probably a crash in Qt. Can you get a backtrace somehow?

**Comment by DennyLiao607** [comment]
Later I reinstall Windows 11 and it can run properly
