### ISSUE TITLE
change product id?

### ISSUE THREAD

**Issue by jayrich5807** [nspire-emus/firebird#308]
What should I do if I want to change the product id?

**Comment by Vogtinator** [comment]
You mean the model type like Touchpad / CX / CX CAS? You select that when creating a flash image.

**Comment by jayrich5807** [comment]
TI NS PIRE CX CAS MODEL NOT 2
I want to match my FIREBIRD product ID with my calculator's product ID.

**Comment by Vogtinator** [comment]
Why? You can read the ID registers of your calc and then change the hardcoded values here: https://github.com/nspire-emus/firebird/blob/master/core/misc.c#L415

**Comment by jayrich5807** [comment]
It seems that the coded program runs based on the product ID, so I want to check it out.

**Comment by Vogtinator** [comment]
That sounds like you bought a lua program which uses that as a license check. Hm, might be a valid use case for importing a product ID.

**Comment by jayrich5807** [comment]
I haven't bought it yet, but I'm looking forward to trying it out.
I'm not a program expert, so I downloaded the Firebird emulator, but I didn't know where to edit the product ID, so I left an inquiry.

**Comment by jayrich5807** [comment]
I think it would be nice if there was a function to easily change the product ID in the emulator.

**Comment by adriweb** [comment]
It's not the simplest thing...
Try to build it with Qt creator, then when it fails (there's a qt bug), open the project in Xcode, then add the corresponding core's .s (asm) file  to the target, then rebuild. Then you can use it on your device.

**Comment by jayrich5807** [comment]
It's not that simple. Sorry for taking up your time. Since I am not an expert, I have no choice but to use the product ID without changing it.
Thank you for your kind reply.
