### ISSUE TITLE
#include <unistd.h> in #ifdef IS_IOS_BUILD in core/translate_aarch64.cpp

### ISSUE THREAD

**Issue by dnevistic** [nspire-emus/firebird#312]
I needed to add this include to core/translate_aarch64.cpp in order to use syscall() when compiling for my iphone 14 Pro Max on my M1 Pro Macbook using xcode 14.2:

#ifdef IS_IOS_BUILD
**#include <unistd.h>**
#include <sys/syscall.h>
#include <sys/mman.h>
#endif

**Comment by adriweb** [comment]
Ah yep can confirm I had to do that too since relatively recently.

**Comment by dnevistic** [comment]
Thanks!!
