### ISSUE TITLE
Handheld Not Recognized on Linux

### ISSUE THREAD

**Issue by superchessmachine** [nspire-emus/firebird#317]
I have my totally stock handheld plugged into my laptop running latest version of Linux Mint. The device is not recognized by anything or any aspect of the software. This includes the ti connect software from Texas Instruments directly. Any idea on how to have the handheld be recognized so I can save files to it? Thanks!

**Comment by Vogtinator** [comment]
Firebird does not communicate with physical calculators.

Regarding the issue with TI connect, note that it is not compatible with CX II models.
