### ISSUE TITLE
Firebird emu 1.6 crashes on Android 5.1.1

### ISSUE THREAD

**Issue by davidj77** [nspire-emus/firebird#321]
Hi, firebird emu 1.6 crashes randomly on Android 5.1.1 after start it.
It worked fine on Firebird emu 1.5.

**Comment by Vogtinator** [comment]
Can you get logs?

**Comment by davidj77** [comment]
How I can get them?

> Can you get logs?

How I can get them?

**Comment by davidj77** [comment]
I'm a new user of Firebird.

**Comment by davidj77** [comment]
How I can get them?

**Comment by Vogtinator** [comment]
You would have to use `adb logcat` on a computer. I'm unfortunately not aware of any other way. Does it provide you with any information other than "The app crashed"?

**Comment by davidj77** [comment]
How I can get them?
I'm a new user of firebird.

**Comment by davidj77** [comment]
Sorry but I'm not have any computer.

**Comment by davidj77** [comment]
I hope other user can provide logs.
Thanks for your attention. ❤
