### ISSUE TITLE
GPG key has expired.

### ISSUE THREAD

**Issue by AwwShoot** [nspire-emus/firebird#326]
I just tried to install this via dnf using the openSUSE  repo and got this error

  The certificate is expired: The primary key is not live
Key import failed (code 2). Failing package is: firebird-emu-1.6-5.1.x86_64
 GPG Keys are configured as: https://download.opensuse.org/repositories/home:/Vogtinator:/firebird-emu/Fedora_37/repodata/repomd.xml.key

**Comment by Vogtinator** [comment]
According to `osc signkey` it expires in two years. I guess the key was extended meanwhile but the repo not republished again after that, I triggered that manually now. Please try again.

**Comment by AwwShoot** [comment]
Thanks! It worked.
