### ISSUE TITLE
Problem with calculator's display 

### ISSUE THREAD

**Issue by mkhl9** [nspire-emus/firebird#329]
Hi there, my emulation of TI Nspire CAS has a problem with the display. I'm using Android 12.
Emulated OS version is 3.6.0.550.
Any ideas?
Thanks
Best regards

![Screenshot_2023-11-09-23-43-21-097_org.firebird.emu.jpg](https://github.com/nspire-emus/firebird/assets/45621060/2a7917f0-97c6-465d-a6e9-ae1d9c1ece35)

**Comment by Vogtinator** [comment]
You're actually looking at the diagnostics there. I assume this is because e9355984a099bd0678f6ba22d5f698a0e4aa672b is not in v1.6 and you're running 1.6?

**Comment by mkhl9** [comment]
> You're actually looking at the diagnostics there. I assume this is because [e935598](https://github.com/nspire-emus/firebird/commit/e9355984a099bd0678f6ba22d5f698a0e4aa672b) is not in v1.6 and you're running 1.6?

Thank you for your answer. Yes I'm running version 1.6.

**Comment by Vogtinator** [comment]
Please try a build from the master branch: https://github.com/nspire-emus/firebird/actions/runs/6207216175. You'll have to create a new flash image.

To install it, you'll have to remove the previous FB app and then install the apk. You'll lose all settings though.

**Comment by mkhl9** [comment]
It worked perfectly. Thank you very much!

**Comment by Vogtinator** [comment]
Perfect, thanks for confirming!
