### ISSUE TITLE
AUR pkgbuild error, and QtQuick error.

### ISSUE THREAD

**Issue by Zekario** [nspire-emus/firebird#33]
The AUR package has an error. It tries to use /src/firebird-nspire, instead of /src/firebird-0.11. I edited mine, and it installed. However, trying to run nspire_emu gave the following error:

`qrc:/qml/qml/Keypad.qml:2:1: module "QtQuick.Layouts" is not installed`
`[1]    19390 segmentation fault (core dumped)  nspire_emu`

Can I fix it or is it a problem with the package itself?

**Comment by Vogtinator** [comment]
Working builds for Arch Linux are on https://software.opensuse.org/download.html?project=home%3AVogtinator%3Afirebird-emu&package=firebird-emu

You don't have QtQuick Controls installed on your system. If you can tell me how the package is called, I'll add it as dependency to PKGBUILD.

The segmentation fault would be interesting. Can you provide a backtrace?

**Comment by Zekario** [comment]
QtQuick Controls is in the AUR as qt51-quickcontrols. I went to install it, but it was taking too long to compile and I aborted it.

How would I go about giving a backtrace?

**Comment by Vogtinator** [comment]
If qt51-quickcontrols means 5.1, that's too old anyway.

> How would I go about giving a backtrace?

Run it in gdb and run "bt" after it crashes.

**Comment by Vogtinator** [comment]
As known working builds are available, I'll close this.
