### ISSUE TITLE
File Transfer issue on iOS Version

### ISSUE THREAD

**Issue by DennyLiao607** [nspire-emus/firebird#332]
I dumped the img file via polydumper on Firebird iOS version but how can I get those files to my phone
![IMG_0123](https://github.com/nspire-emus/firebird/assets/99601414/a14a11a8-b988-47b7-8c51-4e1c9e582f2d)

**Comment by Vogtinator** [comment]
There's currently no way to send files from the emulated calc to the host in the mobile UI.

I do wonder why you're using polydumper in firebird though. You already used the files to get firebird booting...

**Comment by DennyLiao607** [comment]
I just want to make a flash file with newer system version
But later I use my PC and I succeed to make it
