### ISSUE TITLE
urgent

### ISSUE THREAD

**Issue by 1chau** [nspire-emus/firebird#335]
<img width="235" alt="Screenshot 2024-02-18 at 12 41 48 PM" src="https://github.com/nspire-emus/firebird/assets/160379479/196bc696-5fae-4fe3-bed7-d2a10309543e">
Hi all, I know this is kind of stupid questions but I accidentally turned off this one. How can I open it up on Mac. 
Thanks.

**Comment by adriweb** [comment]
You just use the macOS release?

At the time of this reply it's here: 
https://github.com/nspire-emus/firebird/releases/download/v1.6/firebird-emu_macOS.zip
