### ISSUE TITLE
Add artifact uploading to Travis

### ISSUE THREAD

**Issue by p0wer0n** [nspire-emus/firebird#34]
You should make it so when a build completes in travis, then the artifact will be uploaded to Github.

**Comment by Vogtinator** [comment]
Nope, builds are done by OBS.

**Comment by p0wer0n** [comment]
Are the build artifacts available anywhere?

**Comment by Vogtinator** [comment]
Nope. It wouldn't make much sense anyway as those binaries would only work on that specific ubuntu release + repos they're built on.

**Comment by adriweb** [comment]
(BTW for Windows there is http://pimathbrainiac.me/firebird/ providing nightlies)
