### ISSUE TITLE
Upload to AppStore

### ISSUE THREAD

**Issue by gfhdhytghd** [nspire-emus/firebird#340]
Hi！Apple just update its AppStore policy to allow emulators.
“Additionally, retro game console emulator apps can offer to download games.”
https://developer.apple.com/app-store/review/guidelines/#third-party-software
Maybe Firebird emu for iOS can now be update to AppStore? To some extend Nspire CX is a 13 year-old “retro””game console” right?

**Comment by Vogtinator** [comment]
I don't think that applies to firebird, as there are no downloads offered and it's not really a retro game console emulator.

There are also restrictions on JIT code execution as well as GPLv3 software (FWICT).

**Comment by gfhdhytghd** [comment]
Hi，UTM SE is now available on appstore, so I do think that you may have a try.
