### ISSUE TITLE
Submit to iOS AppStore?

### ISSUE THREAD

**Issue by yodaluca23** [nspire-emus/firebird#341]
Apple has recently allowed emulators on the official iOS AppStore, I was wondering if yall are going to try to submit it? Or if you already have?

Emulators already on App Store:

ScummVM- https://apps.apple.com/app/id6446184412

Delta- https://apps.apple.com/app/id1048524688

PPSSPP- https://apps.apple.com/app/id6496972903

RetroArch- https://apps.apple.com/app/id6499539433

Ignited- In reviewing process.

**Comment by adriweb** [comment]
Kind of a dup of #340.

Firebird is neither emulating a game console, nor is it "retro".

Thus, nope we can't, sorry.

**Comment by yodaluca23** [comment]
> Kind of a dup of #340.
> 
> 
> 
> Firebird is neither emulating a game console, nor is it "retro".
> 
> 
> 
> Thus, nope we can't, sorry.

Ok, thank you, I didn't see that issue, sorry.
