### ISSUE TITLE
TI-nspire CX CAS: Leaving Press-to-Test

### ISSUE THREAD

**Issue by cgloeckner** [nspire-emus/firebird#343]
Hi,

great software! But is there a way to simulate connecting the calculator to another one? I've tried entering the Press-to-Test mode but have no option of leaving (instead restarting the software and loading a snapshot from before entering Press-to-Test).

Cheers
glocke

**Comment by adriweb** [comment]
You can also just exit PTT by creating a "Press-to-test" folder (exactly named that way), then transfer in it a dummy/empty .tns file named "Exit Test Mode.tns" (exactly named that way).

**Comment by Vogtinator** [comment]
Correct. We could also add a button for that in the UI I suppose. Firebird only implements the PC interface, not sure if it's possible to use the calc-to-calc method of leaving PTT.

**Comment by cgloeckner** [comment]
I'd welcome a button just like @Vogtinator suggested.
My use case for the emulator is using it on a Linux-based computer during class to show my students how to work with their handhelds - including entering/leaving the test mode.

Btw did @adriweb's suggestion not work for me: I could not transfer a dummy file (it just says `Fehlgeschlagen!` / failed) when transfering a file). Saving a document with the suggested filename does lead to a long loading animation, followed by a connection error (as if someone tries to leave PTT without connecting the handheld).

**Comment by Vogtinator** [comment]
> Btw did @adriweb's suggestion not work for me: I could not transfer a dummy file (it just says Fehlgeschlagen! / failed) when transfering a file).

I just tried it here - works. In PTT mode the "Press-To-Test" folder (@adriweb used the wrong capitalization) already exists, so just sending a file "Exit Test Mode.tns" works.

**Comment by adriweb** [comment]
Ah well, I copied TI's instructions lol, guess they were wrong 🤡

**Comment by cgloeckner** [comment]
@Vogtinator: My tests above relate to the Android Version (not able to send a file): it continus to output `Status: Fehlgeschlagen!` (status: failed!)
![Screenshot_20240930-105729](https://github.com/user-attachments/assets/fb64f643-49b5-4784-91c8-cea33eeeec7b)

On Computer I'm able to transfer the `Exit Test Mode.tns` but I'm getting the same error.
![Bildschirmfoto vom 2024-09-30 10-54-47](https://github.com/user-attachments/assets/30fe821b-74f7-4c18-813b-d85bb0987973)
![Bildschirmfoto vom 2024-09-30 10-56-05](https://github.com/user-attachments/assets/a1a8b37c-fefa-4299-b7fa-5d08fa616dc4)

**Comment by cgloeckner** [comment]
Thanks for the info. On Android this led to a broken filename `Exit%20Test%20Mode` with masked whitespaces after transfering. Renaming manually afterwards to `Exit Test Mode` does let me leave PTT either.

On Computer, I manually moved the file to the PTT-folder because (see screenshot, the file is indented within the PTT-Folder).

Let me know when you've got more things to try :-)

**Comment by Vogtinator** [comment]
> Thanks for the info. On Android this led to a broken filename Exit%20Test%20Mode with masked whitespaces after transfering. Renaming manually afterwards to Exit Test Mode does let me leave PTT either.

Hm, right. There is a WIP fix in https://github.com/nspire-emus/firebird/pull/258, but not quite ready for merge yet.

> On Computer, I manually moved the file to the PTT-folder because (see screenshot, the file is indented within the PTT-Folder).

That won't work, it has to be transferred directly into the PTT folder using drag-and-drop in the file transfer tab.

**Comment by cgloeckner** [comment]
> Hm, right. There is a WIP fix in https://github.com/nspire-emus/firebird/pull/258, but not quite ready for merge yet.

Ok :) 

> That won't work, it has to be transferred directly into the PTT folder using drag-and-drop in the file transfer tab.

How do I specify the target folder? When I drag and drop the `.tns` file from my computer's file browser into the file transfer window, it's automatically uploaded to the calc's root folder.

**Comment by cgloeckner** [comment]
Here's what worked for me on Ubuntu: `Emulation` > `Configuration` > send file via the button. This automatically restarts the handheld and leaves the PTT without any additional keypresses.

**Comment by Vogtinator** [comment]
That way drag-and-drop onto the calc screen will also transfer into that folder which can be annoying. I recommend to drag-and-drop onto the folder in the file transfer tab instead.

Let's keep this open for adding a button.

**Comment by Vogtinator** [comment]
> Let's keep this open for adding a button.

Please try #352.

**Comment by cgloeckner** [comment]
> Please try #352.

The button works fine on my Linux machine in both modes: desktop and mobile view.

**Comment by Vogtinator** [comment]
> > Thanks for the info. On Android this led to a broken filename Exit%20Test%20Mode with masked whitespaces after transfering. Renaming manually afterwards to Exit Test Mode does let me leave PTT either.
> 
> Hm, right. There is a WIP fix in #258, but not quite ready for merge yet.

https://github.com/nspire-emus/firebird/pull/355
