### ISSUE TITLE
TI-nspire CX CAS: Unexpected Behavior in Relations Menu

### ISSUE THREAD

**Issue by cgloeckner** [nspire-emus/firebird#348]
Hi,

since a picture says more than a thousand words:

https://github.com/user-attachments/assets/8e3b6134-59f0-4d13-8b46-5babe855a815

This only happens on that exact same menu with `=`, `<` etc. The menu cannot be closed with Esc anymore; pressing Enter to insert a symbol makes things even worse. Only the touchpad keys / keyboard arrowkeys help here.

Tested with:
- `firebird-emu` v1.6
- using TI-Nspire CX CAS v4.5.5.79
- using Ubuntu (everything's fine on Android)

glocke

**Comment by Vogtinator** [comment]
Looks like somehow the right touchpad arrow is stuck. I cannot reprodue the issue here (Also Linux, but Plasma instead of GNOME).

Does the issue also happen if the keypad is below the screen (portrait mode)?

**Comment by cgloeckner** [comment]
Yes, this happens also in portrait mode and in normal desktop mode (non-mobile view) on my Ubuntu computer. I'm running xfce.

**Comment by complanar** [comment]
I can confirm the above mentioned bug. Also Linux on Xfce. Maybe I discovered a related bug. 

Pressing [AltGr] + [ß] (on german keyboards between [0] (zero) and [←] (backspace) brings up the trigonometric functions. After pressing it twice or three times, sometimes at the first try something similar happens:

https://github.com/user-attachments/assets/bfebb4c3-f4c5-46cd-8cf4-3864267190e4

As mentioned above only pressing the arrow key can stop this.

It does not happen, when bringing up the trigonometry menu with the virtual handheld keyboard, at least I never saw it happen and could not force it.

**Comment by Vogtinator** [comment]
Got it! It happens if you release the AltGr key before ß, which causes the trig key to get stuck. This means the release event doesn't get mapped properly.

**Comment by Vogtinator** [comment]
https://github.com/nspire-emus/firebird/pull/349 should fix this, it works reliably here.

**Comment by cgloeckner** [comment]
> #349 should fix this, it works reliably here.

I tried it: This fixes the trigonometry menu but not the relations menu.

**Comment by Vogtinator** [comment]
> I tried it: This fixes the trigonometry menu but not the relations menu.

Using the keyboard or the keypad widget?

**Comment by cgloeckner** [comment]
I was talking about entering the relations menu via the virtual calculator keypad :-)

**Comment by complanar** [comment]
Could it be that the first issue (relations menu) is dependent on the current state of the emulator? 

Sometimes it happens, sometimes not. If I restart firebird with a clean new boot image and flash everything seems to work. The relations menu only starts to behave weird, after some presses on the physical keyboard, especially if there were some modifier keys involved. I could not yet find out which key presses are the "bad" ones.

If I then save a snapshot and load from that snapshot later, the relations menu is broken from the beginning.

@cgloeckner Did you try out the patched version with an "old" snapshot or a completely new kit?

**Comment by cgloeckner** [comment]
> Did you try out the patched version with an "old" snapshot or a completely new kit?

I tried the patch version with an existing snapshot, which confirms your theory.

**Comment by Vogtinator** [comment]
Is there some stuck key visible in the keypad when it's broken (without loading a snapshot)?

**Comment by Vogtinator** [comment]
Actually, I can reproduce the issue easily straight after boot:

1. Press Ctrl and release it again
2. Press Shift
3. Press 0 (Shift + 0 -> =)
4. Release 0

The relations menu opens. It cycles through the options until shift is released.

I added some logging but it looked exactly as expected. I grabbed my CX and indeed, same behaviour! If you hold Shift while opening the relations menu, it cycles through options!

Other menus don't behave that way, so I guess this is just a calc OS bug?

**Comment by cgloeckner** [comment]
Omg yes: seems like its a OS bug. But releasing the shift key stops the behavior on the handheld

> Is there some stuck key visible in the keypad when it's broken (without loading a snapshot)?

I cannot see any visible keys being pressed/stuck on the emu's keypad.

**Comment by complanar** [comment]
> I grabbed my CX and indeed, same behaviour! If you hold Shift while opening the relations menu, it cycles through options!

I can confirm that this "bug" is still present in OS 6.2.0.333 although maybe this can't be considered as a bug. The shift key is just not intended to be hold on the handhelds, obviously that's why it is sticky.
