### ISSUE TITLE
See the entire keypad when in landscape mode (tablet)

### ISSUE THREAD

**Issue by bob8490** [nspire-emus/firebird#35]
This is amazing.  Props to everyone who put work into this. Fantastic.

One thing that would be neat if it's easy to do - on iPad (and android tablets, or even PCs/Macs), it would be nice to be able to see the entire keypad at once, with the screen off to the side when in landscape mode.  Sort of how TI does their SmartView: https://i.ytimg.com/vi/todG3tFDpHY/maxresdefault.jpg

Also, and I have no idea how this would be done on your end, but Maintenance mode would be nice to have.

USB link also does not seem to be working on OSX - the emulated calculator is not available in the TI link software, and does not show up in the System Report.

I'd be happy to donate if you have a PayPal address :)

**Comment by Vogtinator** [comment]
> USB link also does not seem to be working on OSX - the emulated calculator is not available in the TI link software, and does not show up in the System Report.

That's likely never going to work. OSX does not have an API to emulate a USB device in software AFAIK.

**Comment by Vogtinator** [comment]
> One thing that would be neat if it's easy to do - on iPad (and android tablets, or even PCs/Macs), it would be nice to be able to see the entire keypad at once, with the screen off to the side when in landscape mode. Sort of how TI does their SmartView: https://i.ytimg.com/vi/todG3tFDpHY/maxresdefault.jpg

That's actually relatively easy to do and is planned for the next release.

> Also, and I have no idea how this would be done on your end, but Maintenance mode would be nice to have.

It's already working! By right-clicking on the keypad you can hold keys down.

**Comment by bob8490** [comment]
Amazing. Thank you so much!

Sent from my iPhone

On Feb 17, 2016, at 1:47 PM, Fabian Vogt <notifications@github.com<mailto:notifications@github.com>> wrote:


One thing that would be neat if it's easy to do - on iPad (and android tablets, or even PCs/Macs), it would be nice to be able to see the entire keypad at once, with the screen off to the side when in landscape mode. Sort of how TI does their SmartView: https://i.ytimg.com/vi/todG3tFDpHY/maxresdefault.jpg

That's actually relatively easy to do and is planned for the next release.

Also, and I have no idea how this would be done on your end, but Maintenance mode would be nice to have.

It's already working! By right-clicking on the keypad you can hold keys down.

-

**Comment by bob8490** [comment]
Ah. Windows it is, then!

Thank you.

Sent from my iPhone

On Feb 17, 2016, at 1:45 PM, Fabian Vogt <notifications@github.com<mailto:notifications@github.com>> wrote:


USB link also does not seem to be working on OSX - the emulated calculator is not available in the TI link software, and does not show up in the System Report.

That's likely never going to work. OSX does not have an API to emulate a USB device in software AFAIK.

-

**Comment by Vogtinator** [comment]
Neither OSX nor Windows nor Linux support it. You need to use the integrated USB browser.

**Comment by Vogtinator** [comment]
This is now implemented in >= v1.0
