### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by bob8490** [nspire-emus/firebird#36]
This is amazing.  Props to everyone who put work into this. Fantastic.

One thing that would be neat if it's easy to do - on iPad (and android tablets, or even PCs/Macs), it would be nice to be able to see the entire keypad at once, with the screen off to the side when in landscape mode.  Sort of how TI does their SmartView: https://i.ytimg.com/vi/todG3tFDpHY/maxresdefault.jpg

I'd be happy to donate if you have a PayPal address :)

**Comment by adriweb** [comment]
closed, dup of #35

**Comment by bob8490** [comment]
Yeah, not sure why that happened. Sorry.

Sent from my iPhone

On Feb 16, 2016, at 2:44 PM, Adrien Bertrand <notifications@github.com<mailto:notifications@github.com>> wrote:


closed, dup of #35<https://github.com/nspire-emus/firebird/issues/35>

-
