### ISSUE TITLE
Fail to start in Windows 7: asks for msvcr120.dll

### ISSUE THREAD

**Issue by PaulEJKing** [nspire-emus/firebird#40]
The error message says something to the effect that "The program can't start because msvcr120.dll is missing from my computer. This is a C/C++ redistributable. Where can I get this file? Doesn't look like I can download it myself from M$ unless I buy myself Visual Studio.:-( Their docs suggest that the file is one that is freely distributable, so shouldn't you provide it with your distribution?

**Comment by Vogtinator** [comment]
You can get it from https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by PaulEJKing** [comment]
Thanks

**Comment by PaulEJKing** [comment]
The redistributable installed successfully, but I still get the same, identical error anyway. FYI, my machine is running 64-bit W7, so I had to install the x64 redistributable.

**Comment by Vogtinator** [comment]
You need the 32-bit redistributable as Firebird is a 32bit application on windows.

**Comment by PaulEJKing** [comment]
Also, it appears as if the installation is in-place from the zip file (ie, there is no actual installer for Firebird). Is this right?

**Comment by Vogtinator** [comment]
Yes. Firebird is "portable".

**Comment by adriweb** [comment]
Closing unless the error reappears (feel free to re-comment)
