### ISSUE TITLE
Use PNG images for some weird key labels

### ISSUE THREAD

**Issue by adriweb** [nspire-emus/firebird#42]
See title.

**Comment by Vogtinator** [comment]
Any progress on this?
/me wonders

**Comment by Vogtinator** [comment]
As you didn't get a mail,
\me pings you


Am Mittwoch, 13. April 2016, 20:08:05 CEST schrieb Adrien Bertrand:

**Comment by adriweb** [comment]
Haven't worked on it yet...
/me will do soon, hopefully

Thank you,
Adrien Bertrand

2016-04-19 11:38 GMT-04:00 Fabian Vogt <notifications@github.com>:

**Comment by adriweb** [comment]
(quick test)
PRIVMSG #firebird-emu ACTION lolz

Thank you,
Adrien Bertrand

2016-04-19 11:33 GMT-04:00 Fabian Vogt <notifications@github.com>:

**Comment by adriweb** [comment]
Will try to do that later tonight.
PRIVMSG #ez80-dev nom_nom_nom_optimizations

**Comment by adriweb** [comment]
(to be deleted)
PRIVMSG #firebird-emu #{botname}

Thank you,
Adrien Bertrand

2016-04-19 13:19 GMT-04:00 Adrien Bertrand <bertrand.adrien@gmail.com>:

> Will try to do that later tonight.
> PRIVMSG #ez80-dev nom_nom_nom_optimizations
>

**Comment by adriweb** [comment]
(to be deleted too)
PRIVMSG #firebird-emu what_about
PRIVMSG #firebird-emu multiple_lines
PRIVMSG #firebird-emu and spaces?

**Comment by Vogtinator** [comment]
Apparently you forgot it again!
PRIVMSG #firebird-emu :ACTION eats firebird

**Comment by adriweb** [comment]
https://github.com/Vogtinator/firebird/pull/37/commits/26da4c050bd5d193ad757fcd9193404510414f10 will solve that issue.

**Comment by Vogtinator** [comment]
Thanks!
PRIVMSG #firebird-emu :ACTION cheers
