### ISSUE TITLE
How to do a true hard reset?

### ISSUE THREAD

**Issue by MishaShapo** [nspire-emus/firebird#45]
I've noticed that when I install Ndless and then load the emulator with new flash images, the Ndless Logs still persist which leads me to believe that loading a new flash image is not really a "hard reset". I tried deleting the whole firebird folder, but that still didn't work. Is there a way to do a true hard reset with this emulator?

**Comment by Vogtinator** [comment]
Do you mean the serial output by "Ndless Logs"? If so, don't worry, the logs are never deleted.

To load a newly selected flash image, choose "Emulation->Restart".

**Comment by MishaShapo** [comment]
Vogtinator, this is in relation to the hooks that I asked you about, every time I uninstall the hook, there is a print message that I loaded a long time ago but deleted which leads me to believe that even though I am uninstalling the hook, there is still a part of the code that doesn't get deleted.

**Comment by Vogtinator** [comment]
Hm, in that case, could you try to disable the JIT by running the "t-" command in the debug console before installing the hook?

**Comment by MishaShapo** [comment]
I am at school right now, but I will give it a try tonight when I am back at my work station at home. Thanks for the recommendation.

**Comment by adriweb** [comment]
Re-open if necessary.
