### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Announcement** [nspire-emus/firebird#47]
How do I get it to detect my usb, most options are greyed out, is there some sort of driver or something?

**Comment by Vogtinator** [comment]
firebird does not require anything except an environment for Qt.

What do you mean by "detect my usb"?

Most options are greyed out if you haven't started the emulation yet. Read about that on https://github.com/nspire-emus/firebird/wiki/First-Time-Setup

**Comment by bemeurer** [comment]
I can second having some issues on Arch, can't transfer files to the emulated calculator.

**Comment by Vogtinator** [comment]
I can't reproduce it here on my openSUSE Tumbleweed and it also appears to work fine on OS X and Windows. Could you provide a screenshot or video demonstrating the issue?

**Comment by parkerlreed** [comment]
I might be able to shed some light. I hit USB connect and it goes green as if it's good but tilp as both regular and superuser cannot find it. Nothing shows up in dmesg either. How is the USB emulation implemented?

**Comment by Vogtinator** [comment]
firebird does not emulate a USB device, you need to use the internal file manager.

**Comment by adriweb** [comment]
i.e., drag'n'drop files in to transfer to the emulator, and in the file list you can right click to "download" them from the emu to your computer

**Comment by parkerlreed** [comment]
Ahh.
