### ISSUE TITLE
Issue with emulating OG Nspire Touchpad

### ISSUE THREAD

**Issue by parkerlreed** [nspire-emus/firebird#50]
I'm using Arch x86_64

firebird 0.30

Nspire OS version 3.6.0.550

Used latest polydumper to grab boot1, boot2, menuf, and diags images

Combined them with firebird in the Flash > Create flash menu

![1465829968](https://cloud.githubusercontent.com/assets/841440/16012126/0c0b952a-3156-11e6-8d6e-b8b449b4707e.png)

Booting just errors out here.

````
Boot Loader Stage 1 (1.1.8916)
Build: 2007/4/23, 23:37:16
Copyright (c) 2006, 2007 Texas Instruments Incorporated
Using production keys

Last boot progress: 0
Clocks:  CPU = 90MHz   AHB = 45MHz   APB = 22MHz   

Available system memory: 37292
Checking for NAND: NAND Flash ID: ST Micro NAND256R3A
PM is turning the device OFF
PM has turned the device ON
SDRAM memory test:   Pass
Clearing SDRAM...Done.
Clearing SDRAM...Done.
Clearing SDRAM...Done.
Boot option: Normal

Loading BOOT2 software...

Error reading/validating BOOT2 image

Error loading BOOT2, looking for pre-installed images.
Checking for DIAGS image in pre-install area.
No DIAGS image found.
Checking for BOOT2 image in pre-install area.
No BOOT2 image found.

Error loading BOOT2, install new version.
Checking battery level.
Battery level is OK.

Ready to download BOOT2 software...

Begin XMODEM file transfer.
Download error: 255BOOT1 Error: 
Halting boot due to download error.
````

**Comment by parkerlreed** [comment]
The exact same boot1.img and nspire.img does this on Android Marshmallow 

![cl928vx](https://cloud.githubusercontent.com/assets/841440/16012230/95cc8efe-3156-11e6-8bf0-d0534fd728e3.png)

**Comment by Vogtinator** [comment]
Apparently it didn't like the boot2 in the flash image or it joined them the wrong way.
Can you try to send boot2 over XModem (Tools -> Send file over XModem) after it shows "Begin XModem file transfer"?

**Comment by Vogtinator** [comment]
> The exact same boot1.img and nspire.img does this on Android Marshmallow

Are you sure they are the exact same files?

**Comment by parkerlreed** [comment]
Yes. Transferred them straight to the phone using FTP. I'll try the xmodem on the desktop real quick.

**Comment by Vogtinator** [comment]
That means two things:

- you used a diagnostics image as boot2
- Somehow it boots on ARM but not on x86_64

Can you try to run ```t-``` in the debugger console, press the reset button and continue using ```c```?
This disables the JIT so that only the interpreted core runs.

**Comment by parkerlreed** [comment]
````



Boot Loader Stage 1 (1.1.8916)
Build: 2007/4/23, 23:37:16
Copyright (c) 2006, 2007 Texas Instruments Incorporated
Using production keys

Last boot progress: 0
Clocks:  CPU = 90MHz   AHB = 45MHz   APB = 22MHz   

Available system memory: 37292
Checking for NAND: NAND Flash ID: ST Micro NAND256R3A
PM is turning the device OFF
PM has turned the device ON
SDRAM memory test:   Pass
Clearing SDRAM...Done.
Clearing SDRAM...Done.
Clearing SDRAM...Done.
Boot option: Normal

Loading BOOT2 software...

Error reading/validating BOOT2 image

Error loading BOOT2, looking for pre-installed images.
Checking for DIAGS image in pre-install area.
No DIAGS image found.
Checking for BOOT2 image in pre-install area.
No BOOT2 image found.

Error loading BOOT2, install new version.
Checking battery level.
Battery level is OK.

Ready to download BOOT2 software...

Begin XMODEM file transfer.
ownload error: 253BOOT1 Error: 
Halting boot due to download error.
````

And in the debug tab

````
xmodem got byte 44
````

**Comment by parkerlreed** [comment]
I can't seem to type in the debug console.

**Comment by Vogtinator** [comment]
You need to enter the debugger first (Tools -> Enter debugger)

**Comment by parkerlreed** [comment]
Aha recreated the nspire.img and it worked that time!

**Comment by parkerlreed** [comment]
It's at the same P3 DIAG screen now. How do I actually start the OS?

**Comment by Vogtinator** [comment]
You can switch between diags and boot2 using either firebird (Settings->Nspire->Boot) and then restart or press one of the key combos on https://hackspire.unsads.com/index.php/Operating_System#Startup_key_combinations

You should now that non-CX support is currently not that extensive, but most of the touchpad keys should work as-is.

**Comment by parkerlreed** [comment]
Ok weird. I thought I had booted to boot2. I retry boot2 and I'm back at that initial error I reported.

**Comment by parkerlreed** [comment]
I'll try everything from the start one more time (From polydump on the device) and see what happens.

**Comment by parkerlreed** [comment]
Here's the full process I did https://my.mixtape.moe/qeiynj.mp4

**Comment by parkerlreed** [comment]
Looking at the page you linked

````
A boot 2 image greater than 1358976 bytes (~1327kB, i.e. 10617 128-bit X-Modem packets) cannot be sent: the warning sign is displayed on the Nspire screen, and lsz hangs with "Got 44 for sector ACK". The size of boot2.img v1.4.1571 is 1216KB. (caution, this also could be the result of a streamed image validation by boot 1). 
````

My boot2 is 1359872 bytes. 896 bytes over. That also explains the error 44 I got on the debug output.

**Comment by Vogtinator** [comment]
Indeed. Apparently it does not create the flash image correctly.
I'll try to reproduce that, thanks for the report!

**Comment by parkerlreed** [comment]
Could it maybe be an issue with Polydumper on the calc itself? (Since that's what created that boot2 file)

**Comment by Vogtinator** [comment]
Issue fixed, it was a typo...

**Comment by parkerlreed** [comment]
Well it got a bit farther...

![1465847211](https://cloud.githubusercontent.com/assets/841440/16020922/1d68d396-317e-11e6-9646-341a5f24bf0b.png)

**Comment by parkerlreed** [comment]
Ok I dragged the OS onto the file transfer and it's sending. I'll see what happens.

**Comment by Vogtinator** [comment]
Yes! The OS preloading mechanism does not accept such big OS files...

**Comment by parkerlreed** [comment]
Sweet. Quick question: Is the mouse emulation implemented for the non-CX? Click and dragging on Linux and dragging on Android over the touchpad is not controlling the mouse. I'd love to just use the CX ROM and forget about the non-CX but I don't have a calc to dump from...

**Comment by Vogtinator** [comment]
It's implemented and works in Ndless apps, but the OS doesn't accept it.
You probably noticed how hard it is to get the cursor to show up on real hardware.
It's even harder in firebird and I haven't found a way to get it to appear reliably.

**Comment by parkerlreed** [comment]
On real hardware I can pretty much drag anywhere and it will appear (home screen works) But yeah I can see where that would be tricky. Thanks for the great emulator!

**Comment by gutsystudio** [comment]
Trying to Drag a little to show o use the cursor freeze the OS inthe firebird v1.3 and v1.2 in android Kitkat and Nougat.
While everythings is ok using the touchpad with the cursor in the windows version with the same files (Boot+flash+Snapshot): A fix please, i love somuch this EMU.
