### ISSUE TITLE
Assertion when launching an emulation.

### ISSUE THREAD

**Issue by Eiyeron** [nspire-emus/firebird#51]
Using my own boot1 and boot2 I could use in previous versions of firebird, I tried updating this tool up to HEAD (94a9baa), and the programs now crashes when starting the emulation with this error

```
firebird: ../core/translate_x86_64.c:53: emit_call_nosave: Assertion `false' failed.
fish: “./firebird” terminated by signal SIGABRT (Abort)
```

**Comment by Vogtinator** [comment]
Can you run it in gdb and provide the output of:

```
bt
info locals
print arm
```

**Comment by Eiyeron** [comment]
Fixed in squirrel's issue.
