### ISSUE TITLE
Support for 4.3?

### ISSUE THREAD

**Issue by vladhq** [nspire-emus/firebird#54]
Is there any possible way to add support for the latest 4.3 OS?

**Comment by Vogtinator** [comment]
There is nothing that needs to be done for that, it already works fine.
If you're using the manuf.img of a HW-W or later calc, you need to compile firebird from git or use one of the nightly builds as the last release does not have support for those.

**Comment by pangeacake** [comment]
Does PolyDumper work with the latest OS?

**Comment by Vogtinator** [comment]
There is no Ndless for OS 4.3 so you can't run PolyDumper on OS 4.3.

**Comment by Legimet** [comment]
You will have to find boot1 somewhere else. You can get boot2 by unzipping the 
.tcc/.tco file.
