### ISSUE TITLE
How to transfer files to the emulator in the android version

### ISSUE THREAD

**Issue by hazkaz** [nspire-emus/firebird#55]
I wanted to install endless on the android emulator version and I'm sorry but I've tried connecting the Android device to windows 7 using the TI nspire computer link software but it wont detect my device. I'm using os v 3.9.1.

**Comment by Vogtinator** [comment]
File transfer is not implemented yet in the Android version.

As a fairly complicated workaround: If you have access to a telnet client or netcat, you can connect to port 3334 of your android device (forward with adb first) and run the file transfer commands.

**Comment by awinterstale33** [comment]
could you possibly give some detail on how to do this?   Or just point me in the right directions for searching online?

**Comment by gotoAndDie** [comment]
Or could you transfer the flash image to another emulator, transfer the files on that, then send the image back to the Android?

**Comment by Vogtinator** [comment]
Starting from version v1.0 you can send single files with the Mobile UI as well. It's in the "File Transfer" tab of the settings.
