### ISSUE TITLE
Failed to start emulation on Android N

### ISSUE THREAD

**Issue by RicardoMartinez** [nspire-emus/firebird#56]
I just try to start the emulation on android N but first the app says that "Detected problms with app native libraries.

libfirebird.so: text relocations"

**Comment by Vogtinator** [comment]
Since API 23, Android enforces libraries to not contain text relocations, but firebird needs those for performance reasons. Firebird has the API version set to 14, so this shold not apply here. Did you build the app yourself?

**Comment by RicardoMartinez** [comment]
No, i just download the lasted version that you've upload ... But I don't build the app.

So if I build the app will be running on android N?

**Comment by Vogtinator** [comment]
I re-built the app with Qt 5.7 and removed relocations in .text. Please try the attached apk and confirm that it works, thanks!

[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/560033/QtApp-debug.zip)

**Comment by RicardoMartinez** [comment]
Thanks, i already try and the error disappear, but now it's says that can't start emulatuing

**Comment by Vogtinator** [comment]
Can you provide the logcat output? Are boot1 and flash setup correctly?

**Comment by RicardoMartinez** [comment]
I think that this its the logcat

11-12 18:28:05.232 I/Choreographer(25644): Skipped 67 frames!  The application may be doing too much work on its main thread.
11-12 18:28:09.973 W/System  (25644): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
11-12 18:28:09.982 E/BoostFramework(25644): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
11-12 18:28:09.982 V/BoostFramework(25644): BoostFramework() : mPerf = null
11-12 18:28:23.539 I/Choreographer(25644): Skipped 305 frames!  The application may be doing too much work on its main thread.
11-12 18:29:00.601 I/Adreno-EGL(25644): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
11-12 18:29:00.602 I/OpenGLRenderer(25644): Initialized EGL, version 1.4
11-12 18:29:00.602 D/OpenGLRenderer(25644): Swap behavior 1
11-12 18:29:18.406 I/Choreographer(25644): Skipped 32 frames!  The application may be doing too much work on its main thread.

And yes boot1 and flash are placed on the right way.

**Comment by Vogtinator** [comment]
That is the logcat output, but please upload everything from starting firebird until quitting the app. Preferably use a pastebin service.

**Comment by RicardoMartinez** [comment]
Sorry my bad... here i'ts the logcat:

[LogCat-Firebird](https://gist.github.com/RicardoMartinez/49ade5ed3969c71387a80fdbdd5e9d7a)

**Comment by Vogtinator** [comment]
Nothing useful in there, can you please try the apk from https://github.com/nspire-emus/firebird/pull/60#issuecomment-260159866 ?

**Comment by RicardoMartinez** [comment]
Already try it but, always the same error can't start emulation 

This its other log that I get:
`11-12 19:54:00.417 W/firebird(18915): (null):0 ((null)): Can't find surface 1
11-12 19:54:00.504 W/firebird(18915): (null):0 ((null)): Can't find surface 1
11-12 19:54:00.752 I/WindowManager(771): Destroying surface Surface(name=SurfaceView - org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.finishExit:516 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:176 
`

**Comment by Vogtinator** [comment]
With the apk from https://github.com/nspire-emus/firebird/pull/60#issuecomment-260159866 you will get a whole lot of other debug messages. Always upload the full log please!

**Comment by RicardoMartinez** [comment]
Mmm ok let me see, this its my full log:

[Full-LigCatOutput](https://gist.github.com/RicardoMartinez/e1d50409d4dd3f65cc5cc2723c0cd9a5)

**Comment by plusCubed** [comment]
Emulation is working fine on N for me (7.1.1 DP1 on Nexus 6P, 7.0 on Tab S), both with old version and new. The old one just has the text relocations warning dialog.

**Comment by RicardoMartinez** [comment]
@plusCubed could you please provide me with the boot & flash that are you using?

**Comment by adriweb** [comment]
A new version has been released: https://github.com/nspire-emus/firebird/releases/latest
Please try it and see if that fixes the problem(s).

Closing the issue. Re-open if needed.

**Comment by gutsystudio** [comment]
Trying to Drag a little to show o use the cursor freeze the OS in the firebird v1.3 and v1.2 in android Kitkat and Nougat.
While everythings is ok using the touchpad with the cursor in the windows version with the same files (Boot+flash+Snapshot): A fix please, i love somuch this EMU.

**Comment by gutsystudio** [comment]
Please Vogtinator, could you upload a copy of the new v1.3 Firebird with the relocations in .text removed?
I hope the error mesage and other issues get out with that fix. Have a good day.

**Comment by erwor** [comment]
Can't start emulating on Android Nougat, using Firebird v1.3

**Comment by Vogtinator** [comment]
Sure: [firebird.zip](https://github.com/nspire-emus/firebird/files/1385747/firebird.zip)
