### ISSUE TITLE
Please rename the project

### ISSUE THREAD

**Issue by mariuz** [nspire-emus/firebird#58]
There is another software project called Firebird 

https://en.wikipedia.org/wiki/Firebird_(database_server)#Mozilla_Firefox_name_conflict

**Comment by adriweb** [comment]
Lol, nope, lots of software share the same name, it's not a problem especially since they have nothing to do with each other, i.e. not actively trying to steal users from each other.

**Comment by mariuz** [comment]
http://firebirdsql.org/en/firebird-brand-faq/

**Comment by adriweb** [comment]
Sure, then I'll let @Vogtinator reply :)

Then again, we haven't heard any complaint or anything, in fact we (well, I at least) wasn't aware of anything more that the name already existed, certainly not their trademark thing.
That may only happen if some people just start complaining to Mozilla, probably only to annoy us...

**Comment by adriweb** [comment]
Also, I can't seem to find (well; I looked only for a few minutes) their trademark application for "Firebird", only their FAQ seems to mention all that.
For instance, here in Europe: https://euipo.europa.eu/eSearch/#basic/1+1+1+1/50+50+50+50/firebird or on http://tmsearch.uspto.gov/ for the US
(I do see quite a lot of other "Firebird" trademarks though; including software. This is giving me the impression that the Mozilla stuff isn't quite as "serious" as the FAQ seems ot make it look like.)

Any pointers/links?

**Comment by Vogtinator** [comment]
The official name of this project is "Firebird Emu", "Firebird" is just the short form of it, used as repo name and name of the resulting binary.
The name is also used in many other places, so this is not an issue.
