### ISSUE TITLE
Low Memory message, with plenty available

### ISSUE THREAD

**Issue by gchiozzi** [nspire-emus/firebird#59]
As soon as I do a couple of things with the calculator on windows 7 (and I think also on Windows 10), I get a "Low Memory" error message.

For example, I can systematically reproduce the problem just by following this simple workflow:
- reset the emulator
- enter the Calculator scratchpad
- press the "catalogue" button

I am having the same problem with both firebird and kArmTI, on  and therefore I think it is a problem with the engine or with my configuration/images.
But it seems I do not have this problem on Android using the same images.

Any idea/suggestion?

![nspire-status](https://cloud.githubusercontent.com/assets/10168547/19801055/d9789f86-9cfd-11e6-9dad-6e129ff27982.PNG)
![nspire-lowmemory](https://cloud.githubusercontent.com/assets/10168547/19801060/dcd8e1f4-9cfd-11e6-9687-2e93fa647e73.PNG)

Thanks for the help!
BTW: the application is great. Would just be very useful to have a complete keyboard representation, with all labels. What about a bitmap?

**Comment by Vogtinator** [comment]
> But it seems I do not have this problem on Android using the same images.

Ok, that indicates it is an issue with the IA-32 JIT. Can you try to run ```t-``` in the debugger console and then reset the device? It'll be slow but if it works, it's definitely the JIT.

> BTW: the application is great. Would just be very useful to have a complete keyboard representation, with all labels. What about a bitmap?

The version in this repo already has it, but there are currently no binary builds for windows available.

**Comment by gchiozzi** [comment]
Thanks for the quick reply!

What I did is:

-> reset
-> Enter debugger
-> t-
->c
->procedure.... still error
-> reset
-> procedure.... still error

It seems that disabling instruction translation does not help (unless I did some step wrong).
Are you able to reproduce the problem following my simple steps?
It looks to me too easy to reproduce to be a general problem that nobody else noticed.
Is there some external dependency/library you the engine is using and that is not packed in the distribution?

Thanks!
                   Gianluca

**Comment by Vogtinator** [comment]
> It seems that disabling instruction translation does not help (unless I did some step wrong).
> Are you able to reproduce the problem following my simple steps?

No, I cannot reproduce your issue on Linux x86-64 at all, using OS 3.6.0.546. I tried with the 0.30 version, so the same as yours.

> Is there some external dependency/library you the engine is using and that is not packed in the distribution?

No, firebird only depends on Qt and that only if you build the Qt UI.

**Comment by gchiozzi** [comment]
I think it is a problem with Windows. Do you (or anybody else) have a windows machine to try?
I will try linux during the weekend to see what happens there with my images.

**Comment by adriweb** [comment]
Yes I'm about to try on my Windows VM.

**Comment by adriweb** [comment]
No problem here on my Win10 VM testing a freshly created OS 3.6 CX CAS image on the windows release version.

**Comment by Vogtinator** [comment]
Did you use a special manuf.img (or none) during creation of the flash image? Can you post the boot log?
It might be that the OS somehow thinks that it's running on a 32MiB CX.

**Comment by gchiozzi** [comment]
Here is my bootlog:
[BootLog.txt](https://github.com/nspire-emus/firebird/files/559786/BootLog.txt)

Honestly, I do not remember how I generated the boot/img files: I did it several years ago.
I did it in 2014 and I remember using ndless and polydumper on my own TI.
This are files I see in my ROM folder:

09/09/2014  20:41           524,288 boot1.img.tns
09/09/2014  20:41         2,752,512 boot2.img.tns
09/09/2014  20:41           917,504 diags.img.tns
09/28/2016  17:18         9,022,542 Snap
09/10/2014  10:52       138,412,032 TI_NspireCXCAS_3.6.0.550.bin
09/09/2014  20:23        12,428,059 TI_NspireCXCAS_3.6.0.550.tcc

May be there is something wrong with one of these?

    Thanks!

                Gianluca

**Comment by Vogtinator** [comment]
@gchiozzi 

My guess was right:
> SDRAM size: 32 MB

The Nspire CX (CAS) has 64 MiB of RAM, which is set that way in the manuf.
You didn't use the manuf of your calc, and the tool you used to generate it didn't put the value for a CX at the right place. Use a hex editor to the change the four bytes at 0x880 from ```11 80 01 FE``` to ```12 80 01 FC```.

**Comment by gchiozzi** [comment]
Super!
It works :-)
Thanks for the great support: quick, competent and precise!
