### ISSUE TITLE
v1.1.1 crash on iPhone6, iOS 9.0.2

### ISSUE THREAD

**Issue by bob8490** [nspire-emus/firebird#62]
Title.  Crash when starting emulation.  On opening the app, I get "could not resume emulation" and when pressing Start I get a hard crash back to SpringBoard.

**Comment by bob8490** [comment]
Crash log:  http://pastebin.com/gzXnZjRB

**Comment by adriweb** [comment]
Thanks for the details (looks like I should include debug symbols next time :P)

Hmm.. Looks like an issue with the Kit (flash/boot1 setup). What do you have there?

It works just fine for me on my iPhone 7 (iOS 10) ; as the arch is the same (64bit running the 32bit app), we know at least it's not an issue with this...

**Comment by bob8490** [comment]
Boot1, flash, and state were working before.

I'll grab the copy from my iPad (also v1.1.1) and try that.

I'll report with results in about an hour.

**Comment by adriweb** [comment]
Let's see with that one, the crash log should hopefully be better: [firebird_111_jit_with_symbols.ipa.zip](https://github.com/nspire-emus/firebird/files/622654/firebird_111_jit_with_symbols.ipa.zip)

**Comment by bob8490** [comment]
I think the version I had did have some non-standard JIT stuff going on. It was a debug build, if I remember correctly.

I'll verify that as well. I still have the .ipa somewhere.

**Comment by adriweb** [comment]
You might want to try with a freshly generated flash image (and no state, for now) from the desktop Firebird, as the format changed.

**Comment by bob8490** [comment]
I'll do that.

So make it and hour and a half for me to get home and try that.

Thank you!

**Comment by Vogtinator** [comment]
It looks like it jumped to JIT code and that caused a SIGBUS. Most likely the instructions were not mapped RWX or the cache did not get flushed correctly.

**Comment by adriweb** [comment]
Yeah there isn't supposed to be any JIT on 64bit devices (yet, anyway), so I'll have to make a separate build...

**Comment by Vogtinator** [comment]
The crash log shows a 32bit execution context, so it should work.

**Comment by adriweb** [comment]
Well, who knows... Just in case so that @bob8490 can try several things if needed, here's a build without JIT: [firebird_nojit.ipa.zip](https://github.com/nspire-emus/firebird/files/623118/firebird_nojit.ipa.zip)

**Comment by bob8490** [comment]
It worked without JIT!  :D
So something with the 32/64 bit check is going wrong, I guess?

**Comment by adriweb** [comment]
Well, that's the thing: there's no 32/64bit check, only a JB check... so I'll have to change that, until there's a 64bit JIT.
Thanks for the tests ; I've also updated the 1.1.1 release to include this non-JIT version.

**Comment by adriweb** [comment]
Great news: we've managed to get the JIT working on iOS, even when non-jailbroken, and on both 32-bit and 64-bit devices!
This will be in the 1.2 version, probably released tomorrow :)
