### ISSUE TITLE
Build error on ubuntu 16.10

### ISSUE THREAD

**Issue by Roemke** [nspire-emus/firebird#63]
Hello,
I'm trying to compile under ubuntu16.10. I get some warnings and at least an error of the linker. 
I have appended the messages, I searched a little but I don't found a solution.
Thanks 
 Karsten

warnings, latest is:
../core/mem.c:425:6: note: ‘memory_suspend’ was previously declared here
 bool memory_suspend(emu_snapshot *snapshot)
      ^
../core/mem.c:425:6: note: code may be misoptimized unless -fno-strict-aliasing is used
and the errors:
/usr/bin/ld: /tmp/ccSqysCM.ltrans0.ltrans.o: relocation R_X86_64_32S against symbol `_ZN10QArrayData11shared_nullE@@Qt_5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans2.ltrans.o: relocation R_X86_64_32 against symbol `arm' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans3.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans4.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans5.ltrans.o: relocation R_X86_64_32S against hidden symbol `_ZTV22QQuickWidgetLessBroken' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans6.ltrans.o: relocation R_X86_64_32S against symbol `_ZN9QListData11shared_nullE@@Qt_5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans7.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans8.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans9.ltrans.o: relocation R_X86_64_32S against hidden symbol `timer.lto_priv.233' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans10.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN9EmuThread16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans11.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN10MainWindow16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans12.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN11FlashDialog16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans13.ltrans.o: relocation R_X86_64_32 against hidden symbol `reg_name' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans14.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans15.ltrans.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans16.ltrans.o: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans17.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN10MainWindow16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans18.ltrans.o: relocation R_X86_64_32S against hidden symbol `_ZTV11FlashDialog' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans19.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN17USBLinkTreeWidget16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans20.ltrans.o: relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans21.ltrans.o: relocation R_X86_64_32S against symbol `_ZN9QListData11shared_nullE@@Qt_5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans22.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN10MainWindow16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans23.ltrans.o: relocation R_X86_64_32S against symbol `_ZN10QArrayData11shared_nullE@@Qt_5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans24.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans25.ltrans.o: relocation R_X86_64_32S against hidden symbol `_ZL17progress_callbackiPv.lto_priv.178' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans26.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZL6os_ext.lto_priv.265' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans27.ltrans.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ccSqysCM.ltrans28.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN13FBAboutDialog16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans29.ltrans.o: relocation R_X86_64_32S against hidden symbol `_ZN10MainWindow25usblink_progress_callbackEiPv' can not be used when making a shared object
/usr/bin/ld: /tmp/ccSqysCM.ltrans30.ltrans.o: relocation R_X86_64_32 against hidden symbol `_ZN17USBLinkTreeWidget16staticMetaObjectE' can not be used when making a shared object
/usr/bin/ld: final link failed: Nicht darstellbarer Abschnitt bei Ausgabe
collect2: error: ld returned 1 exit status
Makefile:316: die Regel für Ziel „firebird“ scheiterte
make: *** [firebird] Fehler 1

**Comment by Vogtinator** [comment]
Try to add ```-no-pie``` to QMAKE_LFLAGS in firebird.pro

**Comment by Roemke** [comment]
yes - that was the solution, thank you very much, a really fast answer.
Karsten

**Comment by Legimet** [comment]
I will try to add detection of the -no-pie flag in the pro file. Also the nonstandard -nopie, which was used by older hardened toolchains.
