### ISSUE TITLE
Crash immediately after attempting to start emulation on iOS

### ISSUE THREAD

**Issue by pangeacake** [nspire-emus/firebird#64]
9.3.3, jailbroken iPhone 6
1.3.3 Firebird Emu

(this issue was mentioned in #28)

after I press the start button, the LCD screen turns black for a split second and the app crashes. This also happened in a previous version of Firebird (0.20, I also tested with no tweaks enabled on that version). I will try to get some information from crash logs soon.

**Comment by adriweb** [comment]
I'll try to code something better/specific for this situation tonight (can't test it myself) but in the meantime can you try the noJIT version of the release?

**Comment by pangeacake** [comment]
I will try that soon. Here is the crash log: https://beta.paste.ee/p/qHnIS

**Comment by Vogtinator** [comment]
Yes, that's indeed the JIT crash. Thanks for providing the log!
There will likely be a fixed JIT in v1.1.2 that supports the R^X enforcement of iOS 9 running on AArch64. (https://github.com/hrydgard/ppsspp/issues/8122)

Closing for now, please reopen if the issue persists with the noJIT build or a later v1.1.2 release.

**Comment by adriweb** [comment]
Here's a build with the JIT, but which disables itself at runtime if it's either not a jailbroken-device, or a 64bit one.
Please test and let us know if that works. If so, an updated release should be coming sometime soon.

**Comment by adriweb** [comment]
Great news: we've managed to get the JIT working on iOS, even when non-jailbroken, and on both 32-bit and 64-bit devices!
This will be in the 1.2 version, probably released tomorrow :)
