### ISSUE TITLE
TI_OS_INSTALL_IMAGE_INVALID when install 4.2.0.532

### ISSUE THREAD

**Issue by krystalgamer** [nspire-emus/firebird#65]
I dumped everything i needed with Polydumper( my calcultor is HW-O). When i was creating a flash(created for HW-A, dunno if correct) i couldn't select the OS because of the different extension so i left it. 

When it started it said "Operating System not found. Install OS now." so i dropped in the file transfer tab and after it transfering i got that error.
Any ideias?

**Comment by Vogtinator** [comment]
This likely means that you tried to install a CAS OS on non-CAS hw or the other way around.

**Comment by krystalgamer** [comment]
I feel so dumb. The default option when creating a flash is "CX CAS" and me being dumb didn't see it.

Thank you so much!
