### ISSUE TITLE
"q" not implemented

### ISSUE THREAD

**Issue by krystalgamer** [nspire-emus/firebird#66]
Testing the built-in debugger i found the command [q](https://github.com/nspire-emus/firebird/blob/62f942ad7a025e5edb248a3b3e578b0c9ef638ed/core/debug.cpp#L207) is not implement. Calling it gives "Unknown command q".

I don't see any usage for it, too. It just looks like it's an artifact from gdb.

**Comment by Vogtinator** [comment]
Indeed, the implementation got removed as firebird has it's own way to quit now.
Fixed now, thanks!
