### ISSUE TITLE
Android: Allow scrolling even if touch started on a button

### ISSUE THREAD

**Issue by plusCubed** [nspire-emus/firebird#68]
If I touch on a button and start scrolling (without releasing), the app would not scroll. Right now I have to scroll by starting my touch in a blank space.

I believe the cause of this is that a button is activated as soon as it's touched on, rather than when it is released. If it's changed to the latter, then the touch can be canceled when a scroll is detected. 

(I do not know if this is easy to do in Qt, but it's the default behavior of buttons in Java Android development.)

**Comment by Vogtinator** [comment]
Actually, this is by design. Simply by removing this line https://github.com/nspire-emus/firebird/blob/master/qml/NButton.qml#L36 the behaviour is how you want, however it's irritating to use.

**Comment by plusCubed** [comment]
Ah, due to the scrolling I would imagine? (If so, is there a parameter to tweak for the scrolling to start only after some movement?)

**Comment by Vogtinator** [comment]
Exactly. Otherwise the keypad would wobble around on each button press. Some threshold could be implemented though by just setting preventStealing manually I suppose.

**Comment by Vogtinator** [comment]
This seems to work reasonably fine in master now.
