### ISSUE TITLE
Cannot load files onto latest iOS version

### ISSUE THREAD

**Issue by p0wer0n** [nspire-emus/firebird#7]
There is no option to load the boot1.img and boot2.img files into the emulator in the newest versions of the iOS versions. Please fix this

**Comment by Vogtinator** [comment]
This is a known issue in the mobile UI, for now just comment out the "DEFINES += MOBILE_UI" line in firebird.pro

**Comment by adriweb** [comment]
I'm working on something that would solve that. I'll update this ticket when ready.

**Comment by p0wer0n** [comment]
Thanks!

**Comment by adriweb** [comment]
I have a working solution, but the app crashes because of an unrelated issue later on...

If you want to try it, before it gets into the repo, in `qmlbridge.cpp`, here's the updated `QMLBridge::restart()` method:
```c++
bool QMLBridge::restart()
{
    if(emu_thread.isRunning() && !emu_thread.stop())
        return false;

#if defined(Q_OS_IOS)
    QString docsPath = QStandardPaths::standardLocations(QStandardPaths::DocumentsLocation)[0];
    qDebug() << docsPath;
    std::string boot1_path_str = (docsPath + "/boot1.img").toStdString();
    std::string flash_path_str = (docsPath + "/flash.img").toStdString();
     if (access(boot1_path_str.c_str(), F_OK) != -1 && access(flash_path_str.c_str(), F_OK) != -1) {
         // Both files are good to use.
        emu_thread.boot1 = boot1_path_str;
        emu_thread.flash = flash_path_str;
    } else {
        // TODO: alert the user that the files need to be there
    }
#else
    QSettings settings;
    emu_thread.boot1 = settings.value("boot1").toString().toStdString();
    emu_thread.flash = settings.value("flash").toString().toStdString();
#endif

    emu_thread.start();
    return true;
}
```
And don't forget `#include <unistd.h>` at the top of the file.

With that code, you just have to transfer `flash.img` and `boot1.img` with iTunes into the Firebird app.

**Comment by p0wer0n** [comment]
Is this with MOBILE UI enabled?

**Comment by adriweb** [comment]
Yes, that's only for the Mobile UI. The non-mobile UI has a file opening dialog anyway (but... as told before, the app crashes very early anyway, so you can't get to that point :/)

**Comment by adriweb** [comment]
Actually, my bad, I was testing with a bad file, it's working as intended in the Mobile UI :)
![Screenshot](https://i.imgur.com/LqEQIpXm.png)
