### ISSUE TITLE
Emulation startup freezes at Nspire screen

### ISSUE THREAD

**Issue by ctian1** [nspire-emus/firebird#72]
iOS 9.3.3 jailbroken w/ pangu, iPhone 6

gets stuck at TI-Nspire loading screen at about 60-70%

**Comment by Vogtinator** [comment]
Please add some more information, which OS version, which calculator hardware, how did you create the flash image?

Which version of firebird are you using? Are you able to debug iOS applications?

**Comment by pangeacake** [comment]
Using latest firebird, Nspire CAS, 4.2.0.432, created flash image using ndless + polydumper + firebird on Windows

I have a mac.

**Comment by adriweb** [comment]
Please try the [latest release](https://github.com/nspire-emus/firebird/releases/latest) and reopen the issue if needed (generic comment, might not be 100% related)
