### ISSUE TITLE
../core/os/os-linux.c:4:10: fatal error: 'sys/mman.h' file not found

### ISSUE THREAD

**Issue by parrotgeek1** [nspire-emus/firebird#73]
I'm compiling on Mac. Literally just installed QT, added it to $PATH, followed instructions in Readme. What gives?

**Comment by Legimet** [comment]
Is your toolchain set up correctly?

**Comment by parrotgeek1** [comment]
QT can't compile anything, actually. No include files are found. Even in Qt creator. I intalled with default options

**Comment by parrotgeek1** [comment]
Can you compile my fork for mac cause I still can't get this to work? https://github.com/parrotgeek1/firebird
sorry to bother you

**Comment by parrotgeek1** [comment]
FIXED!!!! xcode-select --install
