### ISSUE TITLE
Where can I find a "Ubuntu" build?

### ISSUE THREAD

**Issue by lexterror** [nspire-emus/firebird#75]
Could someone please post a build for "Ubuntu"

**Comment by Vogtinator** [comment]
There are currently no debian packages available as nobody involved in this project knows how to make one. If you know how, please post everything needed here!

**Comment by adriweb** [comment]
http://askubuntu.com/a/320468/572305 might help, I'll try at some point...

**Comment by adriweb** [comment]
This is very much a WIP and while I've been able to create the .deb file, @Vogtinator is currently trying to use it with OBS to make the thing better...

  1. Open a terminal and do this (changing xenial by your version name if need be):
```bash
sudo add-apt-repository ppa:beineri/opt-qt562-xenial -y
sudo apt-get update
sudo apt-get install -y --force-yes -qq qt56base qt56declarative qt56quickcontrols
```
  2. install this .deb file (unzip first, if course): [firebird-emu_1.2-1_amd64.deb.zip](https://github.com/nspire-emus/firebird/files/784247/firebird-emu_1.2-1_amd64.deb.zip)
  3. launch the newly installed firebird app...

Let us know how/if that works

**Comment by Vogtinator** [comment]
Ubuntu 16.10 should appear shortly on https://software.opensuse.org/download.html?project=home%3AVogtinator%3Afirebird-emu&package=firebird-emu
