### ISSUE TITLE
"The current kit does not have a snapshot file" error on Microsoft Surface

### ISSUE THREAD

**Issue by gchiozzi** [nspire-emus/firebird#77]
Hi,

I have two Microsoft Surface machines and on both I get the following error when exiting:

     "The current kit does not have a snapshot file" 

and then the snapshot is not saved, i.e. when I restart the emulator I get the status from the previous snapshot, saved by hand from the menu without problems.

I have exactly the same configuration (I believe) on a Windows 7 desktop and laptop and it works fine there.

I have seen that on the surface there are missing registry keys, in particular the key with the path to the snapshot:

    "snapshotPath"="D:/Software/tinspirecx-Firebird/ROMS/Snap"

I have imported the ndless\firebird registry tree from the W7 machine where it works on the Surface and now that works as well.

Any idea why the registry is incomplete on the surface?

One difference might be that on the Surface I am using Microsoft Family accounts, while on the other machines I am using normal domain accounts (but in both case with administrator rights).

I attach the registry of the two machines.
[ndless_firebird-registry.zip](https://github.com/nspire-emus/firebird/files/858718/ndless_firebird-registry.zip)

**Comment by Vogtinator** [comment]
This is fixed in https://github.com/nspire-emus/firebird/commit/740038b953221e6a4163b4a98fafb0ee8c2ccf7a
Make sure you're running Firebird v1.2.

**Comment by gchiozzi** [comment]
Thanks.
I was still running 1.1 and I had not realized that 1.2 had fixed this problem.
I imagine that the registry was OK on the older machines where I had used versions older than 1.1 that were not affected by the issue and had a full registry.

     Great job!

              Gianluca
