### ISSUE TITLE
universal windows platform app version

### ISSUE THREAD

**Issue by Jo900** [nspire-emus/firebird#78]
Before buy an android phone for good, i think can be great have firebird on UWP version.
Can be set up on windows store (free or payment), and i can finally have the emulator on my windows phone.
Let me know if is possible to have this conversion. 
Thanks

**Comment by Vogtinator** [comment]
It should be easy to just build the app for UWP. It just needs someone with a dev environment to put some time into it. I do not use windows, so I can't do it.

**Comment by Jo900** [comment]
maybe there is someone you know with dev environment.
i have the desktop app converter, the BaseImage-14393.wim, and win10 sdk ready.
If you write to me some detailed instructions i can make a try...

**Comment by Vogtinator** [comment]
Just download Qt, open Qt Creator and build the project for WinRT. I don't know more details...

**Comment by Jo900** [comment]
There is someone you can ask to make the build for uwp ?

**Comment by Vogtinator** [comment]
@adriweb made the normal windows builds, so maybe he can have a try.

**Comment by adriweb** [comment]
I have no intent to make more things than the one already done - I have no other stuff than Qt Creator installed.
@Jo900 : since you have the win10 SDK and whatnot, just [download Qt Creator here](https://www.qt.io/download-open-source/#section-3) (choose the WinRT one corresponding to the VS version you have, 2015 is preferred if not required) and give it a try.

**Comment by Jo900** [comment]
@adriweb please write to me some guidelines step by step on private messages, never tried that before, and not very used with qt creator. I have already installed qt creator, and visual studio community suite.
I'm happy if i can make that :) just need some help to start. Thanks.

**Comment by adriweb** [comment]
I really don't have anything more to tell than that:

1. clone the repo (or just download [the zip](https://github.com/nspire-emus/firebird/archive/master.zip) and extract it somewher)
2. launch Qt Creator
3. open the .pro file form the repo, and click OK/Next/something when Qt Creator asks you to
4. Hit the Green Play button at the bottom left (it may take a few secs to get available)

**Comment by Jo900** [comment]
I'm trying, ct creator still give me some errors.... when you have time if you can build the uwp version, i can make a little donation for effort and support. :)
(best idea is to place on windows store at payment, i would buy also)
Thanks

**Comment by adriweb** [comment]
Well, please copy/paste the errors, maybe we can solve it

**Comment by Vogtinator** [comment]
> when you have time if you can build the uwp version, i can make a little donation for effort and support

Even if I wanted to, I couldn't. I do not use windows for practical and ethical reasons.

> (best idea is to place on windows store at payment, i would buy also)

Nah. I don't want to monetize this. While the license would allow it, anyone can just build it for free anyway. TI would not like it either and neither would the users, after they realize that they need to own a calc anyway.

**Comment by adriweb** [comment]
(And as for me, I use my windows VM less and less, and I'm pretty sure it doesn't have enough space for the Windows SDK... :/)

**Comment by Jo900** [comment]
i will write here all detail errors on weekend, now i'm far from home. I remember was a qmake error and a winruntime something. qt detect automatic debugger and compiler, when i select c++ compiler from vs give me warning that is not good to produce code something like that. I think is not properly configured the whole kit. (is first time i try that stuff, usually i'm not noob like that :))) thanks for patience )

**Comment by Vogtinator** [comment]
Let's close this as WONTFIX - UWP doesn't have any real benefits and requires building with VC++...
