### ISSUE TITLE
[Please Close] Info.plist has incorrect/missing values.

### ISSUE THREAD

**Issue by p0wer0n** [nspire-emus/firebird#8]
The UIFileSharingEnabled value in the latest build's info.plist for iOS is missing, as well as the CFBundleExecutable is pointing to "firebird-master" instead of firebird. This is easily fixed by changing these values.

**Comment by adriweb** [comment]
Regarding `UIFileSharingEnabled`, it's there: https://github.com/nspire-emus/firebird/blob/master/Info.plist#L36-L37
Hence why you can already transfer files from within iTunes :)

I'll look at the `CFBundleExecutable` thing.

**Comment by p0wer0n** [comment]
The issue was fixed at some point today, and I just found out. Thanks for all of these fast responses.
