### ISSUE TITLE
I set mine up wrong. How do I delete the configuration?

### ISSUE THREAD

**Issue by BobFrederiksen** [nspire-emus/firebird#81]
I just want to restart firebird like how it was when I just downloaded. I checked my appdata folder but I didnt find it. How do I do this?
Thanks

**Comment by Vogtinator** [comment]
You shouldn't need to do that, which settings are hard to reset?

**Comment by BobFrederiksen** [comment]
It doesn't let me resume my previous session when reopened. Every time I open it it tells me "resuming failed" and then I have to start over. How do I fix this? Also from the posts I've read by you across forums you seem very experienced. Do you think you could help me with compiling different versions of nlaunchy? I have ubuntu but I just don't know how to make nlaunch.c into the nlaunch.tns that I need to put on my calculator.
Thanks,
Bob Frederisken

**Comment by Vogtinator** [comment]
> It doesn't let me resume my previous session when reopened. Every time I open it it tells me "resuming failed" and then I have to start over.

Just save a new snapshot after restarting the emulation and the current (corrupted) one will be overwritten. To get rid of the snapshot altogether, remove the file from the disk.

> Also from the posts I've read by you across forums you seem very experienced. Do you think you could help me with compiling different versions of nlaunchy?

Nope.

> I have ubuntu but I just don't know how to make nlaunch.c into the nlaunch.tns that I need to put on my calculator.

There are instructions in the nlaunchy repo which work just fine.

**Comment by BobFrederiksen** [comment]
Thanks for your help on the saving problem. That works. As for nlaunchy I tried using this guide: https://github.com/ndless-nspire/Ndless/wiki/Ndless-SDK:-C-and-assembly-development-introduction but it didnt work as I couldn't get some of the prerequisite files needed. Where can I find those? I also didn't see the instructions in the nlaunchy repo that you are talking about. It did say how to change the file to work for different purposes, but not how to compile it into a tns file.
