### ISSUE TITLE
Firebird won't work on kindle fire

### ISSUE THREAD

**Issue by mshroye1** [nspire-emus/firebird#86]
Yes i know it's not meant for kindle fire but you are able to download android apps to use on kindle. However when I open it up and press I to install the app goes through the installation process but when it gets to the end the LCD screen of the emulator goes blank and I can't get the screen to come back on

What's up

**Comment by Vogtinator** [comment]
Please upload the adb log of the session and provide some more information, especially the OS and boot2 versions you used to generate the flash image. Does the same procedure work on the desktop firebird?

**Comment by kylewill0725** [comment]
Sounds like what I have.

[Adb Log filtered by org.firebird.emu](https://gist.github.com/kylewill0725/40f3230c17c93226debfa958f1ff1034)

Type: HW-A CX CAS
OS: CX CAS 4.4.0.532
I'm not certain what you mean by boot2 versions but was dumped from my calculator running the same OS.
The same procedure did work on the desktop.

**Comment by Vogtinator** [comment]
I was able to reproduce the issue and it's fixed now. Test build here:

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1065176/firebird.apk.zip)
