### ISSUE TITLE
The logs are not redirected to logcat for Android builds.

### ISSUE THREAD

**Issue by Florin9doi** [nspire-emus/firebird#88]

**Comment by Vogtinator** [comment]
What do you mean by "logs", the serial output?
It's not easily possible to do that, as the serial output assumes a proper terminal for escape sequences such as ```\r``` for progress output.

**Comment by Florin9doi** [comment]
I think __android_log_print works well

**Comment by Vogtinator** [comment]
Not quite, for the bootup you'd get this output:

```
Loading from Boot 2 partition...

0 %

1 %

2 %

3 %
```

and so on...

**Comment by Florin9doi** [comment]
You're right. Please close this ticket.
