### ISSUE TITLE
The application do not dynamically requires WRITE permission on Android 6.0 

### ISSUE THREAD

**Issue by Florin9doi** [nspire-emus/firebird#89]
The application do not dynamically requires WRITE permission on Android 6.0, and as result, it fail to open the flash files.

It fails in flash.cpp:412 with Errno13:Permission denied
```
    flash_file = fopen_utf8(filename, "r+b");
    if (!flash_file) {
        gui_perror(filename);
        __android_log_print(ANDROID_LOG_WARN, "org.firebird.emu", "flash_open1 %s:%d:%s",
                            filename, errno, strerror(errno));
        return false;
    }
```

**Comment by Vogtinator** [comment]
It has:

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

Is that not enough?

**Comment by Florin9doi** [comment]
Since Android 6.0 it's no longer enough to add the permissions to manifest. The permissions should be requested at runtime:
- https://developer.android.com/training/permissions/requesting.html
- https://stackoverflow.com/questions/33162152/storage-permission-error-in-marshmallow

I was able to open the flash files moving them from SD Card (/storage/XXXX-XXXX/) to internal storage (**/sdcard/**). 
Maybe this limitation worth to be added in Readme.

**Comment by Vogtinator** [comment]
Looks like it just needs to be rebuilt with Qt >= 5.8: https://bugreports.qt.io/browse/QTBUG-50759

**Comment by Vogtinator** [comment]
If you have an AArch64 (64-bit ARM) phone, you can try https://github.com/nspire-emus/firebird/pull/87

The test binary is built with Qt 5.9 beta 4 (IIRC) and you can also give some feedback on the JIT :D

**Comment by Florin9doi** [comment]
I don't have any ARM64 device now, but I've been able to build it myself using Qt5.9 and TargetSDK 23 and now I receive:

> D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.firebird.emu, PID: 22347
E AndroidRuntime: java.lang.UnsatisfiedLinkError: **dlopen failed: /data/app/org.firebird.emu-1/lib/arm/libfirebird.so: has text relocations**
E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
E AndroidRuntime: 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:244)
E AndroidRuntime: 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:649)
E AndroidRuntime: 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:183)
E AndroidRuntime: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
E AndroidRuntime: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

The cause is this change: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime
>On previous versions of Android, if your app requested the system to load a shared library with text relocations, the system displayed a warning but still allowed the library to be loaded. Beginning in this release, the system rejects this library if your app's target SDK version is 23 or higher.

**Comment by Vogtinator** [comment]
Yes, you need to set the target SDK lower than 23.

This is intentional, text relocation actually make the core faster.

**Comment by Florin9doi** [comment]
So there is no way to have both?

**Comment by Vogtinator** [comment]
Not in one binary at least...

Shouldn't apps with targetSDK < 6.0 not need to request permissions manually due to backwards-compatibility?

You can build without .text relocations by changing the `1` to a `0` in asmcode_arm.S:28 (https://github.com/nspire-emus/firebird/blob/master/core/asmcode_arm.S#L28)

**Comment by Florin9doi** [comment]
I've tried to use RequestPermissions API (https://github.com/Florin9doi/firebird/commit/926bc89c519952096795e29b05e8df5fe2e27ed3) but it still don't have write permissions to SD card. It's probably completely forbidden. 
Let's close this thread
