### ISSUE TITLE
GPIO Original Status fail

### ISSUE THREAD

**Issue by flaghacker** [nspire-emus/firebird#91]
I'm trying to set up Firebird, I followed the steps in the "First Time Setup" guide, but when I now start the emulation I get the following screen:
![image](https://user-images.githubusercontent.com/7887115/27010784-2f061d28-4ead-11e7-8ffe-ecf64c7a1614.png)
 When I then press ESC I get the following screen:
![image](https://user-images.githubusercontent.com/7887115/27010787-412ee642-4ead-11e7-84ef-ca55f4ddabc6.png)

I copied all of the dumped files from PolyDumper to my computer and out them in the configuration like this:

![image](https://user-images.githubusercontent.com/7887115/27010793-63d4830a-4ead-11e7-9cc5-a02c0d249f07.png)
![image](https://user-images.githubusercontent.com/7887115/27010800-7b2df0d6-4ead-11e7-8fa1-be17513a5bad.png)
These are all of the files:
![image](https://user-images.githubusercontent.com/7887115/27010804-910def00-4ead-11e7-9861-afe63be387ef.png)

Am I doing something wrong?

**Comment by Vogtinator** [comment]
It tries to boot to the diags image instead of boot2, can you try it with a flash image without specifiying a diags image?

**Comment by flaghacker** [comment]
I tried it like this:
![image](https://user-images.githubusercontent.com/7887115/27010837-6224f674-4eae-11e7-9e52-080e0e5c7d28.png)

But I still get the same result.

**Comment by Vogtinator** [comment]
That's not possible as without a diags imag there is no diags it can possibly run. Make sure it's actually using the new flash file you generated

**Comment by flaghacker** [comment]
Well I think I'm doing everything correctly, here's a gif of the process:
![gif](http://i.imgur.com/Qnxl8zc.gifv)

**Comment by adriweb** [comment]
Use the Reboot menu item, not Reset :)

**Comment by flaghacker** [comment]
Ah okay, dump mistake :D

Now I get the following:
![image](https://user-images.githubusercontent.com/7887115/27010963-2853c562-4eb1-11e7-8ca5-33c564a52826.png)

**Comment by adriweb** [comment]
Hm, weird (?), but can you click on the plug icon to enable transfers, then transfer the OS (should be a drag'n'drop in the transfer tab, I think)

**Comment by Vogtinator** [comment]
Touchpad OS preloading fixed, was a typo...

Note that the touchpad CAS OS somehow thinks it's a clickpad calc and the keymap does not match at all, making it practically useless. To install the preloaded OS, you need to press A instead of I.

**Comment by flaghacker** [comment]
Yea when I drag in the OS manually the keys didn't map indeed.

**Comment by Vogtinator** [comment]
@adriweb normally does the windows builds

As that takes a while I quickly patched the two bytes in the .exe file directly, just replace it:
[firebird.zip](https://github.com/nspire-emus/firebird/files/1068948/firebird.zip)

**Comment by flaghacker** [comment]
Thanks, the emulation is working perfectly now!

Is there a way to fix the broken keymap?

**Comment by Vogtinator** [comment]
Unfortunately it's not that easy. I have no idea why the OS thinks it's running on clickpad hardware (yet!) and adding a clickpad keypad to firebird isn't that easy as it needs to be designed from scratch.

**Comment by flaghacker** [comment]
That's strange because the keyboard displayed in firebird does exactly match the one on my physical calculator. Couldn't this be fixed by building a simple "mapping" from physical keys to the inputs the OS understands?

Thanks for helping either way!

**Comment by Vogtinator** [comment]
> That's strange because the keyboard displayed in firebird does exactly match the one on my physical calculator.

Yes, but the OS does not agree there.

> Couldn't this be fixed by building a simple "mapping" from physical keys to the inputs the OS understands?

You would need two of those - one for the keypad shown and one for keyboard shortcuts.
And that wouldn't solve the issue either as firebird does not know that the OS assumes a wrong keypad layout.

**Comment by Vogtinator** [comment]
Issue fixed! You can either use a hex editor and change the byte at position 0x846 to ```02``` instead of ```01``` or use a fixed version of firebird to regenerate a flash image.

**Comment by flaghacker** [comment]
Thanks a lot!
