### ISSUE TITLE
Setup of Emulation Stops at Loading Screen Android

### ISSUE THREAD

**Issue by dexman545** [nspire-emus/firebird#92]
On Android N, using Nspire CX 4.4, with boot1 and start created on Windows.

I start the emulation, then it goes to the loading screen, which then pauses saying "factory image found. Press 'I' to install" I do so, but the LCD always turns off before it installs and I have to start it again.

Basically, I am in a loop that prevents use/installation.

**Comment by Vogtinator** [comment]
> On Android N, using Nspire CX 4.4, with boot1 and start created on Windows.

What do you mean by "start"? The flash image?

> I start the emulation, then it goes to the loading screen, which then pauses saying "factory image found. Press 'I' to install" I do so, but the LCD always turns off before it installs and I have to start it again.

That's probably the same as https://github.com/nspire-emus/firebird/issues/86 - can you verify that the test build works for you?

**Comment by dexman545** [comment]
By "start" I meant the snapshot file (Same file I use on Windows)

The Same issue occurs with the test build.

For clarity, this is the screen I'm stuck on: 
![screenshot_20170614-142235](https://user-images.githubusercontent.com/4873274/27148251-9a9983ba-510d-11e7-8948-54f083043909.png)

**Comment by Vogtinator** [comment]
Can you describe exactly what happens?

**Comment by dexman545** [comment]
I get to that screen, press I, then I wait for it to load...
After pressing I nothing changes on the screen until the LCD decides to turn off. When I click "resume" Firebird says that it cannot resume.

**Comment by Vogtinator** [comment]
Yes, that is exactly the issue I fixed in the test build. Make sure that you did install the right version. I can rebuild the latest version if you want to.

**Comment by dexman545** [comment]
I uninstalled the build I was using and tried to use the test build from the issue you linked, could you rebuild it? I'll uninstall this version again as well

**Comment by Vogtinator** [comment]
Here you go. I verified that it contains the fix (and some other changes):

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1075602/firebird.apk.zip)

**Comment by dexman545** [comment]
Installed it, same issue as before

**Comment by adriweb** [comment]
When you press I, are you sure no other key are pressed/held?

**Comment by dexman545** [comment]
I restarted it, and it was a key being held down (this time "6" for some reason)
It appears to be working now, many thanks for your help.
