### ISSUE TITLE
Rename firebird binary to firebird-emu?

### ISSUE THREAD

**Issue by TC01** [nspire-emus/firebird#97]
Sort of in the same vein as #58, though hopefully slightly less contentious:

I am (slowly) working on making a Fedora package of firebird-emu. One concern that was raised when I submitted [a review](https://bugzilla.rpmfusion.org/show_bug.cgi?id=4444) was the potential name conflict with firebird the database management software.

I read the discussion in #58. I'm not all that concerned about the actual name of the *project* (as noted in the ticket, "firebird-emu" is the full name). I'm more concerned about the name of the *binary*, and the resulting possible collision with the firebird stack, which wants to install /usr/sbin/firebird. Having both executables share the same name isn't ideal, even if they don't get installed into the same place.

Now, we can handle this ourselves downstream by making the packages conflict, or we could potentially rename downstream, though neither are really ideal. It would be nice if this could be resolved upstream, but failing that it would be good to at least get a recommendation on what should be done.

**Comment by Vogtinator** [comment]
I planned this a while ago already, as the organization name was never correct, but just kept for easier backwards-compatibility. I took that opportunity to clean that up a bit and renamed it to org.firebird.firebird-emu, which also means that the .desktop file should be found on wayland platforms as well :-)

Please have a look at PR #98 and tell whether anything is missing.

**Comment by adriweb** [comment]
Done
