### ISSUE TITLE
[question] how do I use the debugger after a crash?

### ISSUE THREAD

**Issue by 0xFireball** [nspire-emus/firebird#99]
I ran a program from my Nspire on Firebird, but it crashed:

![image](https://user-images.githubusercontent.com/15932100/29431612-6b34c450-834d-11e7-94a5-8bc1bd3a89ac.png)

The program was compiled with debugging information, and I see that the emulator has dropped into a kind of debugger mode. How exactly do I use this debugger? I tried some GDB commands but it says "Unknown command" for everything.

In particular I would like to get a stack trace (I know this is possible through GDB) but am not sure how to get it through Firebird.

thanks.

**Comment by Vogtinator** [comment]
Did you try to follow https://github.com/nspire-emus/firebird/wiki/Debugging-with-GDB ?

If you enable `Enter debugger on warning` in the debugging configuration, the data abort will trap into gdb and you can do `bt` to get a stack backtrace.

**Comment by 0xFireball** [comment]
Oddly enough, when I restarted the emulator instead of loading the snapshot and transferred and launched my program, the program didn't crash. I'm not sure what happened. Any idea? I'm very new to Ndless development.

**Comment by Vogtinator** [comment]
That can happen for many reasons, one of which is using memory without clearing it first.

**Comment by 0xFireball** [comment]
All right, so I'm attempting to connect GDB remotely using `arm-none-eabi-gdb -ex "target remote :3333"`. But once it's connected the emu says `In debugger` and I can no longer interact with the screen to launch the program.

**Comment by 0xFireball** [comment]
All right, so I'm attempting to connect GDB remotely using `arm-none-eabi-gdb -ex "target remote :3333"`. But once it's connected the emu says `In debugger` and I can no longer interact with the screen to launch the program.

**Comment by Vogtinator** [comment]
You need to instruct gdb to continue execution, with `cont`. Alternatively, simply do:

```
arm-none-eabi-gdb -ex "target remote :3333" -ex "c" -ex "bt" program.elf
```

to automatically run the commands in the right order.

**Comment by 0xFireball** [comment]
Ah thanks so much, it's working great!
